### ISSUE TITLE
Elysia's Hot Reload No Longer Works

### ISSUE THREAD

**Issue by gungun974** [elysiajs/elysia#100]
Hoi, some time ago I decided to test Bun in a small personal project and came across this library for managing an HTTP server, similar to Express but better.

However, I recently discovered that Bun has a hot reload feature, so I thought I'd try it. 
When I start the Elysia server with --hot and make a change, I get the following error:

```
error: Failed to start server. Is port 8080 in use?
      at /home/gungun974/lab/perso/foss/elysia/src/index.ts:2871:16
      at /home/gungun974/lab/perso/foss/elysia/example/http.ts:118:2
```
To avoid creating an unnecessary issue, I looked into what I might have done wrong. That's why I tested it directly with Elysia's example project, but the issue remains. 
I also looked into the past using `git bisect` and found that the commit 56a56a2846b3f4f31b42bdd47ed9b90b6e7d2dca supposedly introduces this bug.

I personally don't have the time to understand how the library works in order to try fixing it myself. However, I felt it was my duty as a developer to report this issue.

**Comment by SaltyAom** [comment]
You may want to migrate to --watch instead.
--hot is designed to be used with frontend hot reload. But to make it work with server side, Elysia have to manipulate prototype which is not a best practice and best to avoid.
It's noted in some where in Bun documentation that they will update hot reload to work with server-side without the said problem, so Elysia drop the support for --hot.

You can use --watch instead

**Comment by SaltyAom** [comment]
With the release of Bun 1.0, `--hot` now should be working once again.

**Comment by gungun974** [comment]
Yes with the much awaited version 1.0. Bun's hot reload now works which is very nice ^^
Anyway thank you for letting me know about this because otherwise I would have completely missed it xD
