### ISSUE TITLE
Access body error

### ISSUE THREAD

**Issue by alexandre-dos-reis** [elysiajs/elysia#102]
I want to mention that I've read all the docs but didn't find the answer...

I have a handler with validation on the body like this: 

```tsx
  app.post(
    "/cars/:id",
    async ({ body, params }) => {
     // ...
    },
    {
      body: t.Object({
        name: t.String({
          minLength: 3,
        }),
        licence: t.String({
          minLength: 3,
        }),
        status: t.Enum(Status),
      }),
    },
```

How can I access the error on `name` for example ? Thx

**Comment by SaltyAom** [comment]
I assume what you want is to set a custom error message for name? If so you can do something like this:
```ts
new Elysia()
	.post('/cars/:id', async ({ body, params }) => 'Ok', {
		body: t.Object({
			name: t.String({
				minLength: 3,
				error: 'name is required to be more than 3'
			}),
			licence: t.String({
				minLength: 3
			}),
                         status: t.Enum(Status)
		})
	})
```

Otherwise, you can access an error via error lifecycle like this:
```ts
	.post('/cars/:id', async ({ body, params }) => 'Ok', {
		body: t.Object({
			name: t.String({
				minLength: 3,
				error: 'AAWD'
			}),
			licence: t.String({
				minLength: 3
			})
		}),
		error({ code, error }) {
			switch (code) {
				case 'VALIDATION':
					const name = error.all.find((x) => x.path === '/name')

					console.log(name)
			}
		}
	})
```

I understand your frustration about this, so I add this to the documentation in [Error Handling section](https://elysiajs.com/patterns/error-handling.html#custom-error-message)

Let me know if this is what you are looking for.

**Comment by alexandre-dos-reis** [comment]
Thank you, maybe the second example could resolve my problem.

Let me explain my use case, I use Elysia to render Html/Jsx and I want to check user's input using body validation. I want to display error in the returned form if validation if invalid.

Sorry for not describing my use case in the first post.

**Comment by alexandre-dos-reis** [comment]
My perfect world would be : 

```tsx
  .post(
    "/cars/:id",
    async ({ body, params, error }) => {

      if (error.hasError()) {

        const errors = error.getErrors();

        return <FormWithError errors={errors} />;
      }

      // update car models

      return <CarsList />;
    },
    {
      body: t.Object({
        name: t.String({
          minLength: 3,
        }),
        licence: t.String({
          minLength: 3,
        }),
        status: t.Enum(Status),
      }),
    },
  )

```

**Comment by SaltyAom** [comment]
You should be able to use [Error.all](https://elysiajs.com/patterns/error-handling.html#catching-all-error) to list all of the errors to the client.

You may want to format the error message a little bit but that's all it takes.

Feels free to reopen the issue if the problem still persists.
