### ISSUE TITLE
Question: Are they any Middleware like express with a next() callback ?

### ISSUE THREAD

**Issue by gungun974** [elysiajs/elysia#109]
I have used express for a long time and one important thing in express for me are middleware.

Middleware are easy to use and just required a callback that will call the next middleware (util it reach the router).

I try to understand how plugin and onRequest hook works but I didn't manage how I can recreate that behavior.

Is it possible to create middleware with a "next()" callback or if that is not possible. How can I create a middleware that call a promise ?

**Comment by SaltyAom** [comment]
There's no next() in Elysia, we rely on async-await.
Besides `onRequest`, you can just use async-await to handle promises.

**Comment by gungun974** [comment]
Well...

Actually, to explain my problem, I'm trying to find a simple way for me to create a sort of global store that allows me to store the context of a route. This way, later in my presentation code, I can bypass the need to pass variables like which route my API was hit on. (This is totally inspire from Laravel `Auth::user()`)

So, NodeJS (and therefore Bun) has the `AsyncLocalStorage` from `node:async_hooks`. 
The problem with this solution is that I need to do this to contextualize the execution thread with a dedicated store.

```ts
asyncLocalStorage.run(new Map(), () => {
    next();
});
```

So the issue here is that with a promise, I can at best return a value in `onRequest.` 
So I'm afraid that for this, I will have to create some kind of wrapper on each of my routes to inject the context.

If by chance you have a more elegant solution than wrapping all the "**get**" 
I'm all opens ^^.

**Comment by SaltyAom** [comment]
How about [derive](https://elysiajs.com/concept/derive.html#derive)

**Comment by gungun974** [comment]
So the idea is there except that the problem is that here we only touch the context of the Elysia query and not physically launch, as explained here, an "independent storage context" which persists the same context for any following asynchronous calls.

https://nodejs.org/api/async_context.html

So obviously afterwards I could pass the context object to each function up to my presentation layer but the basic idea was to avoid mixing the profession with this kind of thing

If you are curious what a minimal implementation with Elysia, here my demo ^^
```ts
import { Elysia, t } from "elysia";

import { AsyncLocalStorage } from "node:async_hooks";

export const asyncLocalStorage = new AsyncLocalStorage<Map<string, any>>();

const app = new Elysia()
  .get(
    "/",
    async ({ query }) => {
      console.log(query.name);

      return asyncLocalStorage.run(new Map(), async () => {
        const store = asyncLocalStorage.getStore();

        if (!store) {
          return "error";
        }

        store.set("name", query.name);

        return await test();
      });
    },
    {
      query: t.Object({
        name: t.String(),
      }),
    },
  )
  .listen(3008);

async function test() {
  await new Promise((f) => setTimeout(f, 1000));

  const store = asyncLocalStorage.getStore();

  if (!store) {
    return "error";
  }

  const name = store.get("name");

  return name;
}

console.log(
  `🦊 Elysia is running at ${app.server?.hostname}:${app.server?.port}`,
);
```

You can try to send `curl 'http://localhost:3008/?name=A'` and  `curl 'http://localhost:3008/?name=B'` with some delay between and see the response is not mix

**Comment by hiep1998vnhn11** [comment]
Hi, this is my solution:
`app.get('/me', this.me.bind(this), {
      beforeHandle: async ({ jwt, set, request }) => {
        const token = request.headers.get('authorization')?.split(' ')[1]
        const user = token ? await jwt.verify(token) : null
        if (!user) {
          set.status = 401
          return 'Unauthorized'
        }
        request.user = user
      },
    })`

**Comment by gungun974** [comment]
> Hi, this is my solution:
> 
> ```js
> app.get('/me', this.me.bind(this), {
>       beforeHandle: async ({ jwt, set, request }) => {
>         const token = request.headers.get('authorization')?.split(' ')[1]
>         const user = token ? await jwt.verify(token) : null
>         if (!user) {
>           set.status = 401
>           return 'Unauthorized'
>         }
>         request.user = user
>       },
>     })
> ```

I don't think that solves my bottom problem to create an AsyncLocalStorage, however I'm curious to know what `this.me.bind(this)` is in your code.

**Comment by gungun974** [comment]
> Well...
> 
> Actually, to explain my problem, I'm trying to find a simple way for me to create a sort of global store that allows me to store the context of a route. This way, later in my presentation code, I can bypass the need to pass variables like which route my API was hit on. (This is totally inspire from Laravel `Auth::user()`)
> 
> So, NodeJS (and therefore Bun) has the `AsyncLocalStorage` from `node:async_hooks`. The problem with this solution is that I need to do this to contextualize the execution thread with a dedicated store.
> 
> ```ts
> asyncLocalStorage.run(new Map(), () => {
>     next();
> });
> ```
> 
> So the issue here is that with a promise, I can at best return a value in `onRequest.` So I'm afraid that for this, I will have to create some kind of wrapper on each of my routes to inject the context.
> 
> If by chance you have a more elegant solution than wrapping all the "**get**" I'm all opens ^^.

Well I re read the Node documentation about `AsyncLocalStorage` and I miss I can create an `AsyncLocalStorage` with `asyncLocalStorage.enterWith(store)`
https://nodejs.org/api/async_context.html#asynclocalstorageenterwithstore

It's technically experimental and do some strange behavior compare to normal `asyncLocalStorage.run` but I tested and with `onRequest` I can create my  context and share everywhere after.

So my strange technical need have been solve.

**Comment by wenerme** [comment]
like this https://github.com/elysiajs/elysia/issues/315 , create a small pr for override fetch
