### ISSUE TITLE
Allow custom errors to not have to extend the Error class

### ISSUE THREAD

**Issue by ethanniser** [elysiajs/elysia#111]
I love the ability to add custom errors and handle them with typesafety, but would also like to be able to do this for types that don't necessarily extend the error class, as its not really useful for that much. This is a common pattern in Effect-ts, [for example](https://effect.website/docs/error-management/expected-errors#error-tracking).

```ts
class FooError {
  readonly _tag = "FooError"
}
 
class BarError {
  readonly _tag = "BarError"
}
```

Is this restriction in place for a specific reason? If so not a huge deal

Otherwise im happy to work on the pr if needed

**Comment by ethanniser** [comment]
just was reading through a unrelated programming discord and saw this

> Usually extending Error is the only time I really use classes because Error has a bunch of platform specific implementation for capturing stack traces and the like.

If this is the reason, then totally makes sense just was curious

**Comment by SaltyAom** [comment]
Yes, you can use custom error without extending Error class but you have to provide `name`, and `message` property for identifying error, formatting, and logging like this:
<img width="1920" alt="Screenshot 2566-09-10 at 12 23 00" src="https://github.com/elysiajs/elysia/assets/35027979/2ddc1248-8f6b-47c2-ae92-1b7ffc7827af">

```ts
import { Elysia } from 'elysia'

class FooError {
	readonly _tag = "FooError"

	name: string = ''
	message: string = ''
}

const app = new Elysia()
	.addError({
		FOO_ERROR: FooError
	})
	.get('/', () => {
		throw new FooError()
	})
	.onError(({ error, code }) => {
		switch(code) {
			case "FOO_ERROR":
				console.log(error)
		}
	})
	.listen(3000)
```

**Comment by Farnsi** [comment]
Does not work.
What is  `.addError`?

**Comment by kravetsone** [comment]
> Does not work. What is `.addError`?

@Farnsi 
Old api
Use `error({})` instead
