### ISSUE TITLE
Similar methods like Express res.write() res.end()

### ISSUE THREAD

**Issue by JawadAhbab** [elysiajs/elysia#114]
I am using `new EventSource(url)` in client side.

In express I use something like this to send events -
```ts
app.get('/', (req, res) => {
  res.write('one')
  res.write('two')
  res.write('three')
  res.end()
})
```

Is there any similar approach in elysia?

**Comment by SaltyAom** [comment]
We will implement Server Sent Event after 0.7 is published #103
