### ISSUE TITLE
How to implement PubSub WebSockets using Elysia?

### ISSUE THREAD

**Issue by ocodista** [elysiajs/elysia#115]
On the Bun documentation there is a section for Pub/Sub Websockets, but Elysia doesn't.

**Comment by SaltyAom** [comment]
Elysia use Bun WebSocket under the hood, so it's the same syntax.

**Comment by SaltyAom** [comment]
See #24

**Comment by jgb-solutions** [comment]
And how would you subscribe to a certain topic using Eden Treaty for example? I think we need more docs on this.

**Comment by jgb-solutions** [comment]
How would the client know about the available topics? Say you are building a chat app with chat rooms. They rooms will be created by the users/clients. So there should be a way to subscribe to those on the client, and the server should receive them dynamically. Using Eden Treaty for example, how would I do this?

**Comment by kravetsone** [comment]
> How would the client know about the available topics? Say you are building a chat app with chat rooms. They rooms will be created by the users/clients. So there should be a way to subscribe to those on the client, and the server should receive them dynamically. Using Eden Treaty for example, how would I do this? 

It js just websockets.
U subscribe and publish to topic on server-side
Client didn't know about yours topics
Please refer to Bun websocket documentation

**Comment by jgb-solutions** [comment]
That's not I used to do it with Socket.IO  or Phoenix (Elixir). But it's Bun so I get it's different. Thanks for replying @kravetsone!
