### ISSUE TITLE
Bun with Elysia SIGHUP when reading file

### ISSUE THREAD

**Issue by xzones2014** [elysiajs/elysia#118]
.get("/file", () => Bun.file("./src/halo.json"))

then open that path on the browser
immediately exit 
error: script "dev" exited with code 1 (SIGHUP)

how to do simple bun reading file

**Comment by enesflow** [comment]
seems to be an issue with bun https://github.com/oven-sh/bun/issues/5960

**Comment by SaltyAom** [comment]
Closing as the issue seems to be on Bun not Elysia.
