### ISSUE TITLE
html plugin with jsx gives error "Cannot call a class constructor without |new|"

### ISSUE THREAD

**Issue by GGAlanSmithee** [elysiajs/elysia#119]
Simply switching out `"jsxFactory": "elements.createElement",` to `"jsxFactory": " ElysiaJSX",`, and updating imports accordingly gives the error

> Cannot call a class constructor without |new|

Returning a simple component from a route works, but anything more sophisticated, such as nested components yields the error. I haven't been able to fully determine under what circumstances this happens, but one thing that triggers this 100% of the time is conditional rendering, such as:

```tsx
const A = () => (
  <div>A</div>
)

const B = ({ content = null }) => (
  <div>{content}</div>
)

const C = () => (
  <div>
    <B />
    <B content={<A />} />
  </div>
)
```

**Comment by ArcherHume** [comment]
Can you provide a complete reproduction? I can't seem to cause the bug in testing :)
> **My Test**
```tsx
describe("JSX", () => {
  it("nested rendering", async () => {
    const A = () => <div>A</div>;

    const B = ({ content }: { content?: JSX.Element | null }) => (
      <div>{content}</div>
    );

    const C = () => (
      <div>
        <B />
        <B content={true ? <A /> : <span>test</span>} />
      </div>
    );

    const app = new Elysia().use(html()).get("/", () => C);

    const res = await app.handle(req("/"));
    expect(await res).toBe(C());
  });
});

```

**Comment by GGAlanSmithee** [comment]
here is a repro with your code, but served on localhost: https://github.com/GGAlanSmithee/elysia-jsx-repro/blob/master/index.tsx

The weird thing now is that it seems to regress even more, as to where i can't even run the server and get a response:

![image](https://github.com/elysiajs/elysia/assets/11805103/5870f9f1-7e53-42f3-b7e7-32f7c43b630d)

**Comment by GGAlanSmithee** [comment]
@ArcherHume not sure what I did, but it's working now. Thanks for your help.
