### ISSUE TITLE
Cannot use PrismaClient in .decorate() or .state()

### ISSUE THREAD

**Issue by Fumaz** [elysiajs/elysia#121]
As the title says, you cannot use a PrismaClient object in .decorate() or .state(), it will throw the following error:
![image](https://github.com/elysiajs/elysia/assets/45318608/fe12b24a-8508-42b0-968e-5dd731a670f1)

**Comment by SaltyAom** [comment]
Should be fixed with this https://github.com/elysiajs/elysia/commit/93b34cb680af2be6feccf3a41160495745ded72a, available on 0.6.23
