### ISSUE TITLE
Set response headers for static files on staticPlugin

### ISSUE THREAD

**Issue by Rennasccenth** [elysiajs/elysia#122]
Any chance to add this extension behaviour by **default**?

For what I saw, the plugin generates **routes** to the given files on the provided assets path (by default it uses _/public_).
Those generated routes aren't extensible from the plugin standpoint (I do not find anything on docs about it), so I was wondering if there are some way to extend the response of those routes, providing a cache header for example (we are talking about static assets that aren't supposed to change frequently, I hope)

**Comment by SaltyAom** [comment]
You can use `headers` to set custom headers for file: https://elysiajs.com/plugins/static.html#headers
```ts
import { Elysia } from 'elysia'
import { staticPlugin } from '@elysiajs/static'

const app = new Elysia()
    .use(
        staticPlugin({
            headers: {
                'x-aliased': 'true'
            }
        })
    )
    .listen(3000)
```
