### ISSUE TITLE
TypeSafety Only Works When Chaining

### ISSUE THREAD

**Issue by simonbindefeld** [elysiajs/elysia#123]
Typesafety only seems to work properly when chaining methods directly on the Elysia class object at instantiation time.
For example, on the left typesafety works and the correct types are provided, but, on the right, when there is no chaining, the correct types aren't generated on the routes. Wondering if anyone has come across this issue as well.

![image](https://github.com/elysiajs/elysia/assets/93556188/b630bba5-1876-45c3-a8c7-c64ba9162309)

**Comment by MystPi** [comment]
This isn't really an issue. It is documented here: https://elysiajs.com/patterns/method-chaining.html
