### ISSUE TITLE
Support swagger empty response

### ISSUE THREAD

**Issue by naturalethic** [elysiajs/elysia#124]
A request may like to return no response, such as a 204.  Swagger does not understand a Void or Undefined response, instead it should simply be absent in the response type.  Perhaps generate no response type in the swagger if t.Void() is provided in the response hook.

```
response: {
    204: t.Void(),
}
```

**Comment by LeandroPereiraDaCruz** [comment]
@naturalethic
I created the pull request above to fix this issue in [`elysia swagger repository`](https://github.com/elysiajs/elysia-swagger).

**Comment by SaltyAom** [comment]
Close with [37b9ddf](https://github.com/elysiajs/elysia-swagger/commit/37b9ddf6d1451f21fbca909605b9138df2b68693)
