### ISSUE TITLE
[Feature Request]: Accept "JsonString" custom type

### ISSUE THREAD

**Issue by brunoeduardodev** [elysiajs/elysia#131]
It's common, while working with multipart/form-data requests to send fields with encoded json, and currently, parsing these fields is a pain since you'll need to treat them as strings and on the handler itself you'll need to do the validation.

See: https://discord.com/channels/1044804142461362206/1044807567022493766/1151065279166689310

Current Example:

```ts
const app = new Elysia()
    .post("/create-user", () => {}, {
         picture: t.File(),
         name: t.String(),
         // It's an object, but unfortunately we need to treat them as strings and parse it inside the handler
         address: t.String() 
     })
```

Suggested API:
```ts
const app = new Elysia()
    .post("/create-user", () => {}, {
         picture: t.File(),
         name: t.String(),
         address: t.JsonString(
            t.Object({
                country: t.String(),
                address1: t.String()
            })
         ) 
     })
```

**Comment by brunoeduardodev** [comment]
RFC for error handling:

<img width="392" alt="image" src="https://github.com/elysiajs/elysia/assets/50559336/b8d474d6-40d1-468a-8ffa-6aa004863d65">
<img width="392" alt="image" src="https://github.com/elysiajs/elysia/assets/50559336/720ca52d-c79c-41f1-ade4-7da06c38cbd7">

**Comment by SaltyAom** [comment]
Fix with [introduction of ObjectString](https://elysiajs.com/blog/elysia-07.html#new-type)
