### ISSUE TITLE
git tag + GitHub Release?

### ISSUE THREAD

**Issue by dtinth** [elysiajs/elysia#137]
For a moment, I was confused which version is the latest, because when I look at the GitHub repo, it still shows 0.5 as latest release:

<img width="325" alt="image" src="https://github.com/elysiajs/elysia/assets/193136/d3779bf8-1e06-451e-8a15-d2c330af91e4">

…also no v0.6.0 tag in GitHub:

<img width="298" alt="image" src="https://github.com/elysiajs/elysia/assets/193136/b1acaec2-233d-4c9a-9c8e-f013fb0c8b30">

**Comment by SaltyAom** [comment]
Implemented by 3fe48f0, closing as completed
