### ISSUE TITLE
EdenTreaty seems to work only with chained calls

### ISSUE THREAD

**Issue by aureliendepeyrelongue** [elysiajs/elysia#147]
Hello, thank you for your work !

I really like the eden treaty feature but i found something strange.
When we are not directly chaining Elysia handlers mapping, errors seem to occur with the eden treaty configuration. As if the type inference did not work properly.
Maybe i am missing something ! 
 
Thanks for your work.

<img width="1472" alt="Capture d’écran 2023-09-14 à 11 59 05" src="https://github.com/elysiajs/elysia/assets/29201705/b1b57b95-4e16-4f26-a120-134d6b650398">

<img width="1532" alt="Capture d’écran 2023-09-14 à 11 59 38" src="https://github.com/elysiajs/elysia/assets/29201705/884bad38-8041-4ce7-8e54-8f7c83be8234">

<img width="550" alt="Capture d’écran 2023-09-14 à 12 00 04" src="https://github.com/elysiajs/elysia/assets/29201705/43125e84-0dfb-4bb1-9772-0c2aff67fb50">

**Comment by aureliendepeyrelongue** [comment]
Thank you @JoeHillyard for your answer, you are right, and yes it works well with plugins !

**Comment by SaltyAom** [comment]
Since the issue seems to have been solved, and there is no further communication, I'm closing the issue.

Feels free to reopen this issue if the problem stills persists.
