### ISSUE TITLE
AOT flag is misdescribed in types

### ISSUE THREAD

**Issue by HKGx** [elysiajs/elysia#161]
https://github.com/elysiajs/elysia/blob/741ffe7659cf049c8627d30b91cd1f05cfbab53e/src/types.ts#L510-L517

Currently, there are no checks for whether you're in the cloudflare envinronemnt.
And also: `(false if not Cloudflare worker)`, it is false when you're IN the cloudflare worker

**Comment by SaltyAom** [comment]
Fixed the JSDoc to `false`, as I couldn't find a reliable way to detect Cloudflare Worker environment.

Feels free to make a PR to improve on this.
