### ISSUE TITLE
Socket.io integration

### ISSUE THREAD

**Issue by arsaizdihar** [elysiajs/elysia#162]
Currently, bun support socket.io https://github.com/oven-sh/bun/discussions/2111

I would love to see at least the documentation about how to integrate socket.io with Elysia (or even better the plugin)

**Comment by alevel7** [comment]
have you checked this out https://elysiajs.com/patterns/websocket.html

**Comment by SaltyAom** [comment]
Closing with [WebSocket](https://elysiajs.com/patterns/websocket.html) and [Eden WS](https://elysiajs.com/plugins/eden/treaty.html#websocket)

**Comment by gurachan** [comment]
> Currently, bun support socket.io [oven-sh/bun#2111](https://github.com/oven-sh/bun/discussions/2111)
> 
> I would love to see at least the documentation about how to integrate socket.io with Elysia (or even better the plugin)

Same like  ```io.attachApp(elysiaApp)```
the only reason is so the server http/https will be handle by elysia and socket.io can still do its thing.. also socket.io uses ws by default.. means it uses uwebsocket too if u run it on bun.. 

for now im using two ports one for server(elysia) one for ws(socket.io) I dont like reinventing the wheel theres some stuff in socket.io that i have to code it my self if i move on other ws xD i mean both of them will use the uwebsocket in bun anyway.

**Comment by Wafje** [comment]
> > Currently, bun support socket.io [oven-sh/bun#2111](https://github.com/oven-sh/bun/discussions/2111)
> > I would love to see at least the documentation about how to integrate socket.io with Elysia (or even better the plugin)
> 
> Same like `io.attachApp(elysiaApp)` the only reason is so the server http/https will be handle by elysia and socket.io can still do its thing.. also socket.io uses ws by default.. means it uses uwebsocket too if u run it on bun..
> 
> for now im using two ports one for server(elysia) one for ws(socket.io) I dont like reinventing the wheel theres some stuff in socket.io that i have to code it my self if i move on other ws integration xD i mean both of them will use the uwebsocket in bun anyway.

Hi @gurachan,
How did you set this up? Can you share some code snippets?
I can't seem to be able to connect to my app (with socket.io).

FYI: Requiring Socket.IO for acknowledgement functionality.
