### ISSUE TITLE
securityHandlers?

### ISSUE THREAD

**Issue by mattiaferrari02** [elysiajs/elysia#164]
Is there anything that works in a similar way as [express openapi](https://www.npmjs.com/package/express-openapi) security handlers?

I need a solution to apply some kind of granular security

**Comment by SaltyAom** [comment]
You can add custom OpenAPI property using `detail` as the following:
```ts
new Elysia().get('/', () => {}, {
	detail: {
		security: [
			{
				Bearer: ['bearer']
			}
		]
	}
})
```
