### ISSUE TITLE
State modifies the object

### ISSUE THREAD

**Issue by nikhilro** [elysiajs/elysia#169]
Hey, I'm trying to use `state` to pass a db connection to the requests. I'm using node-postgres's Pool as my db connection. When I use the object in the request, it's not the same object. 

Here's an example:
```db.ts
export const db = new Pool({/*config*/});
```

```dbPlugin.ts
export const addDb = new Elysia({ name: "db" }).state("db", db);
```

```test.ts
import { addDb } from "./dbPlugins";
import { db as dbImport } from "../db";

export const test = new Elysia({ name: "parseOrgId" })
  .use(addDb)
  .use(bearer())
  .derive(async ({ bearer, store: { db } }) => {
    console.log("db", db);
    console.log("db import", dbImport);
    console.log("db", db.query); // undefined
    console.log("db import", dbImport.query); // actual function
  });
  .get("/", () => "OK")
  .listen(3000);
```

If you look at the console values, it seems functions get stripped off. Would appreciate any help!

**Comment by SaltyAom** [comment]
Should be fixed in >= 0.7.10

Feels free to reopen the issue if the problem still persists.
