### ISSUE TITLE
 Adding Email and Date Validation Behaviors to Typebox FormatRegistry

### ISSUE THREAD

**Issue by yanmifeakeju** [elysiajs/elysia#170]
Typebox does not out-of-the-box validate values like email and date input fields. However, I came across a potential solution on the Typebox GitHub repository (issue: https://github.com/sinclairzx81/typebox/issues/598), which suggests accessing the underlying Typebox and modifying the FormatRegistry to handle these validation behaviours.

Is there a way to access the underlying Typebox and add some of these behaviours via the FormatRegistry?

**Comment by SaltyAom** [comment]
Elysia already provides text formats like email and date input by default.
See https://github.com/elysiajs/elysia/blob/4d740866da5dac28e53ec0926717db28e1ee2e77/src/custom-types.ts#L9

**Comment by yanmifeakeju** [comment]
That's noted, but it doesn't work when I try to send a wrong value  I get:

`ValueCreate.String: String types with formats must specify a default value`

I think this has to do with Typebox's behavior itself.

**Comment by fateslayer** [comment]
@yanmifeakeju try adding the default field. I don't know if this is the right way but it works for now:
```
email: t.String({
	default: "",
	format: "email"
})
```
