### ISSUE TITLE
Way to get response in `onAfterHandle` to perform response transform

### ISSUE THREAD

**Issue by masnormen** [elysiajs/elysia#171]
Hi, I'm currently seeking way to transform response from a handler and/or on the global `ElysiaApp`.

```ts
{
  code: number,
  data: T, // <= T is the returned data from main handler
  status: boolean,
  message: "OK" | "ERROR"
}
```

I want all of my API's response shape to be uniform like above. But I don't necessarily want to `return { code: xx, data: xx, ....... }` on every handler.

Naturally I tried using `onAfterHandle`, but looks like it doesn't support getting response from the main handler. Sure there's a `set` object but it only allows setting headers.

This would also allow something like "Prety JSON Middleware" in Hono.js (https://hono.dev/middleware/builtin/pretty-json), which transforms the output into pretty JSON.

Is there a way to achieve this? Thank you.

**Comment by bogeychan** [comment]
Hi 👋

you could do something like this:

```ts
import { Elysia } from 'elysia';

type MyResponse<T = unknown> = {
  code: number;
  data: T;
  status: boolean;
  message: 'OK' | 'ERROR';
};

new Elysia()
  .onError((ctx) => {
    return {
      code: ctx.set.status ?? 500,
      data: ctx.error.message,
      status: false,
      message: 'ERROR'
    } satisfies MyResponse;
  })
  .onAfterHandle((ctx, response) => {
    return Response.json(
      {
        code: ctx.set.status ?? 200,
        data: response,
        status: true,
        message: 'OK'
      } satisfies MyResponse,
      ctx.set
    );
  })
  .get('/', () => {
    return {
      my: 'json'
    };
  })
  .get('/throw', () => {
    throw new Error('something went wrong!');
  })
  .listen(3000);
```

You have to wrap the response in `Response.json` until https://github.com/elysiajs/elysia/pull/167 is merged.

- http://localhost:3000
  ```json
  {
      "code": 200,
      "data": {
          "my": "json"
      },
      "status": true,
      "message": "OK"
  }
  ```
- http://localhost:3000/throw
  ```json
  {
      "code": 500,
      "data": "something went wrong!",
      "status": false,
      "message": "ERROR"
  }
  ```

**Comment by masnormen** [comment]
Hi, thank you! Awesome. I didn't realize there's a second argument you can use in `Handler` 😅

I've read the docs a dozen times and looks like the `response` argument is not documented enough... I appreciate the amazing works of the maintainers though

However when I ran this code, I got an error because the schema I defined in `response.200` doesn't match the type returned by onAfterHandle's transform. 

```ts
new Elysia()
  .onAfterHandle((ctx, response) => {
    return Response.json(
      {
        code: ctx.set.status ?? 200,
        data: response,
        status: true,
        message: 'OK'
      } satisfies MyResponse,
      ctx.set
    );
  })
  .get('/', () => {
    return {
      name: 'json'
    };
  }, {
    response: {
      200: nameSchema
    }
  })
  .listen(3000);
```

```
Invalid response, 'name': Expected string

Expected: {
  "name": ""
}

Found: {}
```

when I remove the response property in the hook, I got the wanted result:

```
{"code":200,"data":{"name":"json"},"status":true,"message":"OK"}
```

If I read [the docs](https://elysiajs.com/concept/life-cycle.html#:~:text=After%20Handle%3A%20map%20returned%20value%20into%20a%20proper%20response) correctly, Validation on Response must've happened right before After Handle, not after it. Is there something I'm missing or is this a bug?

**Comment by adarshaacharya** [comment]
I've written blog on this you can check this out ! 

https://www.adarsha.dev/blog/elysia-uniform-response

**Comment by adarshaacharya** [comment]
> Hi, thank you! Awesome. I didn't realize there's a second argument you can use in `Handler` 😅
> 
> I've read the docs a dozen times and looks like the `response` argument is not documented enough... I appreciate the amazing works of the maintainers though
> 
> However when I ran this code, I got an error because the schema I defined in `response.200` doesn't match the type returned by onAfterHandle's transform.
> 
> ```ts
> new Elysia()
>   .onAfterHandle((ctx, response) => {
>     return Response.json(
>       {
>         code: ctx.set.status ?? 200,
>         data: response,
>         status: true,
>         message: 'OK'
>       } satisfies MyResponse,
>       ctx.set
>     );
>   })
>   .get('/', () => {
>     return {
>       name: 'json'
>     };
>   }, {
>     response: {
>       200: nameSchema
>     }
>   })
>   .listen(3000);
> ```
> 
> ```
> Invalid response, 'name': Expected string
> 
> Expected: {
>   "name": ""
> }
> 
> Found: {}
> ```
> 
> when I remove the response property in the hook, I got the wanted result:
> 
> ```
> {"code":200,"data":{"name":"json"},"status":true,"message":"OK"}
> ```
> 
> If I read [the docs](https://elysiajs.com/concept/life-cycle.html#:~:text=After%20Handle%3A%20map%20returned%20value%20into%20a%20proper%20response) correctly, Validation on Response must've happened right before After Handle, not after it. Is there something I'm missing or is this a bug?

did you found any solution for this, facing same issue

**Comment by masnormen** [comment]
@adarshaacharya Nah. I ended up wrapping every endpoint's response manually with a helper function.

So `return ok(data)` becomes `{ code: 200, data: data, ... }`

I don't know if this issue still applies to the new Elysia versions though, as I haven't worked with the code again.

**Comment by adarshaacharya** [comment]
@masnormen i think that means we have to wrap every response schema with helper function as well.

I'm trying with latest version and facing same issue, guess we have to wrap every response + response schema with the utility functions :)
