### ISSUE TITLE
Property 'get' does not exist on type Elysia

### ISSUE THREAD

**Issue by mostafa-kheibary** [elysiajs/elysia#172]
I have multipal type error in ```node_modules/elysia/dist/index.d.ts```
after i fix the type errors in ```node_modules/elysia/dist/index.d.ts``` there it was fixed
- all the errors are kind of like this
```const Errors extends  ....```
the typescript complain about the ```const```, and if you remove it it will be fixed

im running bun1.0.1 on ubuntu 22.04
and create the app with ```bun create elysia hi-elysia```

**Comment by HKGx** [comment]
Consider upgrading your typescript version. Const modifier in generics is a standard TypeScript 5.0 syntax.

**Comment by mostafa-kheibary** [comment]
thanks @HKGx

**Comment by mostafa-kheibary** [comment]
thanks @HKGx
