### ISSUE TITLE
How to create secure websocket?

### ISSUE THREAD

**Issue by wtong2017** [elysiajs/elysia#173]
Hi, I want to create a secure websocket connection. I have tried the below code but failed.

```
const app = new Elysia({
  serve: {
    // can be string, BunFile, TypedArray, Buffer, or array thereof
    key: Bun.file("./certs/key.pem"),
    cert: Bun.file("./certs/cert.pem"),
  },
})
  .use(ws())
  .use(cors())
 .ws("/ws", ...
```

I cannot connect to the server, and the client produces this error `websocket connection to 'wss://...' failed`

I couldn't find any tutorials or solutions related to this issue. Is there something I may be overlooking?

**Comment by fruity4pie** [comment]
try https://developer.mozilla.org/en-US/docs/Web/API/WebSocket it will work. 

not sure how to solve this in ws lib :)

**Comment by FedFer98123** [comment]
It looks like you wrote the server object wrong, key and cert are supposed to be inside a "tls" object.
I tried it and had no problems.
[https://bun.sh/docs/api/http#tls](https://bun.sh/docs/api/http#tls)
