### ISSUE TITLE
TypeError: Expected 'this' to be instanceof ServerWebSocket

### ISSUE THREAD

**Issue by wS2Zth** [elysiajs/elysia#174]
Hi there. I am not sure but it seems like bug.

`
app.use(ws()).ws("/ws", {
  open(ws) {
    ws.isSubscribed("chat");
  }
});
`

When the isSubscribed function is used, "TypeError: Expected 'this' to be instanceof ServerWebSocket" error is thrown.
It does not matter whether you use it in "Open" or "Message" functions.

**Comment by bogeychan** [comment]
Hi 👋

thank you for your feedback. This is a known bug that will be fixed in version 0.7 -> https://github.com/elysiajs/elysia/pull/103.

As a workaround you can do this:

```ts
ws.isSubscribed.bind(ws.raw)("chat")
```

**Comment by wS2Zth** [comment]
Thanks for response.
