### ISSUE TITLE
How to serialize/deserialize the response?

### ISSUE THREAD

**Issue by zolboo-gtn** [elysiajs/elysia#175]
Is there a way to serialize the server response and deserialize it on the client side?
If you send a `Date` type to the client, it will automatically converted to `string`. Because of that `edenTreaty ` says it has `Date` type, but what you will actually get is a string.

It would be nice if elysiajs allowed for data transformers like trpc.
https://trpc.io/docs/server/data-transformers

Example:
on the server
```
export const app = new Elysia()
    .use(transformer(superjson))
```
on the client
```
export const app = edenTreaty<App>({
  transformer: superjson,
});
 ```

**Comment by SaltyAom** [comment]
To deserialize a response, you can either use `transform` or `t.Transform`.
For serialize, you can use `afterHandle`

See https://elysiajs.com/concept/life-cycle.html

**Comment by zolboo-gtn** [comment]
@SaltyAom 
Thank you for your response. 
With afterHandle i can transform the response only if `response` schema is not set.
For serialize i couldn't find anything about `transform` in the docs. With `t.Transform` it is possible but if i'm correct it should be written for every non-serializable fields.

**Comment by SaltyAom** [comment]
Closing with [Eden transform](https://github.com/elysiajs/eden/issues?q=is%3Aissue+is%3Aclosed), and Elysia `afterhandle` and `t.Decode`.

Feels free to reopen the issue if the answer is not clear.
