### ISSUE TITLE
Possibility to export the final App type (but as a File)

### ISSUE THREAD

**Issue by garder500** [elysiajs/elysia#189]
It would be cool to export the final App as .d.ts file,  to use it within Eden, because i don't want to host my API and my Client on the same thing (i want to host them on different container)

Hope you understand what i mean

**Comment by garder500** [comment]
> Sounds like a script that should copy type from app.ts and move to your client app

Yes it's that's, but within an Elysia CLI, so it make it easy ^^

**Comment by Fecony** [comment]
> Yes it's that's, but within an Elysia CLI, so it make it easy ^^

But Elysia CLI isn't even referenced in docs :( 
And it would make sense to move issue there instead

**Comment by garder500** [comment]
> > Yes it's that's, but within an Elysia CLI, so it make it easy ^^
> 
> But Elysia CLI isn't even referenced in docs :( And it would make sense to move issue there instead

but Elysia doesn't have CLI no ?

**Comment by Fecony** [comment]
> > > Yes it's that's, but within an Elysia CLI, so it make it easy ^^
> > 
> > 
> > But Elysia CLI isn't even referenced in docs :( And it would make sense to move issue there instead
> 
> but Elysia doesn't have CLI no ?

There "is", @SaltyAom did tell about it on twitter but it's not in docs, doesn't have many commands and so on
https://github.com/elysiajs/elf

**Comment by SaltyAom** [comment]
You can use TypeScript CLI to generate `.d.ts` file.

Just make sure to have `export type App = typeof app` at the end of the file, then everything would just works.
