### ISSUE TITLE
bump typebox (and consider to not reexport)

### ISSUE THREAD

**Issue by gotjoshua** [elysiajs/elysia#19]
@sinclair/typebox@0.25.23

i get some typescript errors that i suspect are due to version sync.

I understand that rexporting feels convenient, but isn't that what peer deps are for?

**Comment by SaltyAom** [comment]
I'm thinking about adding a custom type to the modified local type box dependency (t) to add support for a more server-related type like ArrayBuffer/FormData in the future. 

However, I haven't done it yet, as I'm waiting for [FormData to land on stable](https://github.com/oven-sh/bun/issues/621), after that I will see if it's better to use import typebox directly or a modified version perform better in term of DX.

So likely haven't decided yet until I then.

**Comment by SaltyAom** [comment]
Got some more approach, we can use `peerDependency` with [peerDependencyMeta.optional](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#peerdependenciesmeta).

This way we can have both pre-installed to handle type inference, and optional peerDepencency.

![image](https://user-images.githubusercontent.com/35027979/220968524-cc0b46fb-e1b3-4e1c-a12b-ea11a308b984.png)
