### ISSUE TITLE
onResponse handler neither has the response object nor the Request socket object available (TS)

### ISSUE THREAD

**Issue by otherguy** [elysiajs/elysia#190]
Unfortunately, the `onResponse` handler can neither access the actual `Response` object (to get e.g. response length) nor does it have access to the underlying socket, to get the request protocol for example.

At the least, would it be possible to get response length/size in the `set` object?

And an access to `req.socket` in the TypeScript `Request` object?

**Comment by otherguy** [comment]
@SaltyAom I renamed this since the error is now available on the `onError` handler.

**Comment by SaltyAom** [comment]
In 0.7.0, you should be able to access Response in `afterHandle` as the following.

```ts
new Elysia()
	.onAfterHandle(({ response }) => {
	})
```

Feels free to reopen the issue if the answer is not what you are looking for.

**Comment by otherguy** [comment]
@SaltyAom I don't have permission to reopen a completed issue so I opened a new one: https://github.com/elysiajs/elysia/issues/324
