### ISSUE TITLE
Structured logging?

### ISSUE THREAD

**Issue by fritzblue** [elysiajs/elysia#192]
What options are there for structured logging, log levels, etc. in elysia? Is there any integration with pino or similar? Thanks in advance.

**Comment by ethanniser** [comment]
https://github.com/tristanisham/logysia
https://github.com/bogeychan/elysia-logger (uses pino)
https://github.com/mehtaabGill/holt

**Comment by fritzblue** [comment]
@ethanniser Thank you for these links.

To the maintainers, any plans to provide first class logging as part of the framework?

**Comment by SaltyAom** [comment]
No plan to provide an official structured logging in the near future, I suggested relying on Elysia logger as Bogeychan has a solid understanding of how Elysia works.

**Comment by otherguy** [comment]
I also built [otherguy/elysia-logging](https://github.com/otherguy/elysia-logging) for fast, production-first structured logging that works with any logger, like Pino or Winston.
