### ISSUE TITLE
[Suggestion] add "http://" to Elysia's running message.

### ISSUE THREAD

**Issue by ariqRam** [elysiajs/elysia#202]
The current running message goes like : `🦊 Elysia is running at localhost:3000`.

On VS Code, this local link can't be opened by SHIFT + Click. A `http://` prefix will allow SHIFT + Click to open. 

If this is taken as a good recommendation, allow me to work on it.

**Comment by mushonnip** [comment]
#227

**Comment by kravetsone** [comment]
> The current running message goes like : `🦊 Elysia is running at localhost:3000`.
> 
> On VS Code, this local link can't be opened by SHIFT + Click. A `http://` prefix will allow SHIFT + Click to open.
> 
> If this is taken as a good recommendation, allow me to work on it.

This not Elysia issue
Please open it in [bogeychan/create-elysia](https://github.com/bogeychan/create-elysia) repo
and I recommend taking a look at [kravetsone/create-elysiajs](https://github.com/kravetsone/create-elysiajs)

**Comment by kravetsone** [comment]
This can be closed since `http` already in message

```bash
\elysia-project> bun run start
$ bun run main.ts
Listening on http://localhost:8080/
```
