### ISSUE TITLE
context.query is not preserved if not referenced directly in a handler (see video)

### ISSUE THREAD

**Issue by GGAlanSmithee** [elysiajs/elysia#203]
Originally posted on discord, but since there were no response, I am filing it as a bug report instead

[original discord post](https://discord.com/channels/1044804142461362206/1048142483864956968/threads/1154287812552708127)

If I pass context through to another function, without directly referencing it in the handler, context.query becomes undefined. I would guess this is true for other properties of context as well, but I haven't tried.

I have noticed other oddities, such as that I can't always destruct context but I cannot reproduce this reliably.

https://github.com/elysiajs/elysia/assets/11805103/8683d4ce-9de3-44b9-835e-294ca2489964

**Comment by dezoito** [comment]
I think I found a similar issue, documented below:

Passing `context` to a handler function defined elsewhere makes `query` return `undefined`:

Sample URL: http://localhost:3001/search/baser/some_term/?q=15555

```js
export const getSearch = async (context: Context) => {
  console.log("query:", context.query);
  console.log("params:", context.params);

  return "Search handler returned";
};

.get("/search/:base/:term", async (context) => await getSearch(context))
```

Console output:

```js
query: undefined
params: {
  term: "some_term",
  base: "baser"
}
```

This method (desconstructing `context`), however,  works fine:

```js
export const getSearch = async ({
  query,
  params,
}: Pick<Context, "query" | "params">) => {
  console.log("query:", query);
  console.log("params:", params);

  return "Search handler returned";
};


.get(
"/search/:base/:term",
async ({ query, params }) => await getSearch({ query, params }),
)
```

console output:

```js
query: {
  q: "15555"
}
params: {
  term: "some_term",
  base: "baser"
}
```

**Comment by GGAlanSmithee** [comment]
@dezoito 

Yeah, that does work for me too. Actually, if you need the whole `context` to be passed down,  you can just destruct / rest it, as:

```ts
.get(
"/search/:base/:term",
async ({ ...ctx }) => await getSearch(ctx),
)
```

**Comment by dezoito** [comment]
@GGAlanSmithee , to clarify, the first example omits the `query`, but the second one works, right?

**Comment by GGAlanSmithee** [comment]
@dezoito yes, exactly!

**Comment by GGAlanSmithee** [comment]
seems like this is working for me now with version `0.7.12`. Would you mind trying that as well @dezoito ?

**Comment by dezoito** [comment]
Yup, looks like the issue was solved (and at the same time they messed  up my working websockets endpoint :(

Would you (or anyone else reading this) know the commit where this was fixed? I want an excuse to learn more about the framework.

**Comment by GGAlanSmithee** [comment]
I have no idea, but by a quick glance, [the code in this commit](https://github.com/elysiajs/elysia/commit/a4f7721f49421d8fb12e00103b904333a394b620#diff-9043fd343dba2fc691e6d1577d67b4c164b7cdc2ce399d3a3cc787e06dd81c32L422-L539) looks relevant

**Comment by GGAlanSmithee** [comment]
I will close this issue now, as it's working for now

**Comment by dezoito** [comment]
Looks like something is broken again:

![image](https://github.com/elysiajs/elysia/assets/6494010/3a8e927f-953f-4a39-ae4f-1aef4571888f)

Taking a closer look at what typescript is complaining about:

```
Argument of type '{ body: unknown; query: Record<string, string | null>; params: Record<"base" | "term", string>; headers: Record<string, string | null>; cookie: Record<string, Cookie<any>>; set: { ...; }; path: string; request: Request; store: {}; }' is not assignable to parameter of type '{ body: unknown; query: Record<string, string | null>; params: never; headers: Record<string, string | null>; cookie: Record<string, Cookie<any>>; set: { ...; }; path: string; request: Request; store: {}; }'.
  Types of property 'params' are incompatible.
    **Type 'Record<"base" | "term", string>' is not assignable to type 'never'.ts(2345)**
```

Basically, the type for the params defined for that route (`Record<"base" | "term", string>`) are not compatible to `never`, which is the type defined in `Context`.

@SaltyAom , curiously, if I remove the params from the route, the TS error disappears:

![image](https://github.com/elysiajs/elysia/assets/6494010/f5ad3629-5a17-4974-8636-7d5fd65ba401)
