### ISSUE TITLE
WebSocket routes not working in plugins

### ISSUE THREAD

**Issue by FedFer98123** [elysiajs/elysia#205]
When a websocket route is defined in a plugin, it won't work correctly.
Ex.
```js
import Elysia from "elysia"

const ws = new Elysia().ws("/", {
    message(ws, message) {
        console.log(message)
    }
})

const app = new Elysia()
    .use(ws)
    .listen(4500)
```
test script
```js
const ws = new WebSocket("ws://0.0.0.0:4500/");

ws.addEventListener("error", (e)=>console.log(e))
ws.addEventListener("open", ()=>ws.send("ping"))
```
The console won't output anything but neither will the test script
Expected console output: `ping`

**Comment by SaltyAom** [comment]
Should be fixed in https://github.com/elysiajs/elysia/commit/62cd02a187abb80088c55896d390e2966ab225b4

Let me know if the problem this persists
