### ISSUE TITLE
Re-add fn method

### ISSUE THREAD

**Issue by hazelnutcloud** [elysiajs/elysia#208]
Would love to use fn in my app. I tried to look for the @elysiajs/fn repo to contribute but it seems like it got deleted ?

**Comment by SaltyAom** [comment]
We are on the way to separate Elysia Fn into a standalone server.

Please leave this open until then.

**Comment by pauldvu** [comment]
Plus one for fn feature! World love to use fn(), and contribute
The feature to jump to the function is great!

I'm assuming it works like trcp where we can rename functions? with renameSymbol?

**Comment by marbemac** [comment]
Ah ok, so is it expected that `fn` no longer exists - the docs tripped me up a bit here while trying to get started. This is on Elysia v0.7.13.

<img width="1013" alt="Screenshot 2023-09-25 at 11 20 52 AM" src="https://github.com/elysiajs/elysia/assets/847542/3c829df9-f30d-4343-9f7a-938f69130a93">
