### ISSUE TITLE
`t.Numeric()` cannot be `t.Optional()`

### ISSUE THREAD

**Issue by otus-jfortman** [elysiajs/elysia#209]
## Reproduction:
```js
const app = new Elysia()
  .post("/foo", 
  ({body: {bar}}) => { console.log(bar) }, {
    body: t.Object({ bar: t.Optional(t.Numeric()) })
  })
```

## Expected outcome(s):
When an empty object is sent, there is no error

## Observed outcome:
An error is returned
```
Invalid body, 'bar': Expected number

Expected: {}

Found: {
  "bar": null
}
```

## Note:
Switching `t.Numeric` for `t.Number` allows the `null` value. However, as expected a number-like string does not pass, and requires a transform.

**Comment by otus-jfortman** [comment]
Possibly related, somewhat interesting. If you change `post` to `get`, there is a runtime exception.

![image](https://github.com/elysiajs/elysia/assets/48094294/b4b398e7-a638-4698-ba63-bbf9b490c096)

**Comment by otus-jfortman** [comment]
Removing the `t.Optional` does not result in the correct outcome either.


```js
body: t.Object({ bar: t.Numeric() })
```
results in
```
Invalid body, 'bar': Expected number

Expected: {
  "bar": 0
}

Found: {
  "bar": null
}
```

and if I try setting a default oddly it seems to expect that default number
```
body: t.Object({ bar: t.Numeric({default: 6}) })
```
results in
```
Invalid body, 'bar': Expected number

Expected: {
  "bar": 6
}

Found: {
  "bar": null
}
```

**Comment by SaltyAom** [comment]
Should be fixed in https://github.com/elysiajs/elysia/commit/62cd02a187abb80088c55896d390e2966ab225b4

Let me know if the problem this persists

**Comment by otus-jfortman** [comment]
Thank you, this resolve it.
