### ISSUE TITLE
Issue: Events are not accumulative?

### ISSUE THREAD

**Issue by gtrabanco** [elysiajs/elysia#211]
I made a plugin to [inject html code in html files](https://github.com/gtrabanco/elysia-inject-html/).

The problem is that the plugin can not be added twice as you can see in the example:
- https://github.com/gtrabanco/elysia-inject-html/blob/1678ef554502ff35d86c1d6270103cb7687bfb5e/src/example.ts

If I delete `use(pluginTwo)` it worked but if I keep it it is not working.

You can Download the repo and run the example with:

```shell
bun example
```

I tried with `scoped: true` but there are some issues with that too: #158

**Comment by SaltyAom** [comment]
Close as unable to reproduce on the latest Elysia version.

We have a several patch to fix this issue, and no longer able to reproduce on the latest version.
