### ISSUE TITLE
Explicit response type for websockets

### ISSUE THREAD

**Issue by enesflow** [elysiajs/elysia#222]
there seems to be no way to set explicit content types with `type: ContentType`
```ts
// server.ts
const app = new Elysia()
  .ws("/ws", {
    open(ws) {
      ws.send('{"message": "Hello Elysia"}'); // Sending string, receiving 'object'
      // ws.raw.sendText('{"message": "Hello Elysia"}'); // This returns 'object' too
      // ws.raw.sendBinary(Buffer.from('{"message": "Hello Elysia"}')); // This too
    },
  response: t.String(), // <- I think json is parsed after this is checked
  type: "text", // <- There is no "type" option
})
```
```ts
// client.ts
import { App } from "./server";
const client = edenTreaty<App>("http://localhost:3000");
const sub = client.ws.subscribe();
sub.subscribe((message) => {
  console.log(message.data, typeof message.data);
  // message.data seems to be the type 'string' but:
  /*
   {
     message: "Hello Elysia"
   } object
  */
});

```

**Comment by enesflow** [comment]
My bad, the "type" parameter is only for body, not response, but still the response is being parsed no matter if I intend to or not

**Comment by SaltyAom** [comment]
This is expected behavior, can you provide your use case why would you like to return a stringified JSON instead of an actual JSON.

**Comment by enesflow** [comment]
for example when making a websocket terminal, the terminal might log some json and it should not be parsed when sending with ws

**Comment by SaltyAom** [comment]
Closing as specifying a JSON as a schema will always check as a valid json.

If this doesn't answer your question, feel free to reopen the issue. Thanks
