### ISSUE TITLE
Calling Eden fns on the server / during SSR

### ISSUE THREAD

**Issue by marbemac** [elysiajs/elysia#225]
The primary use case is for data-fetching in frontend apps during SSR.

The general idea is this:

- Assuming a react/solid/svelte/etc web app that is using a data fetching library like [@tanstack/query](https://tanstack.com/query/latest) or [swr](https://swr.vercel.app/)
- A typed "apiCaller" is provided to the app through context. The data fetching functions use this caller to interact with the API (elysia). In elysia's world, this is the Eden client. In tRPC world, this is `createTRPCProxyClient`.
- As user navigates around the web app, the eden/trpc client fns are invoked and make fetch requests as expected.
- **The new bit**. However, during SSR those same fns on the provided "apiCaller" are invoked directly (no fetch). In the tRPC case what we can do is to create a new "apiClient" on each incoming request (via create-caller, linked below), and provide that to the web app context. The resulting apiCaller has the exact same signature, it just invokes the relevant queries/procedures directly on the server rather than making fetch requests. Thus the web app does not need to know anything about these implementation details - can make calls on the provided "apiCaller" and under the hood it'll be making fetch requests in a browser context, and direct calls when on the server during SSR.

This is very powerful because now we can use a single type-safe rpc-style server E2E for both client-side interactions (fetch) and SSR (direct calls). 

tRPC solves this with their "createCaller" functionality -> https://trpc.io/docs/server/server-side-calls#create-caller.

```tsx
/**
 * SUPER simplified pseudo code...
 */

import type { edenFn, edenFnCaller } from '@elysiajs/eden'
import { Elysia } from "elysia";

import MyReactApp from './app.tsx';

export type App = typeof app

export type ApiCaller = ReturnType<typeof edenFn<App>>

export const ApiCallerCtx = React.createContext<ApiCaller>();

const app = new Elysia()
  // our fns
  .fn({
    sum: (a: number, b: number) => a + b,
  })

  // handler to render the react/solid/svelte/whatever app
  .get("/*", (c) => {
    // create a caller per request that is passed to the web app. 
    // should invoke fns directly, not through fetch calls
    const apiCaller = c.edenFnCaller();

    // or could pass in whatever relevant context is needed for eden 
    // to work if don't want to pollute route params... or some other approach
    // const apiCaller = edenFnCaller(c);

    const res = ReactDom.renderToString(
      <ApiCallerCtx.Provider value={apiCaller}>
        <MyReactApp />
      </ApiCallerCtx.Provider>
    );

    return res;
  })
```

**Comment by SaltyAom** [comment]
1. For Tanstack Query and SWR, you can pass Eden endpoint directly, see [React Query example](https://github.com/SaltyAom/elysia-monorepo-example/blob/main/apps/react/src/app/sign-in/form.tsx#L33)
2. You can provide a custom `fetcher` function.
```ts
export const client = edenTreaty<Server>('http://localhost:8080', {
    fetcher: (url, options) => customFetcher(url, options)
})
```
3. If you want to use Eden on SSR, you can use pass `Elysia.fetch` to `Eden.fetch` to directly invoke Elysia function without creating request on server.

Feels free to reopen the issue if the answer is not clear.
