### ISSUE TITLE
Benchmarking failing the official claims

### ISSUE THREAD

**Issue by codeyash** [elysiajs/elysia#229]
Your results are not matching with the posted here: https://web-frameworks-benchmark.netlify.app/result?asc=0&f=elysia&metric=totalRequestsPerS&order_by=level64

Please check it and fix at: https://github.com/the-benchmarker/website/issues/44. 

javascript (ES2019)
[elysia](https://elysiajs.com/) (0.7)
138 735
141 956
142 657

**Comment by fecony** [comment]
Don't you consider that benchmarks are running on different machines..?

**Comment by waghanza** [comment]
To make this kind of assumption @codeyash, you may refer indeed to how results are produced.

The first question I will as is :
Are the machines reliable/ close to what is used / could be used in production?

Like @fecony check it first

What makes sure differences ? What makes the official runs reliable?...

Not sure we can have a single source of trust for benchmarks, it depends on contexts ...

However, feel free to challenge anything here

**Comment by masfahru** [comment]
This is the result of the official round 22 of TechEmpower Framework Benchmark:
![image](https://github.com/elysiajs/elysia/assets/92277627/e941606d-0d7e-499e-9a94-071b76e569e6)
https://www.techempower.com/benchmarks/#section=test&runid=66d86090-b6d0-46b3-9752-5aa4913b2e33&test=plaintext&l=zieepr-33z

Elysia claims that it is 18x faster than Express, and that's true at least for a simple plain text test.

**Comment by waghanza** [comment]
Could you please point me to the source code ?

Seems that Elysia run thrown spawning, not sure is the way recommended to run in production

cc @aquapi @SaltyAom

**Comment by waghanza** [comment]
Elysia : https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/TypeScript/elysia/spawn.ts

**Comment by masfahru** [comment]
> Seems that Elysia run thrown spawning, not sure is the way recommended to run in production

Spawning Workers with `reusePort` enabled is just a way to take advantage of multi-core systems. https://github.com/TechEmpower/FrameworkBenchmarks/pull/8416#issuecomment-1739072644

**Comment by waghanza** [comment]
Hono seems to use `reusePort` https://github.com/the-benchmarker/web-frameworks/blob/master/javascript/hono/app.ts


But not Elysia

Feel free to PR
