### ISSUE TITLE
[Bug] Unexpected behaviour with t.Union and t.ObjectString

### ISSUE THREAD

**Issue by lnfel** [elysiajs/elysia#236]
I am sending nested object via FormData to Elysia endpoint and I am expecting either of the following:
```js
// a single object
{
  contact: {
    name: String,
    number: String
  },
  ...other props
}
// or an array of objects
[
  {
    contact: {
      name: String,
      number: String
    },
    ... other props
  }
  {
    contact: {
      name: String,
      number: String
    },
    ... other props
  }
]
```
This is how I send it:
```js
const formData = new FormData()
formData.append('contact', JSON.stringify(contact))
```
Elysia has a good utility `t.ObjectString` that parses JSON string passed in multipart form data and transforms it into an object. But somehow does not work with `t.Union`. To demonstrate this is how I use it:
```js
const contactSchema = t.ObjectString({
  name: t.String(),
  number: t.String()
})
const route = new Elysia()
  .post('/test', async ({ body }) => {
    console.log(body)
  }, {
    body: t.Object({
      contact: t.Union([contactSchema, t.Array(contactSchema)])
    })
  })
```
It parses it and returns a JSON string instead (i.e. `"{'name': 'some name', 'number': '6565'}"`). But if I were to use either:
- `contactSchema`
- or `t.Array(contactSchema)`
It works and returns parsed object/array of objects. Is this the expected behaviour for `t.Union` or I am doing something wrong?

For now I can use `transform` or `beforeHandle` local hook to return proper data format to route handler.

**Comment by SaltyAom** [comment]
Fixed as implementation of [type coercion](https://elysiajs.com/blog/elysia-11.html#data-type-coercion)
