### ISSUE TITLE
Support JOI as a validator

### ISSUE THREAD

**Issue by mehtaabGill** [elysiajs/elysia#238]
Any chance we could get [JOI](https://github.com/hapijs/joi) as a option for a request validator? I am fan of their syntax as well as their `transform` functionality and it would be a great addition to Elysia.

**Comment by frogconn** [comment]
We try use JOI validate in Elysia is work.
`
import { Elysia, t } from "elysia";
import Joi from 'joi'

const app = new Elysia()

app.get("/", () => "Hello Elysia")

app.post('/login', async ({ body }) => {
  const schema = Joi.object({
    idToken: Joi.string().required(),
    uid: Joi.string().required()
  })

  const validate = schema.validate(body)

  return validate.error?.details
})
`

**Comment by mehtaabGill** [comment]
This isn't ideal because you have to call the validate function manually. It would be nice to have built in support.

**Comment by SaltyAom** [comment]
See #20
