### ISSUE TITLE
What is the point of ping, pong in the webscoket object?

### ISSUE THREAD

**Issue by vrn-dev** [elysiajs/elysia#240]
We have these as part of the websocket config:

```ts
const app = new Elysia({
	websocket: {
		ping: (ctx: ServerWebSocket, data: Buffer) => {},
		pong: (ctx: ServerWebSocket, data: Buffer) => {},
		sendPings: true,
	},
})
```

What do these methods and sendPings accomplish. This is not documented.

**Comment by bogeychan** [comment]
Hi 👋 it's part of [Bun's Websocket-API](https://bun.sh/docs/api/websockets):

- [ping](https://github.com/oven-sh/bun/blob/bb9933fa7ec5eafcb8ef902c96d85a2b248a85be/packages/bun-types/bun.d.ts#L1736) → Called when a ping is sent.
- [pong](https://github.com/oven-sh/bun/blob/bb9933fa7ec5eafcb8ef902c96d85a2b248a85be/packages/bun-types/bun.d.ts#L1744) → Called when a pong is received.
- [sendPings](https://github.com/oven-sh/bun/blob/bb9933fa7ec5eafcb8ef902c96d85a2b248a85be/packages/bun-types/bun.d.ts#L1787) → Should the server automatically send and respond to pings to clients?

**Comment by vrn-dev** [comment]
> Hi 👋 it's part of [Bun's Websocket-API](https://bun.sh/docs/api/websockets):
> 
> * [ping](https://github.com/oven-sh/bun/blob/bb9933fa7ec5eafcb8ef902c96d85a2b248a85be/packages/bun-types/bun.d.ts#L1736) → Called when a ping is sent.
> * [pong](https://github.com/oven-sh/bun/blob/bb9933fa7ec5eafcb8ef902c96d85a2b248a85be/packages/bun-types/bun.d.ts#L1744) → Called when a pong is received.
> * [sendPings](https://github.com/oven-sh/bun/blob/bb9933fa7ec5eafcb8ef902c96d85a2b248a85be/packages/bun-types/bun.d.ts#L1787) → Should the server automatically send and respond to pings to clients?

Thank you for clarifying!
