### ISSUE TITLE
Question: best practices for metric-based monitoring?

### ISSUE THREAD

**Issue by Octember** [elysiajs/elysia#242]
Hello!

I'm considering using Elysia for a production project, migrating off of a next.js app. I've been continually frustrated by the next.js ecosystem and regressions, and want to try the bleeding edge of Elysia -- congrats on all your recent success.

I'd love to set-and-forget some production metrics system like datadog APM, which is supported by frameworks like [express](https://docs.datadoghq.com/integrations/express/)

Is that something you'd consider building out in Elysia? If not, any tips for hooking into application event lifecycle for an easy production monitoring setup?

Cheers.

**Comment by SaltyAom** [comment]
Ideally we are building one based on [Trace API](https://elysiajs.com/patterns/trace.html) but it isn't done yet.

**Comment by SaltyAom** [comment]
Close with introduction of [trace](https://elysiajs.com/patterns/trace.html#trace).
