### ISSUE TITLE
Parameter `default` in validation schema 

### ISSUE THREAD

**Issue by Hetch3t** [elysiajs/elysia#243]
Maybe I'm missing something, but currently for the following code:
```ts
tagsController.get('/', ({ query }) => {
		return query;
	},
	{
		query: t.Object({
			skip: t.Number({ minimum: 0, default: 0 }),
			take: t.Number({ minimum: 0, default: 10 }),
		}),
	}
);
```

I get an error if not providing `skip` and `take` in query parameters. I've tried different approach like:
```ts
	...
		query: t.Object({
			skip: t.Optional(t.Number({ minimum: 0, default: 0 })),
			take: t.Optional(t.Number({ minimum: 0, default: 10 })),
		}),
	...
```
, which doesn't throw error, but I still don't get a default value in the handler. So in both cases `default` doesn't do a thing and doesn't affect anything. Is it a bug or expected behavior? Are there any plans on supporting `default` parameter?

Expected behavior would be for the code above:
- Do not require neither `skip` nor `take` in query parameters;
- The type for `query` in handler `context` would be:
```ts
query: {
	skip: number;
	take: number;
}
```
(no optionals, since we _always_ will have number, either set explicitly or implicitly via `default`)

**Comment by pmenta** [comment]
having the same issue here

**Comment by shmarts** [comment]
Same issue

**Comment by kerolloz** [comment]
I have the same issue here as well.
> [!NOTE]  
> You should be using `Numeric` instead of Number because a query is always a string and `Numeric` provides the ability to parse strings into numbers.

**Comment by SaltyAom** [comment]
Close as implementation of [Default property](https://elysiajs.com/blog/elysia-08.html#default-property) and type [coercion](https://elysiajs.com/blog/elysia-11.html#data-type-coercion)
