### ISSUE TITLE
Request-scoped context / store

### ISSUE THREAD

**Issue by Hetch3t** [elysiajs/elysia#244]
Didn't find any mentions what's the expected / encouraged behavior should be for storing request-scoped information?

Usage example: imagine I have global `onRequest` where I decode JWT payload and get some info from DB. I want to store it somewhere for current request only (e.g. in express there were `res.locals`), so I can have, let's say, `guard` for _admin only_ access instead of manual checking in all the routes

**Comment by SaltyAom** [comment]
You may be looking for [derive](https://elysiajs.com/concept/derive.html)?

**Comment by SaltyAom** [comment]
Close as answered and not further discussion.
> You may be looking for [derive](https://elysiajs.com/concept/derive.html)?
