### ISSUE TITLE
Absolute import will cause cranky types

### ISSUE THREAD

**Issue by rin-yato** [elysiajs/elysia#245]

**Comment by SaltyAom** [comment]
Can you provide more detail? Thanks.

**Comment by rin-yato** [comment]
So the problem is specifically for Eden plugin.

For example, if in the tsConfig.json
```json
{
  "compilerOptions": {
     "baseUrl": ".",
     "paths": {
       "@/*": ["./src/*"]  
     }
  }
}
```
Any file that uses absolute import like `import { userSchema } from '@/schema/user'`.
Will cause edenTreaty to infer the return type as any.

This will cause return type to be any
```typescript
import { db, user } from '@/drizzle/db';

// ....some other code
.get('/', async () => {
  const sth = await db.select().from(user);
  return sth
})
```

Note: somehow it only cause this inside the handler that uses the absolute import any other handler works just fine.

**Comment by SaltyAom** [comment]
Assuming you are using monorepo where you set `tsconfig` to have absolute import on server.

You have to set the `tsconfig.json` on client to have the same file reference as server, so basically you have to add:
```ts
     "paths": {
       "@/*": ["../../apps/server/src/*"]  
     }
```

**Comment by rin-yato** [comment]
> Assuming you are using monorepo where you set `tsconfig` to have absolute import on server.
> 
> You have to set the `tsconfig.json` on client to have the same file reference as server, so basically you have to add:
> 
> ```ts
>      "paths": {
>        "@/*": ["../../apps/server/src/*"]  
>      }
> ```

Hey there, thanks for the answer. But wouldnt that mess up the import path for the client? since on the client it already has something similar.

```json
"paths": {
  "@/*": ["./src/"]
}
```

**Comment by youkaclub** [comment]
I had the same issue, my ugly hack is to use a different alias, @@ for server and @ for client, then add `"@@/*": ["../server/src/*"]` to client's tsconfig.
