### ISSUE TITLE
Streaming responses 

### ISSUE THREAD

**Issue by jmandel** [elysiajs/elysia#250]
Is there some mechanism to return a stream? Say I want to write a function that calls `fetch` and returns the fetch's response body, without accumulating the full body in memory?

Sorry if this is something obvious; from the docs and types.ts I'm having trouble seeing how this is covered.

**Comment by bogeychan** [comment]
Hi 👋

this should do it, see:

- [Fetch response body streaming](https://bun.sh/blog/bun-v0.8.0#fetch-response-body-streaming)
- [Bun.serve() streaming improvements](https://bun.sh/blog/bun-v0.8.0#bun-serve-streaming-improvements)

```ts
import { Elysia } from 'elysia';

const app = new Elysia()
  .get('/', () => fetch('https://github.com/elysiajs/elysia/issues/250'))
  .listen(3000);

console.log(`Listening on http://${app.server!.hostname}:${app.server!.port}`);
```

**Comment by jmandel** [comment]
Thanks so much! It might be worth including a link out to the definition of the response object in the documentation at https://elysiajs.com/concept/handler.html#response ; I did not realize this would be a standard like https://developer.mozilla.org/en-US/docs/Web/API/Response or similar.

**Comment by emilianomon** [comment]
Any tips on how to document the response?

I am using the Swagger plugin and it does not seem to exist a way to do it using Typebox.

**Comment by crishoj** [comment]
@emilianomon, you mean this? → https://elysiajs.com/patterns/creating-documentation.html#route-definitions

**Comment by emilianomon** [comment]
Since there is no way to relate the returning type of the streaming write call with the actual handler method, the question was wrongfully posed.

Is there a way to inject into the ha inject a streaming helper that actually takes de response validation type into consideration?

My end goal is to have a typeface streaming emit.

**Comment by SaltyAom** [comment]
Closing with the introduction of [Stream plugin](https://elysiajs.com/plugins/stream.html#stream-plugin).

**Comment by emilianomon** [comment]
Perfect. Just for another round of clarification, I thought of something like the following:

```typescript
const handler = new Elysia();

handler.post('/stream', ({ stream }) => {

  stream.send({
    validatedAttribute: true, // This should be validated.
  });

  return stream;
}, {
  response: {
    200: t.Object({
      validatedAttribute: t.Boolean(),
    }),
  },
});

export { handler as checkVersionAppHandler };
```

An stream helper injection that takes into consideration the response validation seems to me like a great addition!
