### ISSUE TITLE
Export `Static` Class from Typebox for Better Type Inference

### ISSUE THREAD

**Issue by henaff** [elysiajs/elysia#256]
The problem arises when attempting to use Typebox's `Static` utility type to infer the static types of schema definitions in the Elysia framework. Currently, Elysia exports the `TypeBuilder` (`t`) from Typebox, but not the `Static` type.

Attempting to manually import `Static` from Typebox results in the following TypeScript error:

```
TS2344: Type
TObject<{   name: TString;   definition: TObject<{}>; }>
does not satisfy the constraint  TSchema 
Property  [Kind]  is missing in type
TObject<{   name: TString;   definition: TObject<{}>; }>
but required in type  TSchema 
typebox.d.ts(66, 5):  [Kind]  is declared here.
```

#### The solution I would like

I would like Elysia to include the export of the `Static` type from Typebox to facilitate easier and more powerful type inference. This will improve the developer experience and make type manipulations more straightforward.

#### Code Example:

Here's a simplified code example showing what I'm trying to achieve:

```typescript
import { t } from 'elysia';
import { Static } from '@sinclair/typebox'; // <-- This should ideally be exported from Elysia

export const ChainSchemas = {
  create: t.Object({
    name: t.String(),
    definition: t.Object({}),
  }),
  get: t.Object({ id: t.String() }),
  list: t.Object({}),
  update: t.Object({
    name: t.String(),
    definition: t.Object({}),
  }),
  delete: t.Object({ id: t.String() }),
}

// export type CreateChainSchemaType = s<typeof ChainSchemas.create>;
export type CreateChainSchemaType = Static<typeof ChainSchemas.create>;
```

By exporting the `Static` type from Elysia itself, it would simplify and streamline the development process.

#### Considered alternative

An alternative could be to manually patch the types, but that introduces a new layer of complexity and potential sources of error.

#### Additional context

This feature will help in better aligning Elysia with Typebox capabilities, providing users with a more robust and type-safe experience.

**Comment by SaltyAom** [comment]
`Static` is now re-exported from TypeBox in 0.7.16.
