### ISSUE TITLE
Can I use Eden-client with NodeJS?

### ISSUE THREAD

**Issue by nickerlan** [elysiajs/elysia#257]
Looking forward to use Elysia for backend and to give frontend team (using NextJS + appDir + vercel which is currently has no Bun runtime support) a type-safe sdk (kind of trpc). What is the best way to do it without codegen? Is the TRPC itself the only option here?

**Comment by ronanru** [comment]
Eden client runs find both in the browser and on Node.

**Comment by nickerlan** [comment]
I've managed to make it work with external codebase. 
Just in case someone would need the workaround:

`bun add -D typescript tsc`

```
 "scripts": {
    "dev": "bun run --watch src/index.ts",
    "gen": "tsc  --declaration --skipLibCheck --isolatedModules --emitDeclarationOnly --target es2015 --module NodeNext --moduleResolution NodeNext --outDir PATH_TO_EXTERNAL_REPO_TYPES_FOLDER"
  },
```

`bun gen`

External repo must have elysia installed as dev dependency as well

**Comment by hieunguyen-sens-vn** [comment]
Same issue, I'm using Nextjs with Elysia in NX monorepo.
import `type App` from Elysia app to Nextjs app result to `any`

**Comment by SaltyAom** [comment]
Eden is platform agnostic not depending on runtime.

So as long as you setup TypeScript correctly, you should be able to use Eden on Node.

**Comment by Wafje** [comment]
Hi @hieunguyen-sens-vn.

Have you gotten around to fixing this in your project?
I am facing the same issue with a bun monorepo (workspace).

I have tried with .group and .use
Both seem to resolve App to the `any` type
