### ISSUE TITLE
 Request-Level State Assignment for Elysia Instance

### ISSUE THREAD

**Issue by iserioton** [elysiajs/elysia#259]
I have read the docs and can't find out on how to store data at the request-response level.

For Example: 
```typescript
// Set request-level state in Elysia instance
elysiaInstance.req.locals = { key: 'value' };

// Access request-level state
const requestValue = elysiaInstance.req.locals.key;

``` 

In many web applications, it is common to need request-specific data that should not persist across multiple requests. Express.js, for example, provides the "res.locals" object for this purpose, allowing developers to store data that is relevant only for the duration of a single HTTP request-response cycle. I believe that having a similar feature in the Elysia instance would be highly beneficial.

**Comment by cool3rain** [comment]
You can use State

`app.state('key', 'value')`

and above is accessible via context.store.version which is global state object.

**Comment by iserioton** [comment]
> You can use State
> 
> `app.state('key', 'value')`
> 
> and above is accessible via context.store.key which is global state object.

This is a global state object and I want a request-level state.  @cool3rain 
For example: 
```javascript
req.local.use = {
    user_id: 123,
    user_name: XYZ
}
```

**Comment by cool3rain** [comment]
user decorate

`const app = new Elysia().decorate('user', {user_id: 123, username: 'xyz'}).get("/", ({ user }) => user).listen(3000);`

**Comment by iserioton** [comment]
> You can use derive too
> 
> For example:
> 
> ```ts
> const userProfile = new Elysia({
>   name: "user-profile-plugin",
> })
>   .use(sessionPlugin()) // suppose we have a session plugin that provides a session object 
>   .derive(async ({ session }) => {
>     const user = await getUser(session.userId);
>     return {
>       user,
>     };
>   });
> 
> const userProfileHandler = new Elysia({
>     name: "user-profile-handler",
> })
>   .use(userProfile) // use userProfile plugin so we can access user object in the handler
>   .get("/profile", ({ user }) => {
>     return user
>   })
>   .put("/profile", ({ session, user, body }) => { // we can access session too since it's used in userProfile plugin
>     // ... update user profile
>   });
> ```

This works!!!! Thanks @masfahru
