### ISSUE TITLE
How to connect socket.io?

### ISSUE THREAD

**Issue by heitoke** [elysiajs/elysia#260]

**Comment by cool3rain** [comment]
socket.io does work with the ElysiaJS which is based on Bun which uses uWebSockets so there's no need to use socket.io

**Comment by heitoke** [comment]
Will I have my own methods for accepting and sending data? And how do I connect from the client (socket.io-client) to the server?

**Comment by cool3rain** [comment]
`
// server.tsx
import { Elysia } from "elysia";
import { cors } from '@elysiajs/cors';

const app = new Elysia()
  .use(cors())
  .ws('/ws', {
      open: (ws) => {
        console.log(ws.data);
      },
      message: (ws, message) => {
        console.log(message);
      },
      close: (ws) => {
        console.log(ws)
      }
    })
    .listen(8080)

console.log(
  `🦊 Elysia is running at ${app.server?.hostname}:${app.server?.port}`
);



// client.tsx
const WebSocket = require("ws");

const ws = new WebSocket("http://localhost:8080/ws");

ws.on("error", console.error);

ws.on("open", function open() {
  ws.send("your_data");
});

ws.on("message", function message(data) {
  console.log("received: %s", data);
});`
