### ISSUE TITLE
EdenFN is not available anymore

### ISSUE THREAD

**Issue by ptrxyz** [elysiajs/elysia#261]
I wanted to try out EdenFN however it seems to be gone completely:

![image](https://github.com/elysiajs/elysia/assets/209056/d1c06a04-6269-45dd-aaea-addebdb03e8a)

checking the module reveals:

![image](https://github.com/elysiajs/elysia/assets/209056/ff877c30-360b-4501-b42b-919a80762c02)

There is simply no export for Eden FN.
Also the backend seems to be broken:

![image](https://github.com/elysiajs/elysia/assets/209056/cd30506a-30e6-4157-a9cd-b2fa383fb610)

I followed the installation guides on the website and started from a blank project. So I am pretty sure, it was either moved to a new package or removed completely. Can someone shed some light into this?

**Comment by fecony** [comment]
Looks like Elysia.fn was moved in Elysia 0.4 according to this release blog: https://elysiajs.com/blog/elysia-04.html

But documentation wasn't changed and repository is not public, @SaltyAom 
https://github.com/elysiajs/elysia-fn

**Comment by ptrxyz** [comment]
That makes it basically "gone", right? No way for me to access it?

**Comment by cmmartin** [comment]
> That makes it basically "gone", right? No way for me to access it?

> In this release, to use Elysia Fn, you're required to explicitly install @elysiajs/fn to use Elysia Fn

**Comment by SaltyAom** [comment]
Closing as not going to implement in near future.
