### ISSUE TITLE
I would like to port a REST API to Elysia, can I use Javascript to begin with

### ISSUE THREAD

**Issue by istvano** [elysiajs/elysia#268]
Hi,

Great looking framework. I would like to use bun so Elysia looks very good. I have a problem that I need to port an existing REST Api weitten in Javascript. Eventually I will need typesafety but at the begining I would like to use JS code.

Will this be possible with Elysia, so that I can just copy the existing JS code it. Change the routing and eventually when I add new feature I would use Typescript?

Thanks

**Comment by SaltyAom** [comment]
Yes, you can just use `.js` to co-exist with `.ts`.
