### ISSUE TITLE
API Proposal: add hook that runs after validations have taken place but before any handlers

### ISSUE THREAD

**Issue by abhi-slash-git** [elysiajs/elysia#270]
Currently the `derive` action runs along with transforms. I was looking for a way to run an effect on each request after `validations` have taken place, i.e after a `guard` action.

For example in the below code, the `derive` will always run before `guard`, it isn't clear by looking at the code due to how `derive` is computed. 

This causes `headers.authorization` to be missing when `derive` runs on the request lifecycle even though the code appears to be inferring the correct type since `derive` appears after the `guard`.

```typescript
export const testRoute = new Elysia({
  scoped: true
})
  .onError(({ error }) => {
    console.log(error);
  })
  .guard(
    {
      headers: t.Object({
        authorization: t.String()
      })
    },
    (app) =>
      app
        .derive(({ headers: { authorization } }) => {
          const token = authorization.split(' ')[1];
          return { token };
        })
        .get('/test', () => ({ message: 'Hello World' }))
  );

```

**Comment by abhi-slash-git** [comment]
#265 is a possible change to handle the above but adding a new api is also a way forward

**Comment by dodas** [comment]
Just got bitten by this. I thought `.derive()` would run at the point where it is called in the chain (as inferred types suggest), instead of always running before validations. I was trying to do exactly what @abhi-slash-git posted in his example.

**Comment by dodas** [comment]
@SaltyAom thoughts on this, please?

**Comment by abhi-slash-git** [comment]
Check this out @dodas 

[resolve](https://elysiajs.com/life-cycle/before-handle.html#resolve)


I believe this should be the right step forward. I'll be trying this out shortly and close this issue if it works as intended.

**Comment by dodas** [comment]
hey @abhi-slash-git 
have you played with it? any findings?

**Comment by abhi-slash-git** [comment]
I haven't had a chance to test it yet. 

If someone gets to it before me, please post here.

**Comment by abhi-slash-git** [comment]
I tested the new `resolve` api and it works as expected.
