### ISSUE TITLE
Manually set headers are being overwritten

### ISSUE THREAD

**Issue by joachimhviid** [elysiajs/elysia#273]
When returning a stream or file from a route handler the `Content-Length` header is being overwritten to the total file size instead of the manually set header.

I have attempted to use the `set` function from the context parameter to set the header manually and the `new Response()` method with the headers in the options (as per the [docs](https://elysiajs.com/concept/handler.html#response)). Using either approach will correctly set other headers, but the `Content-Length` changes on the request.

Example handler:
```typescript
const song = Bun.file('PATH_TO_FILE', { type: 'audio/mpeg' })

const chunkSize = 500000 // ~500KB

const start = Number(range.replace(/\D/g, ''))
const end = Math.min(start + chunkSize, song.size - 1)

const contentLength = end - start + 1

const res = new Response(song.stream(contentLength), {
  status: 206,
  headers: {
    'Content-Range': `bytes ${start}-${end}/${song.size}`,
    'Accept-Ranges': 'bytes',
    'Content-Length': String(contentLength),
    'Content-Type': 'audio/mpeg',
  }
})

console.log(res.headers) // Headers are correct (Content-Length = 500001)
return res
``` 

Returns the following response headers:
```
HTTP/1.1 206 Partial Content
Content-Range: bytes 0-500000/5959817
Accept-Ranges: bytes
Content-Type: audio/mpeg
content-length: 5959817
```

**Comment by masfahru** [comment]
I _think_ it's the nature of Bun to [write the Content-Length header automatically](https://github.com/oven-sh/bun/blob/378385ba60900be7bd797923c219ec489101f2f5/packages/bun-uws/src/HttpResponse.h#L162). Have you tried using [Bun.file to stream a file](https://bun.sh/docs/api/http#streaming-files)?

**Comment by joachimhviid** [comment]
> I _think_ it's the nature of Bun to [write the Content-Length header automatically](https://github.com/oven-sh/bun/blob/378385ba60900be7bd797923c219ec489101f2f5/packages/bun-uws/src/HttpResponse.h#L162). Have you tried using [Bun.file to stream a file](https://bun.sh/docs/api/http#streaming-files)?

Thank you for the insight, I wasn't aware that Bun also manages the headers. Unfortunately I am already using a BunFile as my response value (I have edited my code snippet above for clarity).

Returning just the BunFile without the set headers/status, but sliced as the bun docs show, it will return with a status of 200 and a correctly set `Content-Length`, but no `Content-Range`. This results in only the initial slice being returned, which is not the behavior I am expecting, although I am admittedly not too familiar with the 'behind-the-scenes' functionality of browser media elements like `<audio>` in my case.

**Comment by SaltyAom** [comment]
Assuming this is on Bun side not Elysia and no ongoing discussion.

I'm going to close this issue as resolved.

Feels free to reopen the issue if further discussion is need.
