### ISSUE TITLE
Error.message is truncated when running in docker

### ISSUE THREAD

**Issue by gliviu** [elysiajs/elysia#274]
I have en error handler that works perfectly fine when running the app locally. However when running the same app as docker container, the error message seem to be chunked.
```typescript
const app = new Elysia()
  .onError(({ error }) => { console.log(error.message); return 'error'; })
  ...
```

Local output:
```
Invalid response, 'data/5/phone': Required property

Expected: {
  "paginationInformation": {
    "currentPage": 0,
    "totalPages": 0,
    "pageSize": 0,
...
```

Same code executed with Docker, I get truncated error message:
```
Invalid response
```

Dockerfile and package.json attached.

If needed I could work a minimal example.

Maybe related to #272

[package.json](https://github.com/elysiajs/elysia/files/13029699/package.json)
[Dockerfile.txt](https://github.com/elysiajs/elysia/files/13029703/Dockerfile.txt)

**Comment by SaltyAom** [comment]
Assuming that you are running production mode, this is expected behavior.

For security reasons, will remove data type and properties from the response to prevent the attacker from mimicking and determining data type.

Feels free to reopen if the answer is not clear.
