### ISSUE TITLE
Cannot set more than one Reactive Cookie in the same handler

### ISSUE THREAD

**Issue by fernandohjunqueira** [elysiajs/elysia#277]
I am building an app with Elysia and Supabase.
During sign in step, I'm trying to set two cookies (access_token and refresh_token).

Setting the value of one cookie works flawlessly. However, when I set the values of two or more cookies in the same handler, there are no 'Set-Cookies' headers on the response, so no cookie is set at all.

I was following [this article tutorial](https://elysiajs.com/blog/elysia-supabase.html), but adapting it to use Reactive Cookie from 0.7 instead of cookie plugin.

Below is the code of the signin route (I am also using HTMX and JSX)

```typescript
import { Elysia, t } from "elysia"
import { SignInPage } from "@pages/signin"
import { supabase } from "db"

export const auth = new Elysia({ prefix: "/auth" })
  .get("/signin", () => <SignInPage />)
  .post(
    "/signin",
    async ({ cookie: { access_token, refresh_token }, body: { email, password } }) => {
      const { data, error } = await supabase.auth.signInWithPassword({
        email,
        password,
      })

      access_token.set({
        value: data.session?.access_token,
        httpOnly: true,
        path: "/",
      })
      
      /* If I comment the block below, it sets access_token flawlessly. */
      refresh_token.set({
        value: data.session?.refresh_token,
        httpOnly: true,
        path: "/",
      })

      if (error) return <h1>Wrong Credentials</h1>

      return (
        <>
          <h1>Welcome, {email}!</h1>
          <p hx-swap-oob="true" id="username">
            {email}
          </p>
        </>
      )
    },
    {
      body: t.Object({
        email: t.String({ format: "email" }),
        password: t.String({ minLength: 4 }),
      }),
    }
  )
```

I've already tried using many kinds of alternative syntax and setting the header manually. Couldn't make it work yet.

Looks similar to https://github.com/elysiajs/elysia/issues/98. It was mentioned that Reactive Cookies update was going to fix this, so I don't know if what I'm posting is a bug or I am doing some misconfiguration.

**Comment by SaltyAom** [comment]
Should be fixed in the latest version (0.7.26) at the time.

Feels free to reopen this issue if the problem still persists.
