### ISSUE TITLE
Persistent data per web socket connection (like `ws.data` in Bun)

### ISSUE THREAD

**Issue by SewerynKras** [elysiajs/elysia#279]
With buns web socket implementation, it's possible to assign custom data to a client that persists as long as the connection is open like so:
```ts
type WebSocketData = {
  lastSeen: number;
};

Bun.serve<WebSocketData>({
  fetch(req, server) {
    server.upgrade(req, {
      data: {
        lastSeen: Date.now(),
      },
    });
    return undefined;
  },
  websocket: {
    async message(ws) {
      console.log(ws.data); // will print the timestamp of the previous message
      ws.data.lastSeen = Date.now();
    },
  },
});
```

This property can also be accessed in Elysia with `ws.raw.data` but from looking at the source code I see that it's used internally here: https://github.com/elysiajs/elysia/blob/main/src/ws/index.ts#L11 and furthermore the type seems to be always set to `validator?: TypeCheck<TSchema>` here: https://github.com/elysiajs/elysia/blob/main/src/ws/types.ts#L49 so there is no way to use it in a type-safe way. 

Obviously, it's possible to avoid the issue with typescript by explicitly casting `ws.raw.data` to your desired type, but this seems less than ideal:

```ts
import { Elysia } from "elysia";
type WebSocketData = {
  lastSeen: number;
};
new Elysia()
  .ws("/ws", {
    message(ws) {
      console.log(ws.raw.data);
      (ws.raw.data as WebSocketData).lastSeen = Date.now();
      // doing ws.raw.data = { lastSeen: Date.now() } will completely break the internal websocket handler
    },
  })
  .listen(8080);
```

Am I missing something here? Is there a way to achieve custom data per connected client in Elysia in another way than using `ws.raw.data`? 

If this is in fact a missing feature I'd be happy to implement it and issue a PR :)

**Comment by arnaudbzn** [comment]
Same issue here. 
Supporting Web Socket Data is a must for many use cases with Web Sockets based apps.
The `ws.id` is also changing everytime `message (ws)` is called so it is required to store something like `ws.raw.data = { connectionId: nanoid() }` 
Bun implementation is fine (except that `ws.publish` is [not working](https://github.com/oven-sh/bun/issues/4443) in the close handler).

**Comment by SaltyAom** [comment]
You should be able to use [state, decorate](https://elysiajs.com/concept/state-decorate.html) to add custom property to `ws.data` with type safety here.
```ts
import { Elysia } from 'elysia'

const app = new Elysia()
	.decorate('a', 'b')
	.ws('/', {
		message({ send, data: { a } }) {
			send(a)
		}
	})
	.listen(3000)
```

**Comment by deadlinecode** [comment]
For anyone thats like me and still doesn't know how to authenticate a user in the http request and have the user object available in later socket instances here is a example:
```ts
import { Elysia, t } from 'elysia'

const app = new Elysia().group('/ws', { query: t.Object({ token: t.String() }) }, (app) =>
  app
    .derive(({ query: { token } }) => {
      const user = null // use the token to get the user
      if (!user) throw new Error('User not found')
      return { user }
    })
    .ws('/', {
      open: ({ data: { user } }) => {
        console.log(`[ws] ${user.username} CONNECTED`)
      },
    })
)
```
Basically the trick is to group the ws endpoint and then use the derive to do the authentification so that you can attach the user object to the current context and use it via ws.data.user since ws.data is the elysia context of the initial http request
