### ISSUE TITLE
Bug: Bun build with version 0.7.3 and "Readable" with @elysiajs/html plugin

### ISSUE THREAD

**Issue by daviszung** [elysiajs/elysia#285]
When using version 0.7.0, elysia seems to work fine with the html plugin and bun build, but there is a change in a more recent version that seems to be incompatible with bun build.

Thanks for Elysia BTW!

Video:
https://github.com/elysiajs/elysia/assets/95515224/fdd1617f-9e03-4d9b-9ac1-b92b9e426672

**Comment by SaltyAom** [comment]
Because `bun build` expected browser as one of the build target.

This can be resolved by specifying target to either node or bun but not browser.
```bash
bun build --target bun src/index.ts
```
