### ISSUE TITLE
URL fragment are not captured

### ISSUE THREAD

**Issue by mogharsallah** [elysiajs/elysia#286]
When requesting a url with a [url fragment](https://developer.mozilla.org/en-US/docs/Web/API/URL/hash). I am not able to find the fragment within the context.
Is there a way capture this fragment? I tried the different [lifecycle events](https://elysiajs.com/concept/life-cycle.html) But I was not able to find this information anywhere in the context.

Example:
```
http://localhost:3000/callback/#access_token=123&refresh_token=123...
```

**Comment by rsromanowski** [comment]
Unless you are doing something weird the fragment is not sent by the browser to the server. See: https://stackoverflow.com/questions/940905/can-i-read-the-hash-portion-of-the-url-on-my-server-side-application-php-ruby

**Comment by mogharsallah** [comment]
Thank you @rsromanowski ! I wasn't aware about this fact.
I am using [supabase](https://supabase.com/) for authentication which sends the user into a callback endpoint with the credentials as a fragment.

**Comment by mogharsallah** [comment]
As @rsromanowski have [mentioned](https://github.com/elysiajs/elysia/issues/286#issuecomment-1783685948), the fragment part is not sent by the browser and thus can't be recognised by the server.
