### ISSUE TITLE
Extract failing field in validation

### ISSUE THREAD

**Issue by gianLuigiL** [elysiajs/elysia#287]
I don't seem to find a way to extract which field failed validation based on schema definition?
For this validation schema:
`{
      body: t.Object({
        email: t.String({
          minLength: 1,
        }),
        password: t.String({
          minLength: 1
        }),
      }),
    }`
   And this body:
   `{
    "email": "hello@example.com",
    "password": ""
}`
I get this error:
`{
    "code": "VALIDATION",
    "status": 400,
    "type": "body",
    "validator": {
        "schema": {
            "type": "object",
            "properties": {
                "email": {
                    "minLength": 1,
                    "error": "email",
                    "type": "string"
                },
                "password": {
                    "minLength": 1,
                    "type": "string"
                }
            },
            "required": [
                "email",
                "password"
            ],
            "additionalProperties": false
        },
        "references": [],
        "code": "return function check(value) {\n  return (\n    (typeof value === 'object' && value !== null && !Array.isArray(value)) &&\n    (typeof value.email === 'string') &&\n    value.email.length >= 1 &&\n    (typeof value.password === 'string') &&\n    value.password.length >= 1 &&\n    Object.getOwnPropertyNames(value).length === 2\n  )\n}",
        "hasTransform": false
    },
    "value": {
        "email": "hello@example.com",
        "password": ""
    }
}`

Which teels little about what field is actually failing, can you point me in the direction of a solution?

Thanks again for the great work

**Comment by willykleitinho** [comment]
Hey there. This doesn't seem to be documented yet, but when validation fails, you get a ValidationError, in which you get the `all` property on the `error` object, getting an array like the following: 
```
[
  {
    "type": 45,
    "schema": {
      "type": "string"
    },
    "path": "/name",
    "message": "Required property"
  },
  {
    "type": 61,
    "schema": {
      "anyOf": [
        {
          "const": "S",
          "type": "string"
        },
        {
          "const": "A",
          "type": "string"
        }
      ]
    },
    "path": "/currency",
    "value": "sS",
    "message": "Expected union value"
  }
]
```

And here is how I'm using it in on the `onError` middleware, where I've written the `transformErrors` function to delete duplicate errors for the same path:
```
const app = new Elysia()
  .onError(({ error }) => {
    if (error instanceof ValidationError) {
      return {
        message: "Invalid body",
        errors: transformErrors(error.all),
      };
    }

    return {
      message: error.message,
    };
  })
```

**Comment by SaltyAom** [comment]
As @willykleitinho.

We do have documentation on [catching custom error property using all](https://elysiajs.com/patterns/error-handling.html#catching-all-error).
