### ISSUE TITLE
Run Elysia on Unix socket instead of network port

### ISSUE THREAD

**Issue by libersoft-org** [elysiajs/elysia#288]
**Is there a way to let Elysia run on Unix socket instead of network port, like Express and Bun.serve are able to?**

```js
const app = new Elysia();
app.post('/', () => 'Hello world!');
app.listen('/run/server.sock');
```

**Returns:**

Error: Port must be a numeric value

**Comment by libersoft-org** [comment]
> Someone from Discord wrote me to try this:
> 
> ```js
> import { Elysia } from 'elysia';
> 
> const app = new Elysia().get('/', () => '');
> 
> Bun.serve({
>     unix: '/tmp/elysia.sock',
>     fetch: app.fetch,
> });
> ```
> 
> Did not tested yet, but will try it soon. If it works, would be great if you implement it to your docs.

This works pretty great! Please add it to your documentation.

**Comment by SaltyAom** [comment]
Alternatively, you should be able to do:
```ts
new Elysia({
    serve: {
            unix: '/tmp/elysia.sock'
    }
})
```

We have mentioned it in [constructor](https://elysiajs.com/concept/config.html#constructor)

**Comment by libersoft-org** [comment]
> Alternatively, you should be able to do:
> 
> ```ts
> new Elysia({
>     serve: {
>             unix: '/tmp/elysia.sock'
>     }
> })
> ```
> 
> We have mentioned it in [constructor](https://elysiajs.com/concept/config.html#constructor)

Where? There is no mention of "unix" on that page.

**Comment by libersoft-org** [comment]
> Alternatively, you should be able to do:
> 
> ```ts
> new Elysia({
>     serve: {
>             unix: '/tmp/elysia.sock'
>     }
> })
> ```
> 
> We have mentioned it in [constructor](https://elysiajs.com/concept/config.html#constructor)

This is not working, throws an error:  ENOENT: No such file or directory

**Comment by libersoft-org** [comment]
It seems like **Bun.serve** walkaround is not working in the new version of Elysia.

Elysia throws:

`Elysia server is not initialized. Make sure to call Elyisa.listen()`

Any idea what to do with that?

**Comment by libersoft-org** [comment]
Hmm, seems like it is not supporting WebSocket with **Bun.serve** walkaround.
Please reopen this issue.
