### ISSUE TITLE
Ability to localize TypeBox errors

### ISSUE THREAD

**Issue by mrBrownys** [elysiajs/elysia#289]
Thanks for your awesome work!

I need to localize validation errors from TypeBox. But the method from the documentation does not work with Elysia errors https://github.com/sinclairzx81/typebox/tree/master#typesystem

Perhaps I missed something...

Thank you in advance

**Comment by SaltyAom** [comment]
Fix with eabe264, available on 0.7.27.

You should be able to import and configure TypeSystem from 'elysia/type-system', using same API as TypeBox.

Feels free to reopen if the issue still persists.
