### ISSUE TITLE
Type error occurs when using plugins in 0.3.2

### ISSUE THREAD

**Issue by tnraro** [elysiajs/elysia#29]
I would like to report that I'm experiencing a type error after updating to version 0.3.2.
I have tested the packages `@elysiajs/cookie`, `@elysiajs/static`, and `@elysiajs/swagger`.

```ts
import { cookie } from "@elysiajs/cookie";
import { staticPlugin } from "@elysiajs/static";
import { swagger } from "@elysiajs/swagger";
import { Elysia } from "elysia";

new Elysia()
  .use(staticPlugin())
  .use(cookie())
  .use(swagger())
```

Each plugins has type error like this:

```
Argument of type 'Promise<(app: Elysia<ElysiaInstance<{ store: Record<string, unknown>; request: {}; schema: {}; meta: Record<unique symbol, {}> & Record<unique symbol, {}> & Record<unique symbol, {}>; }>>) => Elysia<...>>' is not assignable to parameter of type 'Promise<{ default: (elysia: Elysia<any>) => MaybePromise<Elysia<never>>; }> | MaybePromise<(app: Elysia<ElysiaInstance<{ store: Record<string, unknown>; request: {}; schema: {}; meta: Record<...> & ... 1 more ... & Record<...>; }>>) => MaybePromise<...>>'.
  Type 'Promise<(app: Elysia<ElysiaInstance<{ store: Record<string, unknown>; request: {}; schema: {}; meta: Record<unique symbol, {}> & Record<unique symbol, {}> & Record<unique symbol, {}>; }>>) => Elysia<...>>' is not assignable to type 'Promise<{ default: (elysia: Elysia<any>) => MaybePromise<Elysia<never>>; }>'.
    Type '(app: Elysia<ElysiaInstance<{ store: Record<string, unknown>; request: {}; schema: {}; meta: Record<unique symbol, {}> & Record<unique symbol, {}> & Record<unique symbol, {}>; }>>) => Elysia<...>' is not assignable to type '{ default: (elysia: Elysia<any>) => MaybePromise<Elysia<never>>; }'.
```

Additionally, I have encountered a runtime issue with `@elysiajs/swagger`.

```
31 | const typebox_1 = require("../typebox");
32 | const index_1 = require("../custom/index");
33 | const index_2 = require("../format/index");
34 | class TypeSystemDuplicateTypeKind extends Error {
35 |     constructor(kind) {
36 |         super(`Duplicate kind '${kind}' detected`);
            ^
error: Duplicate kind 'File' detected
      at new TypeSystemDuplicateTypeKind (/node_modules/@sinclair/typebox/system/system.js:36:8)
      at CreateType (/node_modules/@sinclair/typebox/system/system.js:56:18)
      at /node_modules/elysia/dist/custom-types.js:1:1031
      at /node_modules/elysia/dist/index.js:1:9516
```

For your reference, the tested package versions are as follows:

elysia: 0.3.2
@elysiajs/cookie: 0.3.0
@elysiajs/static: 0.3.2
@elysiajs/swagger: 0.3.0

**Comment by SaltyAom** [comment]
This might sound weird but while I was able to replicate the error, seems like Bun accidentally installed an `experimental` channel instead of `stable` randomly causing the type error.

To verify, can you please go into `node_modules/@elysiajs/static`, the correct results should be no `node_modules` folder inside, but if so, can you please go inside the `node_modules/@elysiajs/static/node_modules/elysia/package.json` and see if the version match your installed version.

If this happens, can you try deleting `node_modules`, and `bun.lockb` and reinstall again using `bun install`, restart your IDE if needed, and see if the problem stills persists?

If the issue still persists, can you please try again with either npm / yarn / pnpm to see if the problem still occurs?

**Comment by SaltyAom** [comment]
Additionally, I found that, this occurs only when you update from elysia version with plugin installed.

So, suppose you previously has Elysia 0.3.1 installed with `@elysiajs/cookie`, `@elysiajs/static`, and `@elysiajs/swagger`, and then update to Elysia 0.3.2, `bun install` for some reason, will grab the latest release (regardless of channel) instead of reusing the installed module.

Deleting `node_modules` and `bun.lockb` solve the problem, for some reason.

Will report this to Bun.

**Comment by tnraro** [comment]
Oh, There was a `node_modules` folder inside `node_modules/@elysiajs/static`, and the elysia version inside it was locked at 0.3.1. I resolved the issue by deleting the `node_modules` and `bun.lockb` as you wrote. Thank you.

**Comment by 1bye** [comment]
@SaltyAom Hi! After updating elysia from `0.7.21` to `0.8.5` got error:
```js
TypeError: Spread syntax requires ...iterable not be null or undefined
      at _use (/home/mrbye/Documents/GitHub/flow-server/node_modules/elysia/dist/bun/index.js:341:34605)
      at /home/mrbye/Documents/GitHub/flow-server/node_modules/elysia-autoroutes/dist/index.js:10186:5
      at processTicksAndRejections (:61:77)

```
(Also tested `0.8.3` and `0.8.0` which throwing errors too, but `0.7.31` don't throw)
As you can see I use `elysia-autoroutes`
Thanks

**Comment by kravetsone** [comment]
> @SaltyAom Hi! After updating elysia from `0.7.21` to `0.8.5` got error:
> ```js
> TypeError: Spread syntax requires ...iterable not be null or undefined
>       at _use (/home/mrbye/Documents/GitHub/flow-server/node_modules/elysia/dist/bun/index.js:341:34605)
>       at /home/mrbye/Documents/GitHub/flow-server/node_modules/elysia-autoroutes/dist/index.js:10186:5
>       at processTicksAndRejections (:61:77)
> 
> ```
> (Also tested `0.8.3` and `0.8.0` which throwing errors too, but `0.7.31` don't throw)
> As you can see I use `elysia-autoroutes`
> Thanks



@1bye when i used this library, i got same error)
And i release a `elysia-autoload` plugin
You can use it instead of `elysia-autoroutes`
https://github.com/kravetsone/elysia-autoload

**Comment by 1bye** [comment]
@kravetsone Hi! Thanks for this plugin, but unfortunately is not working, the same error:
```js
TypeError: Spread syntax requires ...iterable not be null or undefined
      at _use (/home/mrbye/Documents/GitHub/flow-server/node_modules/elysia/dist/bun/index.js:341:34613)
```
But maybe this error occurs because in your plugin, elysia version is `0.7.31`

**Comment by kravetsone** [comment]
> @kravetsone Hi! Thanks for this plugin, but unfortunately is not working, the same error:
> ```js
> TypeError: Spread syntax requires ...iterable not be null or undefined
>       at _use (/home/mrbye/Documents/GitHub/flow-server/node_modules/elysia/dist/bun/index.js:341:34613)
> ```
> But maybe this error occurs because in your plugin, elysia version is `0.7.31`


In my plugin elysia version never been `0.7.31`...

**Comment by 1bye** [comment]
@kravetsone Sorry this error was in my project, I've installed your plugin when I had elysia `0.7.21`

**Comment by jellydn** [comment]
Could we open this issue again? This is my starter and got linter and type-checking issue when upgrade from 0.7 to 0.8? https://github.com/jellydn/elysia-demo-app/pull/68

**Comment by lnfel** [comment]
I just shot myself on the foot with this one. Gonna switch to pnpm now.
