### ISSUE TITLE
configuring base url for elysiajs url

### ISSUE THREAD

**Issue by sammeowww** [elysiajs/elysia#297]
I want to use path based routing for my application

e.g. 
https://example.com/dev/app1/login  -->  Dev server
https://example.com/prod/app1/login --> Prod server

May I know whether i can define the basename similar to this for reactjs?
`<BrowserRouter  basename={'/react-student-management'}>`

https://stackoverflow.com/questions/41440240/configuring-apps-basename-in-react-router

thank you!

**Comment by SaltyAom** [comment]
You can use `prefix` in constructor to achieve this:
```ts
new Elysia({ prefix: '/basepath' })
    .get('/hi', () => 'hi')
    .listen(3000)

// http://localhost:3000/basepath/hi -> 'hi'
```

Feels free to reopen the issue if this doesn't answer your question.
