### ISSUE TITLE
error always log

### ISSUE THREAD

**Issue by SaltyAom** [elysiajs/elysia#3]
Continue from [saltyaom/kingworld#15](https://github.com/SaltyAom/kingworld/issues/15)

## Question
> ```typescript
> import { KingWorld } from 'kingworld';
> 
> new KingWorld()
>     .get('/', () => 'Hi')
>     .get('/error', () => {
>         throw new Error('test')
>     })
>     .onError(error => {
>         console.log(error.name === 'test');
>     })
>     .listen(8080)
> ```
>
> If you start the app and visit http://localhost:8080/error should only see "false" in the logs, instead I see this.
>
> ```bash 
> ➜  bun-test git:(main) ✗ bun run ./src/index.ts
> [0.09ms] ".env"
> false
> 1 | import { KingWorld } from 'kingworld';
> 2 | 
> 3 | new KingWorld()
> 4 |     .get('/', () => 'Hi')
> 5 |     .get('/error', () => {
> 6 |         throw new Error('test')
>                   ^
> error: test
>       at /Users/xo/code/bun-test/src/index.ts:6:14
>       at /Users/xo/code/bun-test/node_modules/kingworld/build/es/index.js:285:24
>       at handle (/Users/xo/code/bun-test/node_modules/kingworld/build/es/index.js:220:17)
> ```

## Answer
> I understand that the all error log is annoying, tbh I also looking for a way to disable error logging.
> 
> From what I found, if an Error is thrown in the async function in Bun, it will always log an error, the bug is now reported and pending on Bun.
> 
> Please keep this issue until [oven-sh/bun#1435](https://github.com/oven-sh/bun/issues/1435) is fixed, to see if the issue still occurs.

**Comment by SaltyAom** [comment]
Fixed with 0.1.0-rc.5

**Comment by rodrigoclp** [comment]
Hello SaltyAom!

Do you know if we still have this issue?
I am running bun 0.6.14 and Elysia latest and still getting the error logs - this way the onError does not work properly.

Thank you very much!

**Comment by rodrigoclp** [comment]
No worries here! For some reason, for a GET, I can put the onError after it, for a POST, worked well only when I put the onError before it. But it is working fine.
