### ISSUE TITLE
Exstend ws in REST context?

### ISSUE THREAD

**Issue by MariuzM** [elysiajs/elysia#302]
I have a case where on client i want to make rest call then receive response via websocket. 

The only way for now is have a variable `wss` and assign `ws` to it and then just use that. But would be really nice if instead of that i can use `c` Context `c.ws.publish('group-chat', { message: '222', time: Date.now() })`

```ts
const app = new Elysia();

export let wss: any;

app
  .post('/test', (c) => {
    wss.publish('group-chat', { message: '222', time: Date.now() });
  });

app
  .ws('/ws', {
    body: t.Object({
      message: t.String(),
    }),
    open(ws) {
      wss = ws;
      const msg = `${ws.id} joined`;
      ws.subscribe('group-chat');
      ws.publish('group-chat', { message: msg, time: Date.now() });
    },
    message(ws, { message }) {
      console.log('🚀 ~ message:', message);
      ws.publish('group-chat', { message, time: Date.now() });
    },
  })
  .listen(8080);

app.listen(Number(process.env.PORT) || 3000, () => {
  console.log(`🦊 ${app.server?.hostname}:${app.server?.port}`);
});

```

**Comment by MariuzM** [comment]
Another way via decorate i could do it but not sure what is cleaner 

```ts
let wss: any;

const app = new Elysia().decorate('getWss', () => wss);

  .post('/test', (c) => {
    c.getWss().publish('group-chat', { message: '111111', time: Date.now() });
    // wss.publish('group-chat', { message: '222', time: Date.now() });
  });
```

**Comment by SewerynKras** [comment]
Heya, you can send messages to connected websockets using the underlying bun `Server` instance, like so:
```ts
import { Elysia } from "elysia";

const app = new Elysia()
  .ws("/ws", {
    open(ws) {
      ws.subscribe("group-chat");
    },
  })
  .post("/message", () => {
    app.server!.publish("group-chat", "Hello World!");
  })
  .listen(8080);

console.log("Listening on port 8080");
```

in this example `curl localhost:8080/message -X POST` will send "Hello World!" to all connected websockets

**Comment by MariuzM** [comment]
OH nice this worked great, but still curious is this the best approach?

**Comment by SaltyAom** [comment]
Prior to Elysia 0.7 used to provide a websocket plugin to provide `publish`, but you can use this little snippet to do the same trick.

```ts
import type { Server } from 'bun'

const publish = (app: Elysia) =>
	app
		.decorate('publish', app.server?.publish as Server['publish'])
		.onRequest((context) => {
			if (app.server) context.publish = app.server!.publish
		})

const app = new Elysia()
	.use(publish)
	.get('/', ({ publish }) => {
		publish('hello', 'world')

		return 'Hello World'
	})
	.listen(3000)
```

Feels free to reopen the issue if the answer is not clear.

**Comment by MutedOne** [comment]
@s

> Heya, you can send messages to connected websockets using the underlying bun `Server` instance, like so:
> 
> ```ts
> import { Elysia } from "elysia";
> 
> const app = new Elysia()
>   .ws("/ws", {
>     open(ws) {
>       ws.subscribe("group-chat");
>     },
>   })
>   .post("/message", () => {
>     app.server!.publish("group-chat", "Hello World!");
>   })
>   .listen(8080);
> 
> console.log("Listening on port 8080");
> ```
> 
> in this example `curl localhost:8080/message -X POST` will send "Hello World!" to all connected websockets

is this sample is working. i tried like that  app server is null or unditified
