### ISSUE TITLE
Using a hook/guard/schema with a handler function and request without body results in a "Unexpected end of JSON input"-error

### ISSUE THREAD

**Issue by RationalMatta** [elysiajs/elysia#304]
When you define a route with
1. a hook/guard/schema
2. no HTTP body like a GET
3. handler function that gets context as parameter

you will get an "Unexpected end of JSON input"-error handling that request in line
https://github.com/elysiajs/elysia/blob/9b294fdc2e2e69dae40f62ac5315327502810c50/src/compose.ts#L715 

As far as I see this combination causes body to be read and parsed becase  `hasBody==true` because `hasUnknownContext==true` because `isContextPassToFunction` returns that.  This looks like a workaround of some other situation that is not working as intended (`hasBody` should not be true) but I don't dare to say how it should work.

Simplest reproduction I could find is below where localhost:5000/ok and localhost:5000/ok2 works but localhost:5000/error gives the error.

```typescript
import { Elysia, t } from "elysia";
import { swagger } from '@elysiajs/swagger'

function handleRequestOk() {
    return {}
}

function handleRequestError(c:any) {
    return {}
}

const elysia = new Elysia()
.use(swagger({documentation: {"openapi": "3.1.0"}}))
.get("/ok", (context) => new Object, {type: "application/json", response: t.Object({})})
.get("/ok2", (context) => handleRequestOk(), {type: "application/json", response: t.Object({})})
.get("/error", (context) => handleRequestError(context), {type: "application/json", response: t.Object({})})
.listen(5000);
``` 

For some context what I'm trying to achieve is that
1. accurate schema is used both for validation and for an accurate swagger-page (I want to automatically generate this)
2. general purpose handler is used for all requests (they are passed to an orm-like thing downstream)
3. hook is typed so the swagger-page has correct type `application/json`

From these 1 and 2 are fundamental and hard to change. 3 I might be able to workaround, i.e. control the swagger mime type in some other way and read body as text and parse JSON myself (but can't really see how it should work).

**Comment by SaltyAom** [comment]
Fix with eabe264, available on 0.7.27.

Feels free to reopen if the issue still persists.
