### ISSUE TITLE
Elysia({ scoped: true }) should still expose defined routes on type level

### ISSUE THREAD

**Issue by dodas** [elysiajs/elysia#305]
When defining a router with `new Elysia({ scoped: true })` and then using it in a parent router with `.use()`, the parent router's type won't reflect the routes added in child routers.

I am using `scoped: true` in child routers in order to prevent their middlewares leaking into parent router, but this leads to the parent router's type not reflecting the child routes and therefore preventing their use with Eden.

Example:
```ts
const childRouter = new Elysia({ scoped: true }).get("/child", () => "Hello from child route");
const parentRouter = new Elysia().use(childRouter);

const client = edenTreaty<typeof parentRouter>("");
// client is of type `unknown`
```

**Comment by SaltyAom** [comment]
Fix with eabe264, available on 0.7.27.

Feels free to reopen if the issue still persists.
