### ISSUE TITLE
`t.Numeric` should not convert empty string to 0

### ISSUE THREAD

**Issue by mnpenner** [elysiajs/elysia#308]
I have an HTML `<select>` that looks something like

```
<select name="opponent">
<option value="">— Select —</option>
<option value="1">option 1</option>
<option value="2">option 2</option>
</select>
```

Which I serialize to JSON and sent to the server.

`t.Numeric()` is converting the values to JS `number`s like I want, but it also allows the empty string to go through. It converts it to a `0` instead of rejecting the request.

Can this be disallowed?

**Comment by SaltyAom** [comment]
Fix with eabe264, available on 0.7.27.

Feels free to reopen if the issue still persists.
