### ISSUE TITLE
t.RegExp doesn't work due to requiring default value

### ISSUE THREAD

**Issue by mnpenner** [elysiajs/elysia#309]
If I try something like this:

```
    .group('/api', app => app
        .post('/games/:slug/play', ({db, user, params, body}) => {
            // ...
        }, {
            body: t.Object({
                player: t.RegExp(/^(\d+(\.\d*)?|\.\d+)$/),
            })
        })
    )
```

I get an error:

```
Error: ValueCreate.String: String types with patterns must specify a default value
    at NJ (/mnt/c/Users/Mark/PhpstormProjects/botvsbot/node_modules/elysia/dist/bun/index.js:2:82839)
    at <anonymous> (/mnt/c/Users/Mark/PhpstormProjects/botvsbot/node_modules/elysia/dist/bun/index.js:2:82219)
    at reduce (:1:11)
    at new S0 (/mnt/c/Users/Mark/PhpstormProjects/botvsbot/node_modules/elysia/dist/bun/index.js:2:131852)
    at <anonymous> (:118:50)
    at processTicksAndRejections (:61:39)
```

I think `RegExp` and `t.String` *without* a default should be supported.

---

OK, so I understand why [Create](https://github.com/sinclairzx81/typebox#create) needs a default value now, but I still don't understand why Elysia is creating values in the first place. It should be [decoding](https://github.com/sinclairzx81/typebox#decode) the body, no?

**Comment by SaltyAom** [comment]
`default` is used in `Value.Create` which use in validation error page to show expected data structure comparing to current incoming body.

However with eabe264, available on 0.7.27, this is no longer required by skipping the creation progress entirely (losing ability to compare data structure).

Feel free to reopen if the issue still persists.
