### ISSUE TITLE
Preserve original hostname when using `.mount()`

### ISSUE THREAD

**Issue by dodas** [elysiajs/elysia#310]
When using the `.mount()` method, the mounted request handler will get requests where the original hostname is always replaced with `http://a.cc` – see [here](https://github.com/elysiajs/elysia/blob/9b294fdc2e2e69dae40f62ac5315327502810c50/src/index.ts#L1673) and [here](https://github.com/elysiajs/elysia/blob/9b294fdc2e2e69dae40f62ac5315327502810c50/src/index.ts#L1688).

Is there a reason for this? Can we preserve the original host instead?

**Comment by SaltyAom** [comment]
Fix with eabe264, available on 0.7.27.

Feels free to reopen if the issue still persists.
