### ISSUE TITLE
`.guard(` leads to side effects outside of internal callback.

### ISSUE THREAD

**Issue by Nmans01** [elysiajs/elysia#311]
Originally sent this on Discord.
![image](https://github.com/elysiajs/elysia/assets/12779283/27af8765-dda4-41ae-ab70-fdcddd6a288e)
Note how `name` and `id` are defined in the callbacks of routes that are not included within the guard call here.

**Comment by Nmans01** [comment]
This appears fixed as of 0.7.25

**Comment by Nmans01** [comment]
Although the typing seems fixed in the latest release (currently I'm on 0.7.29), decorators from inside the guard are still accessible outside the guard, despite being typed as always undefined.

**Comment by SaltyAom** [comment]
Decorators are always presented regardless of scopes by design to reduce performance overhead.

Closing as expected behavior, and not going to change.
