### ISSUE TITLE
Bundling typebox?

### ISSUE THREAD

**Issue by JakeHedman** [elysiajs/elysia#317]
`dist/bun/index.js` seems to include a full copy of `@sinclair/typebox`. It breaks `TypeSystem.Type`, `TypeSystem.Format` etc since elysia uses an internal typebox instance. `elysia/type-system` exports the global typebox instance so there is no way to access the elysia typebox.

**Comment by Micnubinub** [comment]
For me its breaking my builds, I'm getting a lot of `TypeBoxError: Duplicate type kind 'Files' detected`. I don't know if this was the best idea

**Comment by SaltyAom** [comment]
Elysia now excludes TypeBox from bundling in 0.8.7.

Feels free to reopen the discussion if need.

**Comment by SaltyAom** [comment]
Reopen because when TypeBox is excluded from Bun bundle causing an error (see 0.8.7)
If added back (only change in 0.8.8), it seems to be working again.

Not sure why this happen but seems like we can't find a way to do that just yet.
