### ISSUE TITLE
Expo Types Issue

### ISSUE THREAD

**Issue by patlux** [elysiajs/elysia#32]
Hi,

I'm trying to use this in an [Expo](https://expo.dev) project. It works really good, the only odd thing are these errors when running `tsc --noEmit --skipLibCheck`:

![CleanShot 2023-03-29 at 18 53 27](https://user-images.githubusercontent.com/4481570/228612065-b7078aa1-baa0-41e5-a66a-cd9b8816f11c.png)

Any idea to fix this?

It's a monorepo with `npm workspaces` which includes the bun-based backend app and the expo-based mobile app.

**Comment by SaltyAom** [comment]
For the record, if I recall correctly this issue is mentioned in Elysia Discord, and resolved by settings `strict: true` in `tsconfig.json`.

If this is not the case, please re-open the issue, thank you.
