### ISSUE TITLE
Guard doesn't respect `aot: false`

### ISSUE THREAD

**Issue by Mkassabov** [elysiajs/elysia#323]
It seems like guard doesn't respect the `aot: false` setting on the Elysia instance. This means that `.gaurd` doesn't work in environments where AoT doesn't work.

**Comment by SaltyAom** [comment]
Lacking reproducible example code and probably have been fixed in previous subsequent Elysia versions and patches.

Feels free to reopen the issue or open a new one if the problem still persists, thanks.
