### ISSUE TITLE
Type system missing format

### ISSUE THREAD

**Issue by masterT** [elysiajs/elysia#328]
It is possible to define the schema using some format, but not all allowed formats are supported.

Ex: `uri` is not allowed but not supported.

See [codesandbox](https://codesandbox.io/p/devbox/nervous-babbage-7h6nqk?codemirror=1&embed=1&file=%2Feden.ts&hidedevtools=1&hidenavigation=1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clp9nb7f500093b6iwh9kxk8i%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clp9nb7f500043b6iqi0t3jh6%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clp9niv8t013m3b6i1u1frfki%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clp9nb7f500083b6ij33kdlyi%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B75.61603922%252C24.383960779999995%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clp9nb7f500043b6iqi0t3jh6%2522%253A%257B%2522id%2522%253A%2522clp9nb7f500043b6iqi0t3jh6%2522%252C%2522activeTabId%2522%253A%2522clp9nwlf102dd3b6i488caw6s%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fapp.test.ts%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A12%252C%2522endLineNumber%2522%253A12%252C%2522startColumn%2522%253A2%252C%2522endColumn%2522%253A2%257D%255D%252C%2522id%2522%253A%2522clp9nwlf102dd3b6i488caw6s%2522%252C%2522mode%2522%253A%2522temporary%2522%257D%255D%257D%252C%2522clp9nb7f500083b6ij33kdlyi%2522%253A%257B%2522id%2522%253A%2522clp9nb7f500083b6ij33kdlyi%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522SANDBOX_INFO%2522%252C%2522id%2522%253A%2522clp9ny00y02ll3b6iyd5g1lmw%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clp9ny00y02ll3b6iyd5g1lmw%2522%257D%252C%2522clp9niv8t013m3b6i1u1frfki%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp9nitbf013i3b6ia9d8a8ms%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clp9nivjd00x2eiji1orv9jwh%2522%257D%255D%252C%2522id%2522%253A%2522clp9niv8t013m3b6i1u1frfki%2522%252C%2522activeTabId%2522%253A%2522clp9nitbf013i3b6ia9d8a8ms%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by SaltyAom** [comment]
Fixed by fbadb73, published under 1.0.11
