### ISSUE TITLE
mount() does not preserve query params

### ISSUE THREAD

**Issue by dodas** [elysiajs/elysia#329]
When mounting a handler via `mount()`, the received URL is missing whole `query` from original URL:
[https://github.com/elysiajs/elysia/blob/757357f28749674844fc848e4ddd715134f7714f/src/index.ts#L1715](https://github.com/elysiajs/elysia/blob/757357f28749674844fc848e4ddd715134f7714f/src/index.ts#L1715)

**Comment by ashwani007mishra** [comment]
// Assuming getHostname is a function to get the hostname from the request

function mountWithQueryParams(request, path) {
  const queryParams = new URLSearchParams(request.url.search);
  const fullPath = path + (queryParams.toString() ? `?${queryParams.toString()}` : '');
  return getHostname(request.url) + fullPath;
}

// Example usage:
const url = mountWithQueryParams(request, '/your/path');

**Comment by silvio2402** [comment]
Wow, I was just going to open an issue about this until I saw your issue :smiley:.

Made this reproduction if that helps:
```ts
import Elysia from "elysia";

const handler = (req: Request) => {
  return new Response(`req.url: ${req.url}`);
};

new Elysia()
  .get("/good", ({ request }) => handler(request))
  .mount("/bad", handler)
  .listen(3000);

console.log("Server started on http://localhost:3000");

console.log(
  await fetch("http://localhost:3000/good?myparam=hello").then((res) =>
    res.text()
  )
);
// Output: req.url: http://localhost:3000/good?myparam=hello

console.log(
  await fetch("http://localhost:3000/bad?myparam=hello").then((res) =>
    res.text()
  )
);
// Output: req.url: http://localhost:3000
```
