### ISSUE TITLE
mount() does not preserve body when fetching through http server

### ISSUE THREAD

**Issue by silvio2402** [elysiajs/elysia#332]
A handler mounted with mount() gets an empty body when the handler is called by an HTTP request to the HTTP server (app.listen()).

I've tried the following combinations of calling a handler and only in the specific case that an HTTP request is handled by a mounted handler does this issue occur:

|              | elysia handler | mounted handler |
| ------------ | -------------- | --------------- |
| app.handle   | ✅             | ✅              |
| app.fetch    | ✅             | ✅              |
| http request | ✅             | ❌              |

Here's a reproduction of this issue:

```ts
import { Elysia } from './src'

const handler = async (req: Request) => {
	return new Response(await req.text())
}

const app = new Elysia().mount('/mount', (req) => handler(req))

app.listen(3005)

const body = 'sucrose'

const options = {
	method: 'POST',
	body
}

const res = await fetch('http://localhost:3005/mount', options)
console.log(`Body: ${JSON.stringify(await res.text())}`)

app.stop()

```

Does anyone have an idea what could be going on?

**Comment by bogeychan** [comment]
Hi 👋

looks like it's a bug with Bun; the following doesn't work either:

```ts
const server = Bun.serve({
	port: 3005,
	async fetch(request) {
		const req = new Request(request) // this line breaks it
		return new Response(await req.text())
	}
})

const res = await fetch('http://localhost:3005', {
	method: 'POST',
	body: 'yay'
})

console.log(`Body: ${await res.text()}`)

server.stop()
```

Here is the position in the source code:

https://github.com/elysiajs/elysia/blob/2f732d799833953c8ff08f1a48b9ec58a14aa029/src/index.ts#L1714-L1717
