### ISSUE TITLE
[FEATURE] Add cookie validation for derive

### ISSUE THREAD

**Issue by itsyoboieltr** [elysiajs/elysia#334]
I would like to derive something from a cookie, but currently as far as I know there is no way to provide cookie validation for the derive function, so all cookies have the type any inside derive. This would be a nice dev exp feature :)

**Comment by Nmans01** [comment]
Using a group or a guard with a schema will allow you to access a typed version of the cookie from `derive` . The same goes for other things you can assign schemas for, like query and params.
```ts
const examplePlugin = new Elysia()
    .guard({
        cookie: t.Cookie({
            someCookie: t.Object({
                name: t.String(),
            })
        })
    }, app => app
        .derive(({ cookie: { someCookie } }) => {

            // type error, id is not part of cookie
            someCookie.value.id;

            return { user: someCookie.value.name }
        })
        .get("/test", ({ user }) => {

            return "Hello " + user;
        })
    )
```

**Comment by SaltyAom** [comment]
Fixed by introduction of [resolve](https://elysiajs.com/life-cycle/before-handle.html#resolve)
