### ISSUE TITLE
Add a new constructor parameter to have integrated services

### ISSUE THREAD

**Issue by Arthurmtro** [elysiajs/elysia#339]
Hey,
I'm working on a project, 
I love the Controller | Service concept for this kind of framework, but actually I was using the 

```ts
// thing.controller.ts
const service = new MyControllerService() // this is the boring thing because it feels like a hack
export const myController = new Elysia({  prefix: '/myController' })

myController.get(':id', ctx => (
 return service.handleId(ctx.params.id)
)
```

So in my actual workflow I've managed to have something I prefer, and I fill is more in touch with the mantras of Elysia

```ts
// thing.controller.ts
const service = new MyControllerService() // this is the boring thing because it feels like a hack
export const myController = new Elysia({  prefix: '/myController' })
  .decorate('service', new MyControllerService())

myController.get(':id', ctx => (
 return ctx.service.handleId(ctx.params.id)
)
```

But I notice I do this in any of my controller, as in a clean architecture I believe in the separation of concepts, so controller doesn't deal with all the service related shit but only with the http/api things

What if, we were adding this service as a new parameter for the Elysia constructor ?? 
I mean, optional but can be cleaner for projects and make it feels less hacky (and can be optimized later on!)

```ts
// thing.controller.ts
export const myController = new Elysia({
  prefix: '/myController',
  service: new myController(), //this can be object that already understand some concept of Elysia, so we can extends at creation to have some set of tools ! class ConversionService extends Service {...}
})

myController.get(':id', ctx => (
 return ctx.service.handleId(ctx.params.id)
)

```

What are your thought on this?

I really think I'm not the only one that does tricky things to handle this, and I think it's a so important flow that including it in the constructor would be even cleaner for code experience

I absolutely can contribute to this, but I want to know that do you think of this all

Happy coding !!

**Comment by Nmans01** [comment]
Having migrated from NestJS to Elysia, I like the service + controller model as well. However, I've applied it in a different way, and found that Elysia already provides the necessary tooling.

Elysia projects are comprised of plugins, and so I find that controllers and services can both be plugins, each with their own purpose. Using `.derive` and `.decorate`, you can append useful functions/logic in a service plugin, and use `.use` to append the service plugin to its corresponding controller plugin. I.e. I have a prismaService, which appends the prisma client to the context, an authService, which uses the prisma service to derive useful auth functions, and an authController, which uses the authService and applies the functions to auth-related endpoints.

In the case of using `.derive` in a service plugin, you can easily access the context object within your "derived" functions, meaning you don't have to create functions which take a fully-typed context as a argument, which seems to be a common pain point people have.

Hope this helps

**Comment by Arthurmtro** [comment]
@Nmans01 , Ohh, interesting, would you mind showing me an implementation of this concept?

**Comment by Nmans01** [comment]
A small example
```ts
// prismaService.ts
const prisma = new PrismaClient();

export const prismaService = new Elysia({ name: "prismaService" })
    .decorate({ prisma })

// authService.ts
export const authService = new Elysia({ name: "authService" })
    .use(prismaService)
    .derive((context) => ({

        getCurrentUser: async () => {
            const user = await context.prisma.user.findFirst({
                // ...
            });
            return user;
        }

    }))

// authController.ts
export const authController = new Elysia({ prefix: "/auth" })
    .use(authService)
    .get("/me", async ({ getCurrentUser }) => {
        const user = await getCurrentUser();
        return { user };
    })

// app.ts
const app = new Elysia()
    .use(authController)
    .listen(3000)
```

**Comment by Arthurmtro** [comment]
This is not stupid at all :o

**Comment by SaltyAom** [comment]
Closing as recommendation by both Nmans01 and WangHansen, and documented in https://elysiajs.com/patterns/mvc.html#mvc-pattern.

Feel free to add further discussion if necessary.

**Comment by dazraf** [comment]
@SaltyAom tried to follow the link above and it returns a 404. Would love any help with figuring out how to do controllers and, specially, dependency injection. Thank you!
