### ISSUE TITLE
[FEATURE] Validation for query string arrays

### ISSUE THREAD

**Issue by itsyoboieltr** [elysiajs/elysia#344]
To enable something like:
```ts
query: t.Object({
  stringArray: t.Array(t.String()),
}),
```
which would be automatically parsed from:
```ts
...api?stringArray=item1,item2,item3
```
into
```ts
const stringArray = ["item1", "item2", "item3"]
```
I believe this is a common enough use case to warrant for an implementation to improve dev exp.

Current workaround: manually parsing the string in the handler.
```ts
query: t.Object({
  stringArray: t.String(),
}),
```
```ts
const stringArray = query.stringArray.split(',');
// ["item1", "item2", "item3"]
```

**Comment by bogeychan** [comment]
You can implement this with built-in hooks:

```ts
import { Elysia, t } from 'elysia';

new Elysia()
  .onTransform((ctx) => { // runs before validation

    // replace this with your own transformation logic
    for (const name in ctx.query) {
      // @ts-expect-error
      ctx.query[name] = ctx.query[name]?.split(';');
    }
  })
  .get('/yay', ({ query }) => query, {
    query: t.Object({
      stringArray: t.Array(t.String())
    })
  })
  .listen(8080);
```

---

A better approach is to use something like [qs](https://www.npmjs.com/package/qs) which also supports objects:

```ts
import { Elysia, t } from 'elysia';
import qs from 'qs';

new Elysia()
  .onTransform((ctx) => {
    // @ts-expect-error
    ctx.query = qs.parse(new URL(ctx.request.url).search.slice(1));
  })
  .get('/yay', ({ query }) => query, {
    query: t.Object({
      foo: t.Object({
        bar: t.String()
      })
    })
  })
  .listen(8080);
```

open `http://localhost:8080/yay?foo[bar]=baz` in your browser

**Comment by floydjones1** [comment]
I came across this need as well. Would be useful

**Comment by thirsty-wing** [comment]
Just a note that there is no consensus on the way to pass an array as query parameter(s): https://medium.com/raml-api/arrays-in-query-params-33189628fa68

- Some software uses `?things=thing1,thing2`

- Other software uses `?things[]=thing1&things[]=thing2`

- Others use  `?things=thing1&things=thing2`

Just noting in case that influences a decision here

Personally I like `?things[]=thing1&things[]=thing2` because that's what I'm used to

**Comment by Blankeos** [comment]
I tried @bogeychan's solution. It works great but when used with Treaty, types are not useful anymore. Mainly because if you want to pass an array via query, you have to do this now:

```ts
	const { data, error } = await app.usersByIds.get({
		query: {
			/** @ts-ignore */
			'ids[0]': 'f85a2461-9501-498f-908a-ac82567862a2'
		}
	});
```

**Comment by Vincz** [comment]
I think the syntax with `?s=val1&s=val2` used to work:

```javascript
{
    query: t.Object({
        s: t.Union([t.Array(t.String()), t.String()]),
    }),
}
```

After an Elysia update, it doesn't anymore.
Like @thirsty-wing  I prefer the `?things[]=thing1&things[]=thing2` syntax as it make it clear what is expected.

**Comment by thirsty-wing** [comment]
@Vincz After reading the spec, it looks like brackets may not be allowed in query params.

> Square brackets are now specified as reserved within the authority component and are not allowed outside their use as delimiters for an IP literal within host.

https://datatracker.ietf.org/doc/html/rfc3986

So even though some software out there supports it, it might be best not to give it special meaning here (if I'm reading the documentation correctly).

**Comment by is-jonreeves** [comment]
> After an Elysia update, it doesn't anymore.

@Vincz thanks for the example, it seems to work ok for me. I just had to remember to handle the fact that it might be an array and coerce to one.

```ts
const validatorGet = { query: t.Object({ keys: t.Union([t.Array(t.String()), t.String()]) }) };

export const get = new Elysia().get('', ({ query }) => {
  const keys = (Array.isArray(query.keys)) ? query.keys : [query.keys];
  ...
}, validatorGet);

**Comment by drsmile1001** [comment]
I think  `keys=1&keys=2`
and 
```typescript
query: t.Object({
      keys: t.Array(t.String()),
    }),
```
break at 1.0.23

**Comment by drsmile1001** [comment]
I report the issue #677 .

**Comment by SaltyAom** [comment]
We can parse query by specifying query as follows:
```ts
const app = new Elysia().get('/', ({ query }) => query, {
	query: t.Object({
		id: t.Array(t.String())
	})
})

app.handle(new Request('http://localhost:3000/?id=1&id=2'))
	.then((x) => x.json())
	.then(console.log)
```

This feature is introduce since 1.1.0 by fc0784b.

Closing as complete, feels free to reopen issue if the problem still persists.

**Comment by danieljvdm** [comment]
This might be related to `aot: false` but I'm getting an issue with this in which if only one param is passed it resolves to a string and throws a 422. I don't think this is intended? I can work around it by typing the field as such:

`idIn: t.Optional(t.Union([t.Array(t.String()), t.String()])),`

and then doing some `typeof idIn === 'string'` stuff to narrow the type and convert the string to an array if it needs to be. Is this how this is supposed to work?
