### ISSUE TITLE
jwt, setCookie and other types don't transfers with default values

### ISSUE THREAD

**Issue by scffs** [elysiajs/elysia#351]
1. I use `@elysiajs/jwt`
2. In my routes I use smth like this

`userRoutes.ts`

![image](https://github.com/elysiajs/elysia/assets/67464545/18f50b27-5d5d-4a4c-bdc7-813e44f70a27)

and then use it like this

`main.ts`

![image](https://github.com/elysiajs/elysia/assets/67464545/cfc984ce-828a-4f90-923d-0285d9e66304)

So in my route function I want to use jwt 
Example:

`authHandler.ts` (route controller)

![image](https://github.com/elysiajs/elysia/assets/67464545/539be9e1-3419-4e99-879c-164d1e3d5297)

but I got an error

![image](https://github.com/elysiajs/elysia/assets/67464545/14847c61-ced6-40e9-ad92-dcace609ff9c)

for myself, I have created custom types that solve this and other problems, but it looks like a crutch

![image](https://github.com/elysiajs/elysia/assets/67464545/70d4cf42-75a9-48b1-b639-8b011d253866)

maybe I do smth wrong or how can I fix this in a different way?

[repo](https://github.com/Diary-SPO/diary-admin/pull/33)

**Comment by vivekrp** [comment]
Any update regarding this issue? I have created a similar custom type to fix the issue for now.

**Comment by SaltyAom** [comment]
This is an expected behavior, as mentioned in https://elysiajs.com/essential/plugin.html#service-locator and https://elysiajs.com/patterns/mvc.html#mvc-pattern.

Either follows the pattern provide in the doc, or use `InferContext` to get the context type of the plugin.

If this doesn't answer your question, feel free to reopen the issue. Thanks.

**Comment by scffs** [comment]
> Either follows the pattern provide in the doc

Yes, I already realized my mistake and carefully studied the MVC pattern

thanks

![image](https://github.com/user-attachments/assets/2cd98e12-a820-4f14-b2c0-58433b7ffcc0)
