### ISSUE TITLE
[QUESTION] [TypeSystem] How to use elysia type system (typebox) with custom errors in schema

### ISSUE THREAD

**Issue by kravetsone** [elysiajs/elysia#357]
Issue for custom typebox erros - https://github.com/sinclairzx81/typebox/issues/85 ([repl](https://codesandbox.io/s/0ekq5?file=/src/index.ts))

Can you implement this in Elysia with type-checking?

**Comment by SaltyAom** [comment]
See: https://elysiajs.com/validation/error-provider.html#message-property

> ### Message Property
> TypeBox offers an additional "error" property, allowing us to return a custom error message if the field is invalid.

> ```typescript
> import { Elysia, t } from 'elysia'
>
> new Elysia()
>	 .get('/', () => 'Hello World!', {
>		body: t.Object(
>			{
>				x: t.Number()
>			},
>			{
>				error: 'x must be a number'
>			}
>		)
>	})
>	.listen(3000)
> ```

**Comment by kravetsone** [comment]
> See: https://elysiajs.com/validation/error-provider.html#message-property
> 
> > ### Message Property
> > TypeBox offers an additional "error" property, allowing us to return a custom error message if the field is invalid.
> 
> > ```typescript
> > import { Elysia, t } from 'elysia'
> >
> > new Elysia()
> >	 .get('/', () => 'Hello World!', {
> >		body: t.Object(
> >			{
> >				x: t.Number()
> >			},
> >			{
> >				error: 'x must be a number'
> >			}
> >		)
> >	})
> >	.listen(3000)
> > ```


it's general error... 
How can i send for example format/minLength error message?

**Comment by 0-don** [comment]
yes exactly having the same problem would like to get an error for each property like minLength maxLength pattern and so on

**Comment by kravetsone** [comment]
I guess it can be closed 

https://elysiajs.com/validation/error-provider.html#error-is-called-per-field

**Comment by bogeychan** [comment]
for those wondering how to do this... from [discord](https://discord.com/channels/1044804142461362206/1044807567022493766/1263546061742407680):

---

you need to `bun add @sinclair/typebox`

and you have to add `IsKindOf` and `IsString` from here as it seems that typebox doesn't export these for whatever reason https://github.com/sinclairzx81/typebox/blob/master/src/type/guard/kind.ts

```ts
import { Elysia, t } from "elysia";
import { ValueErrorType } from "@sinclair/typebox/errors";
import { ValueGuard, Kind, type TString } from "@sinclair/typebox/type";

export function IsKindOf<T extends string>(
  value: unknown,
  kind: T
): value is Record<PropertyKey, unknown> & { [Kind]: T } {
  return ValueGuard.IsObject(value) && Kind in value && value[Kind] === kind;
}

export function IsString(value: unknown): value is TString {
  return IsKindOf(value, "String");
}

new Elysia()
  .post(
    "/",
    () => {
      return {
        yay: "yay",
      };
    },
    {
      body: t.Object({
        yay: t.String({
          minLength: 2,
          pattern: "xyz$",
          error: ({ errors }) => {
            for (const error of errors) {
              if (error.path === "/yay" && IsString(error.schema)) {
                switch (error.type as ValueErrorType) {
                  case ValueErrorType.StringMinLength:
                    return "small";
                  case ValueErrorType.StringPattern:
                    return "bad pattern";
                }
              }
            }
          },
        }),
      }),
    }
  )
  .listen(8080);
```
