### ISSUE TITLE
Response type auto stripping not declared fields or disable type checking?

### ISSUE THREAD

**Issue by m1212e** [elysiajs/elysia#358]
I use the response field for documentation purposes so the generated swagger output has the correct return types set. But sometime I return objects which satisfy the response TS type but contain additional fields which I got e.g. from a more extensive DB query. Now when I return these, TS doesn't complain, since it is a sufficient type, but at runtime the request fails, since the returned object has an additional field.

Is there some way to disable these kinds of typechecks at runtime, or maybe even better, automatically strip all additional fields automatically to comply to my return schema?

**Comment by m1212e** [comment]
Maybe something like this would be an elegant way? Did you consider bringing this into elysia?

https://github.com/sinclairzx81/typebox/issues/278

**Comment by kravetsone** [comment]
[Elysia normalize response by default since 1.1](https://elysiajs.com/blog/elysia-11.html#normalization)

This issue can be closed
