### ISSUE TITLE
Websocket send message to all clients

### ISSUE THREAD

**Issue by ScareCrow95** [elysiajs/elysia#359]
Hello I am trying to figure out how to send a message to all clients in websocket implantation.

`   ws.publish('test', JSON.stringify({ test: 1 }))`

this sends to all clients except sender, I am looking for `Server.publish` like bun docs have. 

![image](https://github.com/elysiajs/elysia/assets/18271051/3d156c27-cffb-4e3c-aa52-b36fae84ed22)

Does elysia have support for this?

**Comment by teodorrd27** [comment]
Yeah, all you gotta do is 
```Typescript
const app = new Elysia()
    .ws('/', {open, close, message, drain })
    .listen(3000) // if you want to run on port 3000
app.server?.publish('the-group-chat', 'Hello world')
```
where `open`, `close`, `message`, and `drain` are `() => {}`s

**Comment by ScareCrow95** [comment]
Thank you so much! I will check it out, I couldnt find it in documentation
