### ISSUE TITLE
Elysia 0.8 Cookie Issues

### ISSUE THREAD

**Issue by sancho1952007** [elysiajs/elysia#373]
I am unable to set cookies in elysia js in the latest version, v0.8.
Here's the code:
```javascript
app.get('/:id/:key', (req) => {
  let expireInOneYear = new Date().setFullYear(new Date().getFullYear() + 1);
  req.cookie.id.set({ value: req.params.id, maxAge: expireInOneYear, httpOnly: true });
  req.cookie.key.set({ value: req.params.key, maxAge: expireInOneYear, httpOnly: true });
  return Bun.file(path.join(__dirname, 'views', 'index.html'));
});
```

I tried all methods after which I downgraded to v0.7 version and it worked.

**Comment by SaltyAom** [comment]
Fixed in 0.8.7, let me know if the problem still persists.

**Comment by VityaSchel** [comment]
I'm still experiencing this. When I access reactive cookie value through .value, it resets expiration date and browser resets cookie to Session

**Comment by VityaSchel** [comment]
Basically every parameter except value is "undefined" on cookie. I'm download a file (streaming it) on this endpoint by the way

**Comment by VityaSchel** [comment]
Can I disable elysia "reactiveness" of cookies? I would like to just use normal way of dealing with them, just accessing value would be enough for me, I don't want to edit anything
