### ISSUE TITLE
Eden Websocket support for pub/sub API

### ISSUE THREAD

**Issue by Lonitch** [elysiajs/elysia#374]
I need to add a live message alert in my app, which should allow users to publish/subscribe different topics. I notice that Bun has  a native publish-subscribe API for [topic-based broadcasting](https://bun.sh/docs/api/websockets#pub-sub). But I need a way to subscribe a user-specific topic at client side, with topic name being the user id, and publish to topics of other user ids. I'm not worrying much about the message history for now, as the real-time message serves as alert to the users. What I found so far is [Eden Treaty](https://elysiajs.com/eden/treaty.html#websocket). But I don't know whether this is possible with Elysia. Any suggestions?

**Comment by vastamaki** [comment]
Can't you just use `socket.subscribe(user_id_here)` on connect and then later where ever you need `app.publish(user_id_here, your_message_here)`? Or did I just misunderstand your problem?

**Comment by Lonitch** [comment]
Thanks for the advice, @vastamaki. After went through the pub/sub example from uWebSocket.js [here](https://github.com/uNetworking/uWebSockets.js/blob/master/examples/PubSub.js), It's now clear to me that I can somehow specify which users the msg needs to be sent to at the server side through query parameters. Now what I wanted to create is basically the following at client side:

1. each user listens to topic of his own user_id (can be down using [eden](https://elysiajs.com/eden/treaty#websocket))
2. each user can send new msgs to channels of ids of other users

I guess I can still do this through two ways:

1. creating group chat like the example shown in which all relevant users get notified by the new messages. 
2. For a more granular communication, meaning that the msgs only sent to the ones specified by user at the client side, I can add more parameters in my query, e.g. `xxxxx?receivers=[user_id1,user_id2]`, and parse them at the server side to send messages to multiple users.

But which way is better in terms of performance?

**Comment by Lonitch** [comment]
With hindsight, it's more relevant to uwebsocket.
