### ISSUE TITLE
WebSocket : Sending a space character (` `) receives `0`

### ISSUE THREAD

**Issue by quentint** [elysiajs/elysia#379]
When sending a space character (` `) to a WebSocket, the received message is `0`. I've added tests in a fork to showcase that:

https://github.com/quentint/elysia/blob/main/test/ws/message.test.ts#L5-L22

The `'Hello!'` and `'0'` pass, but the ` ` fails. I would like to help fix this but I've looked around and didn't find where this could come from. Any pointers appreciated 😉

**Comment by ErickJ3** [comment]
Wouldn't it be appropriate to use 	JSON.stringify to transport messages via websocket? would avoid this type of serialization problem. I will be looking into the problem and opening a PR soon to resolve the possible serialization error. In the meantime, use 	JSON.stringify to transport messages via websocket

example: `JSON.stringify({ message: "Hello!" })`

**Comment by quentint** [comment]
Thanks for your feedback!

Unfortunately I'm writing the server part of the app, but the client one uses a very old standard, and I can't change a thing about it, so I can't decide to format messages differently 😕

**Comment by ErickJ3** [comment]
in fact it is an implementation problem. I would recommend that when sending messages on the websocket channel you ignore completely empty messages. in the implementation somehow it is converting the total empty space to 0

**Comment by quentint** [comment]
But I cannot differentiate spaces wrongfully converted to 0, and actual zeroes.

What do you mean by an implementation problem? Did you locate it?

**Comment by SaltyAom** [comment]
Fixed in 0.8.7.

Feels free to re-open if the problem stills persists
