### ISSUE TITLE
`TypeError: Elysia is not a constructor` when bundling for node (with polyfills) with esbuild with esm

### ISSUE THREAD

**Issue by BLucky-gh** [elysiajs/elysia#399]
since the `node` entry in package.json points to the cjs build, that's what's imported, but it seems like for some reason it results in the default export of the `Elysia` class going under `exported.module.default.default`, and when marking elysia as external in esbuild, esbuild correctly inserts `import Elysia from "elysia"` in the resulting bundle, but the actual class still gets exported under `Elysia.default`, so `new Elysia` errors out, but editing the bundle manually to do `new Elysia.default` makes it work properly. 

You can find some more info under https://github.com/evanw/esbuild/issues/3580

Importing Elysia as a named import rather than the default import with `import { Elysia } from "elysia"` works, but the `@bogeychan/elysia-logger` plugin imports elysia via default import and I have no control of that

**Comment by dodas** [comment]
Relevant: https://github.com/elysiajs/elysia/issues/396

**Comment by SaltyAom** [comment]
Elysia now exports esm and cjs separately as follows:
```json
{
	"exports": {
		"./package.json": "./package.json",
		".": {
			"types": "./dist/index.d.ts",
			"bun": "./dist/bun/index.js",
			"import": "./dist/index.mjs",
			"require": "./dist/cjs/index.js"
		}
        }
}
```

This should have fixed the problem with import and require separately.
