### ISSUE TITLE
`body` validator breaks when request body is JSON

### ISSUE THREAD

**Issue by jcarpe** [elysiajs/elysia#400]
Elysia: v0.8.8
Bun: v1.0.15

Works:
```typescript
// elysia
new Elysia()
  .post('/', ({ request }) => 'reponse')

// test
elysiaInstance.handle( new Request( 
  'http://localhost:8080/', {
    method: 'POST',
    body: JSON.stringify({ value: 'string' })
  }
)

```

Broken:
```typescript
// Elysia
new Elysia()
  .post('/', ({ request }) => 'reponse', {
    body: t.Object({ value: t.String() })
  })

// test
elysiaInstance.handle( new Request( 
  'http://localhost:8080/', {
    method: 'POST',
    body: JSON.stringify({ value: 'string' })
  }
)
```

In the non-functional scenario, the response is a 400 bad request. The same request with no definition is a 200 as expected.

Additionally, the same result occurs when using a curl on the above as well (as opposed to a unit test implementation).

**Comment by kravetsone** [comment]
> new Elysia()
>   .post('/', ({ request }) => 'reponse', {
>     body: t.Object({ value: t.String })
>   })

Maybe `t.String()`?)

**Comment by jcarpe** [comment]
@kravetsone -Thanks! Updated my pseudo-code typo above, but the result is the same with the correct syntax.

**Comment by vdgame** [comment]
add headers: { 'Content-Type': 'application/json' }:

elysiaInstance.handle( new Request( 
  'http://localhost:8080/', {
    headers: { 'Content-Type': 'application/json' },
    method: 'POST',
    body: JSON.stringify({ value: 'string' })
  }
)

**Comment by jcarpe** [comment]
🤦🏼 

Indeed specifying the content type seems to resolve this. While this seems very obvious, the example in the docs would then be functional I believe: https://elysiajs.com/validation/schema-type.html#body

@SaltyAom - I pulled the documentation repo, but I don't think I (anyone?) has permission to PR against that repo to make the small update there?

**Proposal:**
Under "Body" for the "Schema-Type" page:

> The body is provided as same as `body` in `fetch` API. The content type is set accordingly to the defined body.
> 
> ```typescript
> fetch('https://elysiajs.com', {
>     method: 'POST',
>     headers: { 'Content-Type': 'application/json' },
>     body: JSON.stringify({
>         name: 'Elysia'
>     })
> })
> ```
> 
> ...

**Comment by bogeychan** [comment]
@jcarpe you have to fork the repo first.

There are a number of resources on this topic, I recommend this one: https://github.com/firstcontributions/first-contributions?tab=readme-ov-file#first-contributions

**Comment by jcarpe** [comment]
Closed with: https://github.com/elysiajs/documentation/pull/256
