### ISSUE TITLE
Error when using Guard inside Group

### ISSUE THREAD

**Issue by zulfio** [elysiajs/elysia#401]
Hi, i want to implement user check(middleware) for **/api/v1/auth** route/group.

index.js:
```
const app = new Elysia();
app.use(authRoutes);
```

authRoutes.js:
```
const authRoutes = (app) => {
  app.group("/api/v1/auth", (app) => {
    return app
      .guard({
        beforeHandle({ set }) {
          console.log("check the user before do the otp");
        },
      })
      .post("/req-otp", requestOTP)
      .post("/validate-otp", validateOTP);
  });
};
```

It's throwing an error after i'm adding the .guard method:
`TypeError: (X?.beforeHandle??[]).map is not a function. (In '(X?.beforeHandle??[]).map(Y)', '(X?.beforeHandle??[]).map' is undefined)`

**Comment by hvdson** [comment]
i had a similar problem and this seemed to solve it https://github.com/elysiajs/elysia/issues/156 
currently on 0.8.8

**Comment by SaltyAom** [comment]
Unable to replicate the problem in the latest version with the following code:
```ts
const plugin = new Elysia().group('/api/v1/auth', (app) => {
	return app
		.guard({
			beforeHandle({ set }) {
				console.log('check the user before do the otp')
			}
		})
		.post('/req-otp', () => 'ok')
		.post('/validate-otp', () => 'ok')
})

const app = new Elysia().use(plugin)

app.handle(
	new Request('http://localhost/api/v1/auth/req-otp', {
		method: 'POST'
	})
)
	.then((x) => x.text())
	.then(console.log)
```

If the problem still persists, feel free to reopen the issue.
