### ISSUE TITLE
group function compiler error

### ISSUE THREAD

**Issue by xslim** [elysiajs/elysia#403]
When implementing `group` function like this:
```ts
app.group("/test", (app: Elysia) => app.get("/", () => 'hello test'))
```
I am getting error `Argument of type '"/test"' is not assignable to parameter of type '""'.`

But when implemented like this
```ts
app.group("/test", (app: any) => app.get("/", () => 'hello test'))
```
the error is gone.

The reason why I want to have `app: Elysia` is to have this route in separate file, so I could do something like

```ts
// testRoute.ts
export default function configureRoute(app: Elysia) {
  app.get("/", () => 'hello test')
  return app
}

// index.ts
import testRoute from './testRoute'

app.group('/test', testRoute)
```

**Comment by gaetandezeiraud** [comment]
Same problem here.

**Comment by runyasak** [comment]
Here is my temporary solution to create a route to another file:

```ts
import Elysia from "elysia";

export type GroupRoute<GroupPath extends string> = Elysia<GroupPath>;

export default function configureRoute(app: GroupRoute<"/test">) {
  app.get("/", () => "hello test");
  return app;
}
```

Elysia will create a new instance for `group`, so I must declare `Elysia` type with the base path.

If you have some state or decorators, you need to specify decorators to `Elysia` type too.

```ts
export type GroupRoute<T extends string> = Elysia<
  T,
  DecoratorBase & { store: { build: number } }
>;
```

---

Waiting @SaltyAom for the proper solution.

**Comment by xslim** [comment]
My current solution:

```
export default function configureRoute(app: any) {
  return (app as Elysia)
  .get()
  .post()
}
```

**Comment by SaltyAom** [comment]
Should have been fixed by introduction of prefix constructor option.

```ts
const configureRoute = new Elysia({ prefix: '/stuff' }) 
```

Or alternatively, we can use generic to configurable prefix:
```ts
const configureRoute = <const T extends string>(prefix: T) => new Elysia({ prefix }) 
```

Feel free to reopen if this doesn't answer your question. Thanks.
