### ISSUE TITLE
Optional `body` type not inferred correctly

### ISSUE THREAD

**Issue by bogdan-manole** [elysiajs/elysia#409]
Long story short, to make `Elysia` accept an optional body (`T | undefined`) the only combination I came up with is:
```typescript
      body: t.Union([
        t.Object({
          my_parameter: t.Optional(t.String()),
        }),
        t.Undefined(),
      ]),

```

this works for the runtime, but when I try to access the `body.my_parameter` property I get a TS error:

```typescript
  .all(
    '/my-route',
    ({ body, html }) => {
      if (body) {
        const param = body.my_parameter   // TS: Error Property 'my_parameter' does not exist on type '{}'.
        return html(<div>{param}</div>)
      }
      return html(<div>no body</div>)
    },
    {
      body: t.Union([
        t.Object({
          my_parameter: t.Optional(t.String()),
        }),
        t.Undefined(),
      ]),
    },
  )
```

I found a hack for that, but is not the most elegant one:
- Extract the `typebox` schema definition outside the route
- create a type from it (with `Static` type definition imported from `typebox`)
- and specify that type on the route and its `type-box` definition in the route options

```typescript
import { Elysia, t, Static } from 'elysia'

.....

const MyBody = t.Union([
  t.Object({
    my_parameter: t.Optional(t.String()),
  }),
  t.Undefined(),
])

.....

  .all(
    '/my-route',
    ({ body: wrongTypedBody, html }) => {
      const body: Static<typeof MyBody> = wrongTypedBody || {}   //TS: valid
      return html(<div>{body.my_parameter ?? 'no body'}</div>)
    },
    {
      body: MyBody,
    },
  )
.....

```

**Comment by kravetsone** [comment]
const MyBody = t.Union([
  t.Object({
    my_parameter: t.Optional(t.String()),
  }),
  t.Undefined(),
])

t.MaybeEmpty is allow to pass T | undefined | null

Won't you need it?
