### ISSUE TITLE
Router: How to ignore unexpected property in query parameters ?

### ISSUE THREAD

**Issue by primadi** [elysiajs/elysia#411]
consider this route:

```js
app.get("/test", ({ query }) => query.name, {
   query: t.Object({
     name: t.String(),
   }),
  }
}
```

if we send query : http://localhost/test?name=xyz

it is ok,

but we add other property than name, it will error..

http://localhost/test?name=xyz&country=indonesia ==> Invalid query, 'country': Unexpected property

how to make Elysia router only search for expected query parameter only, and ignore other query parameters ?

thank you.

**Comment by kravetsone** [comment]
```ts
app.get("/test", ({ query }) => query.name, {
   query: t.Object({
     name: t.String(),
   }, {
     additionalParameters: true
}),
  }
}
```

**Comment by primadi** [comment]
@kravetsone thanks, previous code work even without adding additionalParameters: true, after i update elysia into : "^0.8.9".

**Comment by adarshaacharya** [comment]
@kravetsone can we enable this functionality globally?
