### ISSUE TITLE
swagger : hide endpoint from swagger

### ISSUE THREAD

**Issue by primadi** [elysiajs/elysia#412]
Is it possible to hide specific endpoint from swagger doc ?

thanks.

**Comment by kravetsone** [comment]
You can use exclude Regex)
```ts
.use(swagger({
            exclude: /^\/(auth|github)/i //regexp

}));
```


@SaltyAom 
in @fastify/swagger we can hide the route in the `schema` property
It would be more convenient if we could `hide: true` to `datails` to exclude the route from swagger

```ts
.get("/", "Hello, Elysia!", {
    detail: {
        hide: true
    }
});
```

**Comment by kravetsone** [comment]
@SaltyAom @primadi i guess we can close it because https://github.com/elysiajs/elysia/pull/763 was merged
