### ISSUE TITLE
Returning a subclass of Response shows an empty object {}

### ISSUE THREAD

**Issue by hambergerpls** [elysiajs/elysia#421]
Example code:

```ts
import { Elysia } from "elysia";

class ResponseTest extends Response {}

new Elysia()
    .all('/response', () =>{
        return new Response('Hi')
    })
    .all('/subclass', () =>{
        return new ResponseTest('Hi')
    })
    .listen(3000)

```
Result:
```
/response: Hi
/subclass: {}
```

Hi, based on this [docs](https://elysiajs.com/essential/handler.html#response), I should be able to return a Response class. It does work as shown in the code above. However, if I return a subclass of the Response, it returns an empty object.

This prevents me from creating a subclass of Response that contains different status code and headers. e.g. ResponseWithUnauthorized(). 

A workaround for this is to create a helper function that returns a Response class with the desired status code and header, but I prefer returning a subclass of Response :-)

**Comment by hambergerpls** [comment]
Looking at the code, it seems to be related to this?
https://github.com/elysiajs/elysia/blob/5dc46ab23be7115ec9d0652a44326f46f02ad60b/src/handler.ts#L187-L201

**Comment by bogeychan** [comment]
Hi 👋,

yes, Elysia checks it's `constructor.name`; you can do this as a workaround:

```js
const MyResponse = class Response extends globalThis.Response {};

console.log(new Response().constructor.name === new MyResponse().constructor.name);

import { Elysia } from 'elysia';

new Elysia().get('/', () => new MyResponse('yay')).listen(8080);

```

**Comment by hambergerpls** [comment]
> Hi 👋,
> 
> yes, Elysia checks it's `constructor.name`; you can do this as a workaround:
> 
> ```js
> const MyResponse = class Response extends globalThis.Response {};
> 
> console.log(new Response().constructor.name === new MyResponse().constructor.name);
> 
> import { Elysia } from 'elysia';
> 
> new Elysia().get('/', () => new MyResponse('yay')).listen(8080);
> ```

Thanks for the workaround, but it looks kinda hacky? I'm quite new to js/ts, so this is just my newbie perspective.
