### ISSUE TITLE
[lifeCycle] validation before parse and transform 

### ISSUE THREAD

**Issue by hminhman** [elysiajs/elysia#424]
Version: Elysia 0.8.9 , bun 1.0.22
As doc at: [Essential / Life Cycle](https://elysiajs.com/essential/life-cycle) and [Life Cycle overview](https://elysiajs.com/life-cycle/overview.html), I understand that parse and transform must be run before validation with typebox.

![image](https://github.com/elysiajs/elysia/assets/61128944/6322b86f-985b-431d-816e-e1444fc595f7)

But when I try to modify body by parse or transform before validation, it's not working. Postman told that:
```js
  "expected": {
    "arr": [],
    "file": "File",
    "date": "2024-01-16T02:02:50.369Z"
  },
  "found": {
    "file": {},
    "date": "2024-01-10T10:51:50.976Z",
    "+arr[0].a": "1",
    "+arr[0].b": "2"
  },
```
This is my controller options:
```js
  body: t.Object({
    arr: t.Array(t.Object({a: t.Number(), b: t.Number()})),
    file: t.File(),
    date: t.Date(),
  }),
  transform({body}) {
    console.log('body before:', typeof body, '\n', JSON.stringify(body, null, 2));
    body = toObj(body);
    const date = new Date(body.date);
    isValid(date) && (body.date = date);
    console.log('body after:', typeof body, '\n', JSON.stringify(body, null, 2));
    console.log(
      'body check:\ndate:',
      typeof body.date,
      '-',
      body.date instanceof Date,
      '\nfile:',
      typeof body.file,
      '-',
      body.file instanceof File,
    );
  },
```
and log:
```js
  body before: object 
   {
    "file": {},
    "date": "2024-01-10T10:51:50.976Z",
    "+arr[0].a": "1",
    "+arr[0].b": "2"
  }
  body after: object 
   {
    "file": {},
    "date": "2024-01-10T10:51:50.976Z",
    "arr": [
      {
        "a": 1,
        "b": 2
      }
    ]
  }
  body check:
  date: object - true 
  file: object - true
```
Can anyone give me some ideas about this case?

**Comment by hminhman** [comment]
I just found that if I skip check by remove body typebox. the body inside handler not take transform effect too. It mean transform not working as expected. what I log in transform:
```js
  transform({body}) {
    console.log('body before:', typeof body, '\n', JSON.stringify(body, null, 2));
    body = toObj(body);
    const date = new Date(body.date);
    isValid(date) && (body.date = date);
    console.log('body after:', typeof body, '\n', JSON.stringify(body, null, 2));
    console.log(
      'body check:\ndate:',
      typeof body.date,
      '-',
      body.date instanceof Date,
      '\nfile:',
      typeof body.file,
      '-',
      body.file instanceof File,
    );
  },

//=> log
  body before: object 
   {
    "file": {},
    "date": "2024-01-10T10:51:50.976Z",
    "+arr[0].a": "1",
    "+arr[0].b": "2"
  }
  body after: object 
   {
    "file": {},
    "date": "2024-01-10T10:51:50.976Z",
    "arr": [
      {
        "a": 1,
        "b": 2
      }
    ]
  }
  body check:
  date: object - true 
  file: object - true
```
in handler:
```js
  console.log('body in handler:', typeof body, '\n', JSON.stringify(body, null, 2));
  console.log(
    'body check:\ndate:',
    typeof body.date,
    '-',
    body.date instanceof Date,
    '\nfile:',
    typeof body.file,
    '-',
    body.file instanceof File,
  );

//=> log
  body in handler: object 
   {
    "file": {},
    "date": "2024-01-10T10:51:50.976Z",
    "+arr[0].a": "1",
    "+arr[0].b": "2"
  }
  body check:
  date: string - false 
  file: object - true
```

what wrong with my transform? I just follow [transform example](https://elysiajs.com/life-cycle/transform.html#example)

**Comment by hminhman** [comment]
Finally I found that [transform example](https://elysiajs.com/life-cycle/transform.html#example) was strange. I follow this:
```js
transform({ params }) {
    const id = +params.id
    if(!Number.isNaN(id))
        params.id = id
}
```
to do this:
```js
transform({ body }) {
      const date = new Date(body.date);
      isValid(date) && (body.date = date);
}
```
but not working. And I try this:
```js
transform(context) {
      const date = new Date(context.body.date);
      isValid(date) && (context.body.date = date);
}
```
and it's working.

**Comment by SaltyAom** [comment]
Close as the issue have been resolved. As for JS rule mentioned here

> Finally I found that [transform example](https://elysiajs.com/life-cycle/transform.html#example) was strange. I follow this:
> 
> ```js
> transform({ params }) {
>     const id = +params.id
>     if(!Number.isNaN(id))
>         params.id = id
> }
> ```
> 
> to do this:
> 
> ```js
> transform({ body }) {
>       const date = new Date(body.date);
>       isValid(date) && (body.date = date);
> }
> ```
> 
> but not working. And I try this:
> 
> ```js
> transform(context) {
>       const date = new Date(context.body.date);
>       isValid(date) && (context.body.date = date);
> }
> ```
> 
> and it's working. I think it about js rule. Can anyone explain for me about this?

I'm not sure either. If someone know please help, thanks.
