### ISSUE TITLE
content-type in text response is undefined, should it be 'text/plain' ?

### ISSUE THREAD

**Issue by erf** [elysiajs/elysia#425]
When returning a simple text string from a router, `content-type` is undefined, is this by design or should it be set to `text/plain` ?

Simple test case:

```
test('Elysia should return content-type text/plain', async () => {
	const req = new Request('http://localhost/text')
	const app = new Elysia().get('/text', () => 'Elysia')
	const res = await app.fetch(req)
	console.log(res)
	const resText = await res.text()
	expect(res.status).toBe(200)
	expect(resText).toBe('Elysia')
	expect(res.headers.get('content-type')).toBe('text/plain') // FAILS
});
```

**Comment by erf** [comment]
Also .. i found the documentation for the response a bit lacking. In the first examples text is returned but it is not described. I like in Hono you are more explicit about this by calling  `text` or `json` on the Context object.

**Comment by bogeychan** [comment]
Looks like its a bug with `bun`, i opened an issue: https://github.com/oven-sh/bun/issues/8530

**Comment by SaltyAom** [comment]
Bun automatically add `content-type` to `text/plain` on network layer but not programmatically.

We are not going to implement this as it introduce performance overhead.

Closing as not going to implement. Thanks for your understanding.
