### ISSUE TITLE
Support compression

### ISSUE THREAD

**Issue by ricardo-devis-agullo** [elysiajs/elysia#44]
Hi, is there any plans to add a compression plugin (gzip/brotli) at some point? What's the recommended way of doing it right now, create our own plugin/middleware?

**Comment by SaltyAom** [comment]
We have planned support for adding a compression plugin, however, this is pending on Bun to implement [Compression Stream API](https://developer.mozilla.org/en-US/docs/Web/API/Compression_Streams_API).

A workaround, for now, is to either:
1. Rely on the provider to handle compression. Most providers like Cloudflare, Vercel, GCP, AWS, and Azure automatically handle gzip compression by default.
2. Use reverse proxy like nginx to handle compression

We want to create a compression plugin for the barebone server too, but it's not possible at the moment.

Please leave this open until we implemented until then.

**Comment by SaltyAom** [comment]
Solved on https://github.com/gusb3ll/elysia-compression
