### ISSUE TITLE
URL param match by regex

### ISSUE THREAD

**Issue by vidz1979** [elysiajs/elysia#443]
### What is the problem this feature would solve?

I am building a URL shortener and want to put my link id in the root of project. It is a nanoid with 7 characters. I am get errors because favicon.ico and all other non matched requests fall in the path.

```typescript
server.get("/:id", async ({ params: { id }, set }) => {...})
```

### What is the feature you are proposing to solve the problem?

Other frameworks offer the option to tell the param format using a regex. I think this can be useful here.

```typescript
server.get("/:id{^[A-Za-z0-9_-]{7}$}", async ({ params: { id }, set }) => {...})
```

### What alternatives have you considered?

Move my endpoint to a folder (/link/:id)

**Comment by FDiskas** [comment]
```js
.get('/:id', ({ params }) => params.id, {
    params: t.Object({
      id: t.String({
        pattern: '^[A-Za-z0-9_-]{7}$',
        default: '',
      }),
    }),
  })
```

**Comment by yassine-zhang** [comment]
I need this feature, too

**Comment by kravetsone** [comment]
Match routes with regex is a really evil action. It very slow and may cause [ReDoS attack](https://en.wikipedia.org/wiki/ReDoS?useskin=vector)

**Comment by SaltyAom** [comment]
Close as not going to implement as mentioned by kravetsone and overhead
