### ISSUE TITLE
Mention in Typebox Readme.md under "Ecosystem"

### ISSUE THREAD

**Issue by xddq** [elysiajs/elysia#45]
Hey!

This is a generic message asking you if you would like that this package should be mentioned in the future/new "Ecosystem" section inside the typebox repository.

Would be great if you (any maintainer) could simply drop a reponse in https://github.com/sinclairzx81/typebox/pull/435.

Want it to be part of the documentation?

    Yes -> Then please comment with the package name and a short description for it, for more info see the issue.
    No -> Please simply comment "no thanks - packageNameHere"

Sorry for posting an "issue" for this, I hope it did not bother to much, feel free to close it!

**Comment by SaltyAom** [comment]
Thanks for an invitation, I appreciate it, thanks 😊
