### ISSUE TITLE
Elysia macro does not run when it should

### ISSUE THREAD

**Issue by itsyoboieltr** [elysiajs/elysia#451]
### What version of Elysia.JS is running?

0.8.14

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

Here is the reproduction repo: [elysia-macro-reprod](https://github.com/itsyoboieltr/dbest-stack/tree/elysia-macro-reprod)

Steps: 
1. bun i
2. bun dev
3. Check the file macro and Elysia route implementation in [index.ts](https://github.com/itsyoboieltr/dbest-stack/blob/elysia-macro-reprod/src/routes/api/todo/index.ts)
4. Test and validate on the UI that the `.delete` path does not get guarded, while it should be guarded by a macro, and an error should be thrown.

### What is the expected behavior?

The route is guarded, macro is run, and an error is thrown

### What do you see instead?

The route is not guarded, macro is not run, no error thrown.

### Additional information

In the guard statement, the first function appears to be guarded. The functions coming after seem to ignore the macro in the guard statement. If I copy paste the function into the beforeHandle, then it works.

**Comment by BingCoke** [comment]
same problem

**Comment by itsyoboieltr** [comment]
Thank you! working
