### ISSUE TITLE
 Duplicate type kind 'Files' detected

### ISSUE THREAD

**Issue by itsyoboieltr** [elysiajs/elysia#452]
### What version of Elysia.JS is running?

0.8.15

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

Here is the reproduction repo: [elysia-reprod](https://github.com/itsyoboieltr/dbest-stack/tree/elysia-reprod)

Steps:

1. bun i
2. bun dev
3. Server not working, error is thrown due to the JWT plugin in [index.ts](https://github.com/itsyoboieltr/dbest-stack/blob/elysia-reprod/src/routes/api/index.ts)

### What is the expected behavior?

JWT plugin works.

### What do you see instead?

```
error: Duplicate type kind 'Files' detected
      at new TypeBoxError (node_modules/@sinclair/typebox/build/import/type/error/error.mjs:4:6)
      at new TypeSystemDuplicateTypeKind (node_modules/@sinclair/typebox/build/import/system/system.mjs:13:8)
      at Type (node_modules/@sinclair/typebox/build/import/system/system.mjs:37:16)
      at module code (node_modules/elysia/dist/bun/index.js:366:5628)
      at node_modules/@elysiajs/jwt/dist/cjs/index.js:5:7

1 | /** The base Error type thrown for all TypeBox exceptions  */
2 | export class TypeBoxError extends Error {
3 |     constructor(message) {
4 |         super(message);
         ^
```

### Additional information

Seems similar to this: https://github.com/denoland/deno/issues/21394
But I am not using deno. I am using bun.

**Comment by bogeychan** [comment]
It looks like `vinxi` assumes that your elysia handler under `routes/api/index.ts` is some kind of SSR module and therefore tries to load this handler as SSR. Which in turn causes it to be executed twice.

If it is possible, try telling `vinxi` that this route is not SSR and should be injected as a simple http handler instead. There seems to be a configuration for this (or you have to write your own `vinxi`-plugin), but it has been updated recently and lacks documentation.

... at least from my perspective (i haven't done anything with `vinxi` yet)

**Comment by mehtaabGill** [comment]
did you end up finding a fix for this? also facing the same issue

**Comment by bogeychan** [comment]
This should work now.

There's a type-registery check beforehand:

https://github.com/elysiajs/elysia/blob/321a7c5539b9503cfd9169f8c313643c351037b0/src/type-system.ts#L221-L223

**Comment by SaltyAom** [comment]
Resolved as mentioned by bogeychan

> This should work now.
> 
> There's a type-registery check beforehand:
> 
> https://github.com/elysiajs/elysia/blob/321a7c5539b9503cfd9169f8c313643c351037b0/src/type-system.ts#L221-L223
