### ISSUE TITLE
Using a query key that contains a hyphen raises a SyntaxError

### ISSUE THREAD

**Issue by elliotwaite** [elysiajs/elysia#461]
### What version of Elysia.JS is running?

0.8.15

### What platform is your computer?

Darwin 23.1.0 x86_64 i386

### What steps can reproduce the bug?

```typescript
import { Elysia, t } from 'elysia'

const app = new Elysia()
  .get('/', ({ query }) => query['key-with-hyphen'], {
    query: t.Object({
      'key-with-hyphen': t.String(),
    }),
  })
  .listen(3000)
```

### What is the expected behavior?

To be able to use query keys that contain hyphens.

### What do you see instead?

I receive the following error:
`SyntaxError: Unexpected token '-'. Expected a ':' following the property name 'key'.`

### Additional information

The error still occurs even if the query value isn't accessed within the route handler. Example:
```typescript
import { Elysia, t } from 'elysia'

const app = new Elysia()
  .get('/', () => 'Hello', {
    query: t.Object({
      'key-with-hyphen': t.String(),
    }),
  })
  .listen(3000)
  ```
  
I also tested using a similar syntax with TypeBox to see if it was an issue with TypeBox, but the below example worked without any errors.
  ```typescript
import { Type } from '@sinclair/typebox'
import { Value } from '@sinclair/typebox/value'

const T = Type.Object({ 'key-with-hyphen': Type.String() })

console.log(Value.Check(T, { 'key-with-hyphen': 'this is a test' }))
```

**Comment by denis12301232** [comment]
Same problem with dots
