### ISSUE TITLE
"After Handle - Returned Value" code example seems incorrect.

### ISSUE THREAD

**Issue by elliotwaite** [elysiajs/elysia#462]
### What is the type of issue?

Documentation is incorrect

### What is the issue?

The [After Handle - Returned Value](https://elysiajs.com/life-cycle/after-handle.html#returned-value) code example seems incorrect. It mentions:

> The above example could be rewritten as the following:
> ```typescript
> import { Elysia } from 'elysia'
> import { isHtml } from '@elysiajs/html'
> 
> new Elysia()
>     .get('/', () => '<h1>Hello World</h1>', {
>         afterHandle({ response, set }) {
>             if (isHtml(response))
>                 set.headers['content-type'] = 'text/html; charset=utf8'
>         }
>     })
>     .get('/hi', () => '<h1>Hello World</h1>')
>     .listen(3000)```

...but the "above example" that is being referenced is:
> ```typescript
> import { Elysia } from 'elysia'
> import { isHtml } from '@elysiajs/html'
> 
> new Elysia()
>     .get('/', () => '<h1>Hello World</h1>', {
>         afterHandle({ response, set }) {
>             if (isHtml(response))
>                 set.headers['Content-Type'] = 'text/html; charset=utf8'
>         }
>     })
>     .get('/hi', () => '<h1>Hello World</h1>')
>     .listen(3000)```

...and the only thing different between the two is the casing of `'Content-Type'` was changed to `'content-type'`.

### Where did you find it?

[After Handle - Returned Value](https://elysiajs.com/life-cycle/after-handle.html#returned-value)

**Comment by bogeychan** [comment]
Thanks for reporting! Please open an issue in the documentation repository next time: https://github.com/elysiajs/documentation

_this can now be closed_

**Comment by elliotwaite** [comment]
@bogeychan Okay, thanks for the fix. And I'll open any docs-related issues in the documentation repo next time. I wasn't sure whether I should open the issue in this repo or the documentation one since I noticed that when you open an issue in this repo, it lists the following option:
>📗 **Documentation Issue**
> Tell us if there is missing or incorrect documentation

So I thought that meant that I was supposed to post documentation-related issues in this repo. Perhaps that option could updated to redirect people to the documentation repo instead.

**Comment by bogeychan** [comment]
Oh, thanks. I didn't know about this until recently. there will be a fix for this problem (hopefully) soon https://github.com/elysiajs/elysia/pull/472
