### ISSUE TITLE
Composite reference Model

### ISSUE THREAD

**Issue by KilianB** [elysiajs/elysia#468]
### What is the problem this feature would solve?

The documentation at https://elysiajs.com/validation/reference-model.html states that reference models can be defined to create reusable models. Currently it is only possible to type the entire body, query or response, but individual fields can not reference such a model.

For us it is much more common than not the entire body or response is identical, but rather we want to reuse fields inside more complex definition in multiple places.

````ts
const app = new Elysia()
.model("otpToken",t.String({
  format: 'uuid',
  examples: '550e8400-e29b-41d4-a716-446655440000',
})).post("/url", () => {

}, {
  body: t.Object({
    otpToken: 'otpToken',
    username: t.String()
  })
})
````

### What is the feature you are proposing to solve the problem?

Allow to register individual fields as models. 

### What alternatives have you considered?

You can export partial typebox schemas into a field and use these instead. This has the disadvantage of those schemas not being proberly showing up as reusable schemas inside the openapi spec.

**Comment by Nmans01** [comment]
Typebox supplies utilities like `t.Composite([])`, which will all you to reuse a partial schema in multiple complete schemas, such as for the body and response schemas of a route, like your example. All of these schemas can be easily added to then server/openAPI spec for the sake of documentation, and the boilerplate isn't awful.

```ts
import { Elysia, t } from "elysia";

const otpToken = t.Object({
    otpToken: t.String({
        format: 'uuid',
        examples: '550e8400-e29b-41d4-a716-446655440000',
    })
});

const otpTokenBody = t.Composite([
    otpToken,
    t.Object({
        username: t.String()
    })
]);

const otpTokenResponse = t.Composite([
    otpToken,
    t.Object({
        somethingElse: t.String()
    })
]);

const app = new Elysia()
    .model({
        otpToken,
        otpTokenBody,
        otpTokenResponse
    })
    .post('/api/otp/token', (context) => {

        throw new Error('Not implemented');
    }, {
        request: "otpTokenBody",
        response: "otpTokenResponse"
    });
```

**Comment by kravetsone** [comment]
> ### What is the problem this feature would solve?
> The documentation at https://elysiajs.com/validation/reference-model.html states that reference models can be defined to create reusable models. Currently it is only possible to type the entire body, query or response, but individual fields can not reference such a model.
> 
> For us it is much more common than not the entire body or response is identical, but rather we want to reuse fields inside more complex definition in multiple places.
> 
> ```ts
> const app = new Elysia()
> .model("otpToken",t.String({
>   format: 'uuid',
>   examples: '550e8400-e29b-41d4-a716-446655440000',
> })).post("/url", () => {
> 
> }, {
>   body: t.Object({
>     otpToken: 'otpToken',
>     username: t.String()
>   })
> })
> ```
> 
> ### What is the feature you are proposing to solve the problem?
> Allow to register individual fields as models.
> 
> ### What alternatives have you considered?
> You can export partial typebox schemas into a field and use these instead. This has the disadvantage of those schemas not being proberly showing up as reusable schemas inside the openapi spec.

I guess this cannot be implemented in the type system (TypeScript limitation) with typebox, so it doesn't make much sense

**Comment by SaltyAom** [comment]
It might be possible to implement this feature **but** with a huge compromise and typescript limitation.

We recommended using model remap instead:
```ts
new Elysia()
  .model("otpToken",t.String({
    format: 'uuid',
    examples: '550e8400-e29b-41d4-a716-446655440000',
  }))
  .model((model) => ({
    ...model,
    a: t.Object({
      otpToken: model.otpToken,
      username: t.String()
    })
  }))
```
