### ISSUE TITLE
Payload validation should respect readOnly/writeOnly

### ISSUE THREAD

**Issue by Mudbill** [elysiajs/elysia#477]
### What version of Elysia.JS is running?

0.8.16 (not sure what this `Elysia --revision` command is)

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

Create an endpoint with a `body` and `response` schema that includes a `readOnly` and a `writeOnly` property. If you attempt to send in a body without the field specified as `readOnly`, Elysia will throw a validation error. Similarly, if you try to respond with a value that lacks the `writeOnly` field it will also throw.

Example code (for input):

```ts
app.post("/", () => "Hello", {
  body: t.Object({
    readOnlyProperty: t.Integer({ readOnly: true }),
    normalProperty: t.Integer()
  })
});
```

In this scenario, it should be possible to send a POST request with only `{ "normalProperty": 5 }` as input, however Elysia complains that `readOnlyProperty` is missing.

### What is the expected behavior?

Because Swagger excludes `readOnly` properties from the suggested input body payload, Elysia should also allow these to be absent. Same applies to `writeOnly` properties in the output response.

### What do you see instead?

Currently Elysia throws a validation error if a property from the schema is missing in the input body, even if it is marked as `readOnly`.

**Comment by SaltyAom** [comment]
> In this scenario, it should be possible to send a POST request with only { "normalProperty": 5 } as input, however Elysia complains that readOnlyProperty is missing.

I may unable to understand this correctly, but personally I think this doesn't make sense since `readOnlyProperty` is not defined as Integer, how does `readOnly: true` make it able to be null or undefined?

If I don't understand this correctly, feel free to correct me. Closing as not going to implemented.
