### ISSUE TITLE
Import named 'TypeCompiler' not found

### ISSUE THREAD

**Issue by HybridFox** [elysiajs/elysia#49]
I created a project using `bun create elysia hi-elysia`

Whenever I try to run bun with `bun run --hot src/index.ts` I receive the following error:
```SyntaxError: Import named 'TypeCompiler' not found in module '/.../node_modules/@sinclair/typebox/compiler/index.js'.```

If I omit the --hot or --watch option the server starts normally.
Thanks for any help in advance!

**Comment by luis-seedata-io** [comment]
+1

**Comment by luis-seedata-io** [comment]
+1

**Comment by luishdosreis** [comment]
+1

**Comment by SaltyAom** [comment]
You can try downgrading to Bun 0.6.4 to see if it is fixed:
```bash
curl https://bun.sh/install | bash -s -- bun-v0.6.4
```

Otherwise, what version of Bun, and Elysia are you using that occurs the bug, and which OS are you using.

**Comment by HybridFox** [comment]
Indeed, it works on bun v0.6.4
I was running bun v0.6.5, but it seems like v0.6.6 released recently which has fixed the issue.
Platform was `darwin-aarch64`

**Comment by Northernside** [comment]
Hey there,
I'm also experiencing this issue on bun 0.6.12. My server is running on Debian 11.
@SaltyAom

**Comment by Northernside** [comment]
@SaltyAom anything new? 👀

**Comment by SaltyAom** [comment]
@Northernside, hi sorry for the late response.

May I ask some more questions that should help me with this further?

- What's the version of Bun are you using? (I assume it's 0.7.0 but not sure if it's a stable or canary)
- How are you running dev server
- What Elysia version are you using 
- What Linux kernel version are you using? and is it WSL2, Docker environment, or native Linux
- Are you using dynamic linking in any chance? or any other beside glibc (If you're not sure, then probably no)
- Also can I have the code that cause this error

**Comment by Northernside** [comment]
@SaltyAom don't worry!

- Bun stable 0.7.0
- With `bun file.mjs`
- elysia@latest (0.5.24)
- Linux 5.10.0-22-cloud-amd64 x86_64 (native)
- I don't know about that, so nope.
- https://paste.laby.net/ugebuqiqul.js

<img width="1180" alt="image" src="https://github.com/elysiajs/elysia/assets/60970791/d9fe35a5-edcb-4152-9bf7-16435841fcbe">

**Comment by Northernside** [comment]
// This was fixxed in bun 0.7.1
