### ISSUE TITLE
The onResponse hook runs multiple times when the plugin uses async/await during registration.

### ISSUE THREAD

**Issue by ErikPham** [elysiajs/elysia#492]
### What version of Elysia.JS is running?

0.8.17

### What platform is your computer?

Darwin 22.6.0 x86_64 i386

### What steps can reproduce the bug?

I have 3 TypeScript files: plugin1.ts, plugin2.ts, index.ts. And I run the command: **bun dev**.

**plugin1.ts**
```
import {Elysia} from "elysia";

const delay = (timeout: number) => new Promise((resolve) => setTimeout(resolve, timeout));

const plugin1 = async (app: Elysia) => {
    await delay(1000);
    app
        .derive(() => { test: false })
        .onResponse(() => {
            console.log("Response sent");
        });
    return app;
}

export default plugin1
```

**plugin2.ts**
```
import {Elysia} from "elysia";

const delay = (timeout: number) => new Promise((resolve) => setTimeout(resolve, timeout));

const plugin2 = async (app: Elysia) => {
    await delay(2000);
    app
        .derive(() => { test2: true });
    return app;
}

export default plugin2
```

**index.ts**
```
import { Elysia } from "elysia";
import plugin1  from "./plugin1";
import plugin2  from "./plugin2";
const app = new Elysia()
    .use(plugin1)
    .use(plugin2)
    .get("/", () => "Hello Elysia")
    .listen(3000);

console.log(
    `🦊 Elysia is running at ${app.server?.hostname}:${app.server?.port}`
);
```

### What is the expected behavior?

I want the **onResponse** hook to be executed only once when the response.

### What do you see instead?

The **onResponse** hook is being triggered twice, and '**Response sent**' appears twice in the terminal.
<img width="504" alt="Screenshot 2024-02-19 at 15 52 09" src="https://github.com/elysiajs/elysia/assets/2884378/ecbd83d3-9f63-4c23-83dd-c01df93f1443">

**Comment by jambonn** [comment]
I encountered, too.

**Comment by PandaWorker** [comment]
two sync  - 2 hooks
```ts
const app = new Elysia()
	.state('counter', 0)
	.use((app) => {
		app.onResponse(({ store }) =>
			console.log(`onResponse: ${store.counter++}`)
		);
		return app;
	})
	.use((app) => {
		app.onResponse(({ store }) =>
			console.log(`onResponse: ${store.counter++}`)
		);
		return app;
	})
	.get('/', () => `hello`);
await app.modules;

const hooks = app.routes[0].hooks;

console.log(`onResponse hooks: `, hooks?.onResponse?.length); // 2
```

one async plugin - 2 hooks
```ts
const app = new Elysia()
	.state('counter', 0)
	.use(async (app) => {
		app.onResponse(({ store }) =>
			console.log(`onResponse: ${store.counter++}`)
		);
		return app;
	})
	.get('/', () => `hello`);
await app.modules;

const hooks = app.routes[0].hooks;

console.log(`onResponse hooks: `, hooks?.onResponse?.length); // 2
```

two async plugins - 6 hooks
```ts
const app = new Elysia()
	.state('counter', 0)
	.use(async (app) => {
		app.onResponse(({ store }) =>
			console.log(`onResponse: ${store.counter++}`)
		);
		return app;
	})
        .use(async (app) => {
		app.onResponse(({ store }) =>
			console.log(`onResponse: ${store.counter++}`)
		);
		return app;
	})
	.get('/', () => `hello`);
await app.modules;

const hooks = app.routes[0].hooks;

console.log(`onResponse hooks: `, hooks?.onResponse?.length); // 6
```

three async plugins - 12 hooks
```ts
const app = new Elysia()
	.state('counter', 0)
	.use(async (app) => {
		app.onResponse(({ store }) =>
			console.log(`onResponse: ${store.counter++}`)
		);
		return app;
	})
        .use(async (app) => {
		app.onResponse(({ store }) =>
			console.log(`onResponse: ${store.counter++}`)
		);
		return app;
	})
        .use(async (app) => {
		app.onResponse(({ store }) =>
			console.log(`onResponse: ${store.counter++}`)
		);
		return app;
	})
	.get('/', () => `hello`);
await app.modules;

const hooks = app.routes[0].hooks;

console.log(`onResponse hooks: `, hooks?.onResponse?.length); // 12
```

**Comment by PandaWorker** [comment]
Solution to the problem: for asynchronous plugins you need to use a new Elysia instance and add a wait if the following handlers depend on the plugin

sample
```ts
const pligin1 = async () => {
	const plugin = new Elysia();

	await Bun.sleep(1000);

	plugin.onResponse(() => console.log('onResponse'));

	return plugin;
};

// or
const pligin2 = async () => {
	const plugin = new Elysia();

	await Bun.sleep(1000);
    
        plugin.onBeforeHandle(() => console.log('onBeforeHandle'));
	plugin.derive(() => ({ test2: true }));

	return (app: Elysia) => app.use(plugin);
};

const app = new Elysia()
	.use(await pligin1())
	.use(await pligin2())
	.get('/', () => 'hello')
	.post('/', () => `h`)
	.listen(3000);
```



> ### What version of Elysia.JS is running?
> 0.8.17
> 
> ### What platform is your computer?
> Darwin 22.6.0 x86_64 i386
> 
> ### What steps can reproduce the bug?
> I have 3 TypeScript files: plugin1.ts, plugin2.ts, index.ts. And I run the command: **bun dev**.
> 
> **plugin1.ts**
> 
> ```
> import {Elysia} from "elysia";
> 
> const delay = (timeout: number) => new Promise((resolve) => setTimeout(resolve, timeout));
> 
> const plugin1 = async (app: Elysia) => {
>     await delay(1000);
>     app
>         .derive(() => { test: false })
>         .onResponse(() => {
>             console.log("Response sent");
>         });
>     return app;
> }
> 
> export default plugin1
> ```
> 
> **plugin2.ts**
> 
> ```
> import {Elysia} from "elysia";
> 
> const delay = (timeout: number) => new Promise((resolve) => setTimeout(resolve, timeout));
> 
> const plugin2 = async (app: Elysia) => {
>     await delay(2000);
>     app
>         .derive(() => { test2: true });
>     return app;
> }
> 
> export default plugin2
> ```
> 
> **index.ts**
> 
> ```
> import { Elysia } from "elysia";
> import plugin1  from "./plugin1";
> import plugin2  from "./plugin2";
> const app = new Elysia()
>     .use(plugin1)
>     .use(plugin2)
>     .get("/", () => "Hello Elysia")
>     .listen(3000);
> 
> console.log(
>     `🦊 Elysia is running at ${app.server?.hostname}:${app.server?.port}`
> );
> ```
> 
> ### What is the expected behavior?
> I want the **onResponse** hook to be executed only once when the response.
> 
> ### What do you see instead?
> The **onResponse** hook is being triggered twice, and '**Response sent**' appears twice in the terminal. <img alt="Screenshot 2024-02-19 at 15 52 09" width="504" src="https://private-user-images.githubusercontent.com/2884378/305886382-ecbd83d3-9f63-4c23-83dd-c01df93f1443.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNzI4NjgsIm5iZiI6MTcwODM3MjU2OCwicGF0aCI6Ii8yODg0Mzc4LzMwNTg4NjM4Mi1lY2JkODNkMy05ZjYzLTRjMjMtODNkZC1jMDFkZjkzZjE0NDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTlUMTk1NjA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzZhMGEwMTI5NWIzMDgxMDBmODVhOGZkOGQyNGM2ZjI0ZDQ4NWM5OGNhZjdiNDQyYjgwY2VhNDdkZTA0MGYwNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.VmvwW95_sPV6szpNFG_tDU6d5KrQVlD0ZrGCLn48zHM">
> 
> ### Additional information
> _No response_

**Comment by ErikPham** [comment]
@PandaWorker I tried and it doesn't work with derive. Every dervive I registered was undefined. It seems use doesn't seem to work

<img width="645" alt="image" src="https://github.com/elysiajs/elysia/assets/2884378/7b6d2574-d6bf-47c3-8c93-6661c9818b9e">
<img width="743" alt="image" src="https://github.com/elysiajs/elysia/assets/2884378/f72ba520-de56-4499-acd1-9213cfa4bb51">

**Comment by PandaWorker** [comment]
@ErikPham need to call the function
