### ISSUE TITLE
Add official plugin for vite/vike or Express Connect

### ISSUE THREAD

**Issue by SelfhostedPro** [elysiajs/elysia#494]
### What is the problem this feature would solve?

I don't see a good way to have Elysia and a frontend framework live together easily in a single repo (similar to nuxt) which would improve developer dx significantly for fullstack applications.

### What is the feature you are proposing to solve the problem?

I would love to see an officially supported plugin for [vite/vike](https://vike.dev/) as the [one](https://github.com/timnghg/elysia-vite-plugin-ssr) mentioned in your blog hasn't been updated in 7 months. I think it could attract attention and developers to your framework.

### What alternatives have you considered?

I'm working on getting my own repo to work with vike already but a boilerplate/plugin would save a lot of time.

An official way to use express middleware would be a more widely applicable/utilized functionality if vite is too specific.

**Comment by SelfhostedPro** [comment]
Closing in favor of https://github.com/elysiajs/elysia/issues/494

**Comment by rtritto** [comment]
@SelfhostedPro actually, there is a maintained plugin?
My use case with _vike_ is with Solid + SSR.

**Comment by kravetsone** [comment]
> @SelfhostedPro actually, there is a maintained plugin for SSR support?
> 
> FYI @kravetsone @SaltyAom

For vike?

I want to make it but for now - no

U can craft it with elysia-vite-server i guess

Elysia-remix is a good example

**Comment by SelfhostedPro** [comment]
Sorry, had multiple tabs open. Meant this: https://github.com/kravetsone/elysia-vite-server

There's a good example there for ssr with vue. The plugin for connect middleware may work for vike if that doesn't.

**Comment by rtritto** [comment]
Found [vike-node](https://github.com/vikejs/vike-node) (officially maintained by **vike**) that supports _Elysia_:

```ts
// server/index.js

import { Elysia } from 'elysia'
import vike from 'vike-node/elysia'

startServer()

function startServer() {
  const app = new Elysia()
  app.use(vike())
  const port = +(process.env.PORT || 3000)
  app.listen(port, () => console.log(`Server running at http://localhost:${port}`))
}
```
