### ISSUE TITLE
Add ability to use Connect middleware

### ISSUE THREAD

**Issue by eagerestwolf** [elysiajs/elysia#497]
### What is the problem this feature would solve?

There's already a ton of great middleware out there designed for Connect frameworks (Express, Koa, Hapi, etc.) that would be nice to use with Elysia. A prime example that comes to mind is [Passport.js](https://www.passportjs.org/). While many plugins can be replaced, or substituted ([Helmet](https://helmetjs.github.io/) comes to mind), some are just so deeply intertwined with Connect that it would be impossible to port them over.

### What is the feature you are proposing to solve the problem?

Obviously adding a full blown Connect interface into the Elysia core simply doesn't make sense. One of the things that makes Bun and Elysia so great compared to the status quo is that much of the overhead has been reduced. However, I do think that an official plugin to translate Connect middleware into something Elysia can understand (much like [Fastify](https://github.com/fastify/fastify-express) has already done) would be amazing.

### What alternatives have you considered?

I have looked into the possibility of porting Passport over to Elysia, but that isn't feasible. Getting Passport itself working likely wouldn't be an issue, but many strategies wouldn't work on my modified version. I am also aware of the Lucia integration, but Lucia is just a bit too limited for what I am after (it's missing 2FA and WebAuthn support, which Passport has). Furthermore, I could look into creating my own Connect translation layer (and I may still yet do that), but I don't really have a ton of time to dedicate to the project; and I lack a lot of knowledge about the internal workings of Elysia (granted that could be solved by diving head-first into the source code *shudders*).

**Comment by kravetsone** [comment]
> (it's missing 2FA and WebAuthn support, which Passport has)

Maybe you can talk about this topic with the author of Lucia? Passport.JS is already outdated in my opinion...

But it would be great to do something like [fastify-express](https://github.com/fastify/fastify-express). It would be a great marketing move!

**Comment by SelfhostedPro** [comment]
It would also greatly expand the current ecosystem since you could then utilize most express middleware.

**Comment by kravetsone** [comment]
> It would also greatly expand the current ecosystem since you could then utilize most express middleware.

But I still think it's more of an evil thing...

**Comment by SelfhostedPro** [comment]
I mean, if you're going through the effort of building it, I wouldn't intentionally make it hard to use. Just state that there's minimal/no support if avoiding support getting overloaded is a worry.

**Comment by kravetsone** [comment]
> ### What is the problem this feature would solve?
> There's already a ton of great middleware out there designed for Connect frameworks (Express, Koa, Hapi, etc.) that would be nice to use with Elysia. A prime example that comes to mind is [Passport.js](https://www.passportjs.org/). While many plugins can be replaced, or substituted ([Helmet](https://helmetjs.github.io/) comes to mind), some are just so deeply intertwined with Connect that it would be impossible to port them over.
> 
> ### What is the feature you are proposing to solve the problem?
> Obviously adding a full blown Connect interface into the Elysia core simply doesn't make sense. One of the things that makes Bun and Elysia so great compared to the status quo is that much of the overhead has been reduced. However, I do think that an official plugin to translate Connect middleware into something Elysia can understand (much like [Fastify](https://github.com/fastify/fastify-express) has already done) would be amazing.
> 
> ### What alternatives have you considered?
> I have looked into the possibility of porting Passport over to Elysia, but that isn't feasible. Getting Passport itself working likely wouldn't be an issue, but many strategies wouldn't work on my modified version. I am also aware of the Lucia integration, but Lucia is just a bit too limited for what I am after (it's missing 2FA and WebAuthn support, which Passport has). Furthermore, I could look into creating my own Connect translation layer (and I may still yet do that), but I don't really have a ton of time to dedicate to the project; and I lack a lot of knowledge about the internal workings of Elysia (granted that could be solved by diving head-first into the source code _shudders_).

I create plugin for it

[elysia-connect-middleware](https://github.com/kravetsone/elysia-connect-middleware)

Can you open an issue if something need to test&support?

**Comment by kravetsone** [comment]
But for now it really WIP

**Comment by kravetsone** [comment]
![image](https://github.com/user-attachments/assets/33a6bbfd-5994-46be-9067-5dd99ceaf24a)

PassportJS works too!

**Comment by kravetsone** [comment]
I guess we can close it

if something not working properly you can open an issue in [elysia-connect-middleware repo](https://github.com/kravetsone/elysia-connect-middleware)

**Comment by SaltyAom** [comment]
Closing as not planned and not going to implement on Elysia core. I'd recommended using a third party library instead as mentioned by kravetsone. Thanks.
