### ISSUE TITLE
Improve ESM support through CommonJS

### ISSUE THREAD

**Issue by bogeychan** [elysiajs/elysia#50]
At the moment it is not possible to import CommonJS into ESM because the [exports](https://github.com/elysiajs/elysia/blob/a2c34f8095377ab7b50c9c3be33f24c303247bd3/package.json#L11) defined in `package.json` (of all projects) are sorted incorrectly.

---

Example: (run with `node main.js`)
```js
// main.js
import Elysia from 'elysia';

new Elysia.Elysia();
```

Error: (yes, i've `"type": "module"` in my `package.json`)

```bash
SyntaxError: Cannot use import statement outside a module
```

---

The sorting is important. `Node.js` & `Deno` apparently check from top to bottom. This means that if it is ESM-context, `import` is used instead of `require` or `node`.

Therefore `node` must move further up and point to CommonJS (in all `exports`):

```diff
{
  "bun": "./dist/index.js",
+ "node": "./dist/cjs/index.js"
  "require": "./dist/cjs/index.js",
  "import": "./dist/index.js",
  "default": "./dist/index.js",
- "node": "./dist/index.js"
}
```

Furthermore, type or runtime errors occur when CommonJS is imported into ESM, because `SWC` breaks named exports for ESM in CommonJS build (i.e. `module.exports`):

❌ SWC

```js
(function (e, t) {
  for (var r in t) Object.defineProperty(e, r, { enumerable: !0, get: t[r] });
})(exports, {
  Elysia: function () {
    return h;
  },
  default: function () {
    return u;
  }
});
```

Runtime Error
```bash
import { Elysia } from 'elysia';
         ^^^^^^
SyntaxError: Named export 'Elysia' not found. The requested module 'elysia' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'elysia';
const { Elysia } = pkg;
```

OR Type error
```js
import Elysia from 'elysia';

const app = new Elysia.Elysia() // Property 'Elysia' does not exist on type 'typeof Elysia'.ts(2339)
```

✅TSC (without SWC)
```js
exports.Elysia = Elysia;
exports.default = Elysia;
```

---

I can make (or help you with) the changes to `exports` in all `package.json`, but I don't know how you wanna handle `SWC`.

An alternative would be to drop CommonJS and only support ESM → `"moduleResolution": "nodenext"` & `"type": "module"` (i.e. specify all imports and exports with `.js` extension).  This would work for `Node.js` and `Deno` too.

**Comment by bogeychan** [comment]
For reference, I made basic adjustments in my fork: https://github.com/elysiajs/elysia/compare/main...bogeychan:elysia:main

Just run `bun run test:node`

**Comment by SaltyAom** [comment]
We will be using `tsc` to compile CommonJS to support `module.exports` syntax instead.

Should be released on 0.5.14 with this commit https://github.com/elysiajs/elysia/commit/69a130d33e640d286f2c94ec711f6b567d166fd3

**Comment by bogeychan** [comment]
That should be all.

- Updating [memoirist](https://github.com/saltyaom/memoirist) is not necessary as it is imported from CommonJS, so [require](https://github.com/SaltyAom/memoirist/blob/4d1dc719c7df6365365338d28ec3eeeb6dcbf7b0/package.json#L12) is used anyway
- I could not update [@elysiajs/websocket](https://github.com/elysiajs/elysia-websocket) because there are a bunch of type errors when upgrading `Elysia.js` to `0.5.12`

**Comment by SaltyAom** [comment]
For @elysiajs/websocket is migrated to the core package via `elysia/ws`, so no need to update the package.

That should be all for CommonJS, so I'm closing the issue.
