### ISSUE TITLE
1.0.0-rc.0 server timing breaks beforeHandle guards

### ISSUE THREAD

**Issue by MatthewAry** [elysiajs/elysia#516]
### What version of Elysia.JS is running?

1.0.0-rc.0

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

Please see my reproduction https://github.com/MatthewAry/elysia-reproductions/tree/serverTiming-Breaks-Guards

Simply put, you just add server timing right after you create the root Elysia object and then you create a route that is protected by a guard via a beforeHandle hook.

### What is the expected behavior?

It's expected that the server will respond with the message returned by the beforeHandle hook if the necessary conditions are met.

### What do you see instead?

When running in dev mode via `bun run --inspect --watch src/index.ts` rejected requests will hang.
When running in prod via `NODE_ENV=production bun src/index.ts` it works as expected.

**Comment by SaltyAom** [comment]
Should be fixed in [3572bdf](https://github.com/elysiajs/elysia/commit/3572bdfd1189f3ccd07c3eda054792ffa15faeef), published on `1.0.0-rc.2`.

Let me know if it works or not.

**Comment by MatthewAry** [comment]
On my reproduction the issue seems to be fixed. On my application however it seems to not be resolved. It feels like I need to reproduce more of my application to figure out why. I have multiple layers of guards and context loading as permissions get more strict.
- Is Authenticated
- User Context (DB call to get user data) (Async)
- Feature Flags (Async)
- CORS with regex

Also I deleted node_modules, the lockfile, and then reinstalled to make sure there wasn't something else going on. I'll try to work on another reproduction when I have the time, for now, I still have server timing commented out.

**Comment by iscekic** [comment]
Faced a similar issue

```
new Elysia()
  .use(serverTiming())
  .use(
    pluginGracefulServer({
      serverIsReadyOnStart: true,
    }),
  )
  .use(gql)
  .listen(env.port);
```

```
new Elysia()
  .onBeforeHandle(rateLimit(300, 10))
  .resolve(async ({ request }) => {
    try {
      const uid = await getUid(request);

      return { uid };
    } catch {
      return { uid: null };
    }
  })
  .post(
    "/gql",
    ({ body, set, uid }) => {
      // ...
    }
  );
```

I fixed it by changing `resolve` to `derive`

**Comment by SaltyAom** [comment]
Closing as no reproducible example code and inactivity, feel free to reopen the issue if anything update.
