### ISSUE TITLE
Elysia WebSocket API TypeScript Error: "Type instantiation is excessively deep and possibly infinite"

### ISSUE THREAD

**Issue by bigbeno37** [elysiajs/elysia#52]
I created a new Elysia app using `bun create elysia elysia-app`, and when I go to add WebSocket support:

```ts
import { Elysia, ws } from "elysia";

const app = new Elysia()
	.use(ws())
	.ws('/ws', {
		message(ws) {
			console.log('New ws message!');
		}
	})
	.listen(3000);

console.log(
  `🦊 Elysia is running at ${app.server?.hostname}:${app.server?.port}`
);
```

I get the following error message that wraps from `new Elysia()` to before `.listen(3000)`:

```
TS2589: Type instantiation is excessively deep and possibly infinite.
```

**Comment by bogeychan** [comment]
I could not reproduce it on my end.

Can you please provide your bun and dependency versions by running:

- bun version: `bun --version`
- dependencies: `bun pm ls` (inside your project's root)

I'm using `bun v0.6.7` and:
```bashj
├── bun-types@0.6.8
└── elysia@0.5.17
```

**Comment by bigbeno37** [comment]
`bun --version` is `0.6.8`, and `bun pm ls` outputs:
```
├── bun-types@0.6.8
├── elysia@0.5.17
└── typescript@5.1.3
```

I should clarify I added TypeScript so I can run `tsc` to check for type errors.

**Comment by bogeychan** [comment]
That makes sense, it doesn't work for me with `tsc` either.
You can add the following line to disable the type error for now:

```ts
// @ts-ignore
const app = new Elysia()
```

@SaltyAom, the root cause seems to be here:

https://github.com/elysiajs/elysia/blob/3134e9e56bd5e2503ebf1bc260f744d6280788e5/src/ws/types.ts#L143-L147

Any idea how to fix it?

**Comment by SaltyAom** [comment]
I'm sorry for not getting back to you sooner.

This issue is somewhat hard to solve, but it should get better in Elysia 0.5.19, try update to see if the issue gets better.

**Comment by bigbeno37** [comment]
0.5.19 fixed the issue. Thank you!
