### ISSUE TITLE
Swagger Adaptation Issue: Incorrect Response Examples Display

### ISSUE THREAD

**Issue by Mikey-ShenSu** [elysiajs/elysia#523]
### What platform is your computer?

Darwin 23.3.0 arm64 arm

### What steps can reproduce the bug?

When following the OpenAPI Specification (OAS) rules, Swagger displays additional ```{value:{}}``` for response examples, as shown in the provided images. To properly display examples in Swagger, modifications are required as indicated in the additional images. However, making these changes leads to a TypeScript type assignment error, which is detailed in the provided error message.

![image](https://github.com/elysiajs/elysia/assets/153639584/c22840bc-00f5-4239-8f6f-db8d0411103a)

![image](https://github.com/elysiajs/elysia/assets/153639584/ade4e0e6-7d9f-4fd0-942b-4321d75f2d8e)

To properly display in /swagger, I have to:

![image](https://github.com/elysiajs/elysia/assets/153639584/10f54163-4884-4d83-a4b1-85aa3aa923ad)
![image](https://github.com/elysiajs/elysia/assets/153639584/f7174180-472c-4b5c-ba06-39cf61945900)

If so, I will be getting the problem:
```
Type '{ "200": { description: string; content: { "application/json": { examples: { 用户验证成功: { code: string; message: string; status: number; }; 用户登录成功: { value: { code: string; message: string; status: number; }; }; }; }; }; }; "422": { ...; }; "500": { ...; }; }' is not assignable to type '{ "200": { description: string; content: { "application/json": { examples: { 用户验证成功: { code: string; message: string; status: number; }; 用户登录成功: { value: { code: string; message: string; status: number; }; }; }; }; }; }; "422": { ...; }; "500": { ...; }; } & ResponsesObject'.
  Type '{ "200": { description: string; content: { "application/json": { examples: { 用户验证成功: { code: string; message: string; status: number; }; 用户登录成功: { value: { code: string; message: string; status: number; }; }; }; }; }; }; "422": { ...; }; "500": { ...; }; }' is not assignable to type 'ResponsesObject'.
    Property '"200"' is incompatible with index signature.
      Type '{ description: string; content: { "application/json": { examples: { 用户验证成功: { code: string; message: string; status: number; }; 用户登录成功: { value: { code: string; message: string; status: number; }; }; }; }; }; }' is not assignable to type 'ReferenceObject | ResponseObject'.
        Type '{ description: string; content: { "application/json": { examples: { 用户验证成功: { code: string; message: string; status: number; }; 用户登录成功: { value: { code: string; message: string; status: number; }; }; }; }; }; }' is not assignable to type 'ResponseObject'.
          Types of property 'content' are incompatible.
            Type '{ "application/json": { examples: { 用户验证成功: { code: string; message: string; status: number; }; 用户登录成功: { value: { code: string; message: string; status: number; }; }; }; }; }' is not assignable to type '{ [media: string]: MediaTypeObject; }'.
              Property '"application/json"' is incompatible with index signature.
                Type '{ examples: { 用户验证成功: { code: string; message: string; status: number; }; 用户登录成功: { value: { code: string; message: string; status: number; }; }; }; }' is not assignable to type 'MediaTypeObject'.
                  Types of property 'examples' are incompatible.
                    Type '{ 用户验证成功: { code: string; message: string; status: number; }; 用户登录成功: { value: { code: string; message: string; status: number; }; }; }' is not assignable to type '{ [media: string]: ReferenceObject | ExampleObject; }'.
                      Property '"用户验证成功"' is incompatible with index signature.
                        Type '{ code: string; message: string; status: number; }' is not assignable to type 'ReferenceObject | ExampleObject'.ts(2322)
auth.controller.ts(204, 21): The expected type comes from property 'responses' which is declared here on type '{ summary: string; description: string; tags: string[]; responses: { "200": { description: string; content: { "application/json": { examples: { 用户验证成功: { code: string; message: string; status: number; }; 用户登录成功: { ...; }; }; }; }; }; "422": { ...; }; "500": { ...; }; }; } & Partial<...>'
```

### What is the expected behavior?

```
{
  "code": "verifyCode.Verified",
  "message": "用户验证成功！",
  "status": 200
}
```

### What do you see instead?

```
{
  "value": {
    "code": "verifyCode.Verified",
    "message": "用户验证成功！",
    "status": 200
  }
}
```

**Comment by Mikey-ShenSu** [comment]
Such Issue would not happen, If I change the provider from default ("scalar") to "swagger-ui".

```
.use(swagger(
    {
      provider: "swagger-ui"
    }
  ))
```

![image](https://github.com/elysiajs/elysia/assets/153639584/2d47e5df-5499-404a-8f1c-e78f540d45bc)

**Comment by kravetsone** [comment]
> Such Issue would not happen, If I change the provider from default ("scalar") to "swagger-ui".
> 
> ```
> .use(swagger(
>     {
>       provider: "swagger-ui"
>     }
>   ))
> ```
> 
> ![image](https://github.com/elysiajs/elysia/assets/153639584/2d47e5df-5499-404a-8f1c-e78f540d45bc)
> 
> 



Can you create issue in [Scalar repo](https://github.com/scalar/scalar)?

**Comment by Mikey-ShenSu** [comment]
> > Such Issue would not happen, If I change the provider from default ("scalar") to "swagger-ui".
> > ```
> > .use(swagger(
> >     {
> >       provider: "swagger-ui"
> >     }
> >   ))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://private-user-images.githubusercontent.com/153639584/311410337-2d47e5df-5499-404a-8f1c-e78f540d45bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxMjE3MDksIm5iZiI6MTcxMDEyMTQwOSwicGF0aCI6Ii8xNTM2Mzk1ODQvMzExNDEwMzM3LTJkNDdlNWRmLTU0OTktNDA0YS04ZjFjLWU3OGY1NDBkNDViYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMVQwMTQzMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZGE3ODZlOWE5NDA2NzQ1NThjN2I0ZTEyMWZlZTVhZTI4NTIyNzY4NmJiMTNkZmE0ZTA1YWVjZDljZjk0NWEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Of3actZdLBVAJhRxhXbcp7QzDKtlpv19JmghserbUK8)
> 
> Can you create issue in [Scalar repo](https://github.com/scalar/scalar)?

Sure, I have created the issue on Scalar.
