### ISSUE TITLE
Minor DX request: Allow passing an `edenTreaty` value without a trailing slash

### ISSUE THREAD

**Issue by EvHaus** [elysiajs/elysia#526]
### What is the problem this feature would solve?

Currently, when you use `edenTreaty` you must pass in a URL that ends with a trailing slash, otherwise requests will fail with:

```
Cannot read properties of undefined (reading 'endsWith')
```

It would be nice if you didn't need to do this and Elysia could automatically append a trailing slash if its missing. It took me a while to figure out why I was getting that error message.

### What is the feature you are proposing to solve the problem?

Currently you must do:

```ts
import { edenTreaty } from '@elysiajs/eden';
import type { App } from 'backend';

const api = edenTreaty<App>(`${process.env.MY_API_URL}/`);
```

It would be nice to just do:

```ts
import { edenTreaty } from '@elysiajs/eden';
import type { App } from 'backend';

const api = edenTreaty<App>(process.env.MY_API_URL);
```

**Comment by cybercoder-naj** [comment]
I've used `edenTreaty` when testing my server (look [here](https://github.com/cybercoder-naj/wordle-clone/blob/main/test/auth.test.ts#L5)) and I didn't require a trailing forward-slash to run my tests. After scavenging the code, I believe the error originates in [this line](https://github.com/elysiajs/eden/blob/f936e007f51a4ff51e62d03bbfc410b9e784799e/src/treaty/utils.ts#L6) but I am unsure why `domain` is undefined.

Can you check your version numbers and environment to narrow the problem?

**Comment by EvHaus** [comment]
Cannot reproduce this anymore after upgrading to:

- @elysiajs/eden: 1.0.0-rc.5
- elysia: 1.0.0-rc.16
