### ISSUE TITLE
NOT_FOUND Error thrown by default

### ISSUE THREAD

**Issue by iamswat** [elysiajs/elysia#533]
### What version of Elysia.JS is running?

0.8.17 and tested on 1.0.0-rc.16

### What platform is your computer?

m1 mac

### What steps can reproduce the bug?

`
use 
elysia.onError(({code, error})=>{
    console.log(error)
});
`

### What is the expected behavior?

The expected behaviour is by default, Elysia shouldn't throw random errors

### What do you see instead?

<img width="713" alt="Screenshot 2024-03-14 at 2 52 50 PM" src="https://github.com/elysiajs/elysia/assets/163091666/146a3d47-97e6-49fd-ba24-92feae6f7e64">

**Comment by iamswat** [comment]
The error was caught for 
http://localhost:3000/favicon.ico

**Comment by cholasimmons** [comment]
> The error was caught for http://localhost:3000/favicon.ico

Where must favicon.ico be placed to get rid of this error?

**Comment by luan-coelho** [comment]
Where should I place this favicon file?

**Comment by hasan-muzak** [comment]
Still occurs lol
