### ISSUE TITLE
Add 'global'/'local' to `model` function

### ISSUE THREAD

**Issue by cybercoder-naj** [elysiajs/elysia#538]
### What version of Elysia.JS is running?

1.0.0-rc.19

### What platform is your computer?

Linux 6.6.21-1-lts x86_64 unknown

### What steps can reproduce the bug?

In VSCode, create a model in a separate instance and use it on the main instance of Elysia.

```typescript
const userAuthModel = new Elysia()
  .model({
    'user.auth': t.Object({
      email: t.String({ format: 'email' }),
      password: t.String()
    })
  })

const app = new Elysia()
  .use(userAuthModel)
  // Typescript error at email and password:
  // Property "email" does not exist on type '{}'
  // Property "password" does not exist on type '{}'
  .post('login', ({ body: { email, password } }) => {
    // Handle login
  }, { body: 'user.auth' })
```

### What is the expected behavior?

Typescript should understand the model in use and type the body accordingly.

### What do you see instead?

![image](https://github.com/elysiajs/elysia/assets/48282810/af1d2899-4afe-4eb3-9335-a0f7817be18b)

### Additional information

When reverted the version to `v0.8.17`, this problem still persists.

**Comment by VaronLaStrauss** [comment]
Same problem with #545
