### ISSUE TITLE
Missing resolved properties on `onBeforeHandle` and models of a route.

### ISSUE THREAD

**Issue by VaronLaStrauss** [elysiajs/elysia#545]
### What version of Elysia.JS is running?

1.0.0

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

```typescript
import { Elysia, t } from "elysia";

const resolvedUser = new Elysia().resolve(() => {
  return { user: "I am a user" };
});

const model = new Elysia().model("somebody", t.String());

const app = new Elysia()
  .use(resolvedUser)
  .onBeforeHandle(
    { as: "local" },
    (
      // Property 'user' does not exist on type '{ body: unknown; query: Record<string, string | undefined>; ...
      { user },
    ) => {},
  )
  .get("/", () => {}, {
    // Type 'string' is not assignable to type 'TSchema'
    body: "somebody",
  });

```

### What is the expected behavior?

Same as with versions <=0.8, to be able to resolve types on hooks.

### What do you see instead?

No intellisense for hooks and models.

**Comment by SaltyAom** [comment]
See #513 

Since your resolve is local, it isn't inherited by the parent instance.

You need to add `{ as: 'global' }` to `resolve` to fix this.
```typescript
const resolvedUser = new Elysia().resolve({ as: 'global' }, () => {
  return { user: "I am a user" };
});
```

**Comment by kabir-asani** [comment]
> See #513
> 
> Since your resolve is local, it isn't inherited by the parent instance.
> 
> You need to add `{ as: 'global' }` to `resolve` to fix this.
> 
> ```ts
> const resolvedUser = new Elysia().resolve({ as: 'global' }, () => {
>   return { user: "I am a user" };
> });
> ```

This absolutely works! Thank you so much.
