### ISSUE TITLE
Exporting Elysia from file causes server to run twice

### ISSUE THREAD

**Issue by EvHaus** [elysiajs/elysia#550]
### What version of Elysia.JS is running?

1.0.0

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Create a basic Elysia server like this:

```ts
import { Elysia } from 'elysia';
const app = new Elysia()
  .get('/', () => 'Landing')
  .listen(8080)

console.log(
	`🦊 API is running at ${app.server?.hostname}:${app.server?.port}`,
);

export default app;
```

Then run the server via `bun index.ts`.

### What is the expected behavior?

Server should run with no errors.

### What do you see instead?

Server crashes with:

```
bun run index.ts
 6 |       if(typeof entryNamespace?.default?.fetch === 'function')  {
 7 |         Bun.serve(entryNamespace.default);
 8 |       }
 9 |    }, reportError);
10 | } else if (typeof entryNamespace?.default?.fetch === 'function') {
11 |    Bun.serve(entryNamespace.default);
     ^
EADDRINUSE: Failed to start server. Is port 8080 in use?
 syscall: "listen"

      at bun:main:11:4
```

The problem seems to be that doing `export default app` in Elysia 1.0.0 causes a separate `listen` call to be executed. 

Removing `export default app` makes the issue go away, but this means you can't import the file for the purpose of unit testing as shown [here](https://elysiajs.com/blog/elysia-10.html#treaty-2).

Removing `listen(8080)` also makes the issue go away, but causes `app.server` not to be defined, so the console message prints: `API is running at undefined:undefined` instead.

I can also remove `export default app` and change `const app = ...` to `export const app = ...` to fix this, and I suppose this is what you recommend to do, but this behavior was not expected (or documented) so I thought I'd log it.

**Comment by DobroslavR** [comment]
Why are you exporting it? If you need only type, you can do `export type API = typeof app` and it's gonna work.

**Comment by EvHaus** [comment]
I'm exporting it so I can pass it to `treaty` during tests.

```ts
import app from './';
import {treaty} from '@elysiajs/eden';

const api = treaty(app);
```

**Comment by kravetsone** [comment]
It's bun behaviour 

https://bun.sh/docs/api/http#object-syntax

**Comment by SaltyAom** [comment]
Close as not going to fix as it's Bun behavior, and changing this behavior would introduce large breaking change.

**Comment by EvHaus** [comment]
I put up a small PR to update the docs around this, which I hope will help those who are new to Elysia. I hope you'll consider adding it. https://github.com/elysiajs/documentation/pull/384
