### ISSUE TITLE
dyld: lazy symbol binding failed

### ISSUE THREAD

**Issue by mijburgh-beukes** [elysiajs/elysia#561]
### What version of Elysia.JS is running?

1.0.7

### What platform is your computer?

MacOS Version 10.15.7 Darwin 19.6.0 x86_64 i386

### What steps can reproduce the bug?

- Using bun 1.0.33
- Create a basic server in src/index.ts
```
import { Elysia } from "elysia";
const app = new Elysia().get("/", () => "Hello World!").listen(3000);
console.log(`Elysia is running at http://${app.server?.hostname}:${app.server?.port}`);
```
- Run `bun run index.ts`

### What is the expected behavior?

`Elysia is running at http://localhost:3000` in the console

### What do you see instead?

```
dyld: lazy symbol binding failed: Symbol not found: _pwritev$NOCANCEL
  Referenced from: /Users/{username}/.bun/bin/bun (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib
```

```
dyld: Symbol not found: _pwritev$NOCANCEL
  Referenced from: /Users/{username}/.bun/bin/bun (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib
```

### Additional information

Running
```
Bun.serve({
  port: 3000,
  fetch(request) {
  return new Response("Welcome to Bun!"); 
})
```
instead produces the expected console output, so not sure why Elysia isn't running as well...

**Comment by SaltyAom** [comment]
This seems like problem with Bun itself, not Elysia. Closing as not planned.

I'd recommended to open issue on Bun repo instead, thanks.
