### ISSUE TITLE
`decorate` type is not global

### ISSUE THREAD

**Issue by cybercoder-naj** [elysiajs/elysia#569]
### What version of Elysia.JS is running?

1.0.9

### What platform is your computer?

Linux 6.6.21-1-lts x86_64 unknown

### What steps can reproduce the bug?

The `decorate` function is not global, type-wise.

```typescript
const decoratePlug = new Elysia()
  .decorate("someVar", 3)
  .decorate("otherVar", 10)

const child = new Elysia()
  .get('/child', ({ otherVar }) => { // Error cannot find otherVar 
    return otherVar;
  })

const app = new Elysia()
  .use(decoratePlug)
  .use(child)
  .get('/', ({ someVar }) => {
    return someVar;
  })
```

### What is the expected behavior?

When there is an object defined with `decorate`, it should be available in Context for all child components also.

### What do you see instead?

![image](https://github.com/elysiajs/elysia/assets/48282810/61d4820b-b0c0-4884-87af-331205ab2439)

### Additional information

Although the types don't work, the application still runs with the correct behaviour.

![image](https://github.com/elysiajs/elysia/assets/48282810/212efe7e-9be2-4071-94d7-107ed7ea3831)

**Comment by Gerhardt0011** [comment]
@cybercoder-naj did you manage to sort this out? i'm struggling with a similar issue.

**Comment by cybercoder-naj** [comment]
This is shortcoming of Typescript itself and can't be fixed. [https://elysiajs.com/essential/plugin.html#service-locator](https://elysiajs.com/essential/plugin.html#service-locator)
