### ISSUE TITLE
add mapResponse support stream type

### ISSUE THREAD

**Issue by chakeawx** [elysiajs/elysia#587]
### What is the problem this feature would solve?

add type on mapResponse to support stream

`
  .mapResponse(({ response }) => {
    if (response instanceof Stream) {
      return response
    }
  })
`

### What is the feature you are proposing to solve the problem?

.

**Comment by SaltyAom** [comment]
Bun.serve expect as response to be Request to return a request to client and `mapResponse` is the mapper function to do just that.

If you want to return a stream, wrap a stream inside `new Request` or alternatively use generator function as introduce in 1.1 https://elysiajs.com/patterns/stream.html#stream
