### ISSUE TITLE
derive body is not parsed

### ISSUE THREAD

**Issue by yadsbah** [elysiajs/elysia#589]
### What steps can reproduce the bug?

Body is not parsed before derive. 
the body is String. 

```
export const doesBrandExistPlugin = (app: Elysia) => {
  return app.derive(
    {
      as: "scoped",
    },
    async ({ body }) => {
      const { id } = body;
      const brand = await db.brands.findFirst({
        where: {
          id,
        },
        include: {
          title: true,
        },
      });
      return {
        brand,
      };
    }
  );
};
```

**Comment by kidqueb** [comment]
You're probably looking for `resolve` which runs after route validation, but also from a typesafety perspective the plugin is unaware of any validation that had previously been defined.

To guarantee the body is validated with an id you can add a guard before calling `derive`

```typescript
function doesBrandExistPlugin(app: Elysia) {
  return app
    .guard({
      body: t.Object({ id: t.String() }),
    })
    .derive({ as: "global" }, ({ body }) => {
      body.id; // string
      return { YAY: true };
    });
}

const app = new Elysia()
  .use(doesBrandExistPlugin)
  .get('/', ({ YAY }) => {
    return YAY; // boolean
  })
```

**Comment by yadsbah** [comment]
> You're probably thinking more of `resolve` which runs after route validation, but also from a typesafety perspective the plugin is unaware of any validation that had previously been defined.
> 
> To guarantee the body is validated with an id you can add a guard before calling `derive`
> 
> ```ts
> function doesBrandExistPlugin(app: Elysia) {
>   return app
>     .guard({
>       body: t.Object({ id: t.String() }),
>     })
>     .derive({ as: "global" }, ({ body }) => {
>       body.id; // string
>       return { YAY: true };
>     });
> }
> 
> const app = new Elysia()
>   .use(doesBrandExistPlugin)
>   .get('/', ({ YAY }) => {
>     return YAY; // boolean
>   })
> ```

Using Guard fixed the problem. Thanks
