### ISSUE TITLE
Lacking route-specific middleware chain

### ISSUE THREAD

**Issue by hjb1694** [elysiajs/elysia#591]
### What is the problem this feature would solve?

I would like to see a solution where I can pass multiple handlers or middlewares to a specific route, being able to funnel the request through and prevent passage to subsequent handlers.

### What is the feature you are proposing to solve the problem?

I would like to be able to pass multiple handlers in an array, similar to Express. Maybe produce a function to create a new middleware chain, where the argument passed is an array of handlers, or provide the option to pass an array of handlers/middleware where a single handler is the only option at this time.

### What alternatives have you considered?

I have seen examples of custom middleware implementations that are framework agnostic, but I do question their robustness.

**Comment by phrynus** [comment]
Yes, manual middleware can make code inefficient and difficult to understand

**Comment by SaltyAom** [comment]
Technically we lifecycle can perform the same as middleware but just with a named or a point in time. So basically nothing stopping you from doing that as you can just pass an array to a specific lifecycle.

For example:
```ts
new Elysia()
	.get('/', () => 'a', {
		beforeHandle: [
			() => {
				console.log(1)
			},
			() => console.log(2)
		]
	})
```

Either way, you could also use https://elysiajs.com/patterns/macro.html#macro to achieve the same effect.

Closing as complete, and not going to implement.
