### ISSUE TITLE
Static File Not work

### ISSUE THREAD

**Issue by bobwatcherx** [elysiajs/elysia#6]
i followed the tutorial on this web https://elysiajs.com/plugins/static.html
and I also installed package @elysia/static and re-run .  why get an error like this @elysiajs/static
root@minto-Lenovo-V145-14AST:/home/minto/belajar/elysyaPro/elyapp/manelysia# bun run  dev

```
root@minto-Lenovo-V145-14AST:/home/minto/belajar/elysyaPro/elyapp/manelysia# bun run  dev

$ bun run --hot src/index.ts


error: Could not resolve: "@elysia/static". Maybe you need to "bun install"?

import { staticPlugin } from '@elysia/static'
                             ^
/home/minto/belajar/elysyaPro/elyapp/manelysia/src/index.ts:2:30 64error: script "dev" exited with code 1 (SIGHUP)
```

version
root@minto-Lenovo-V145-14AST:/home/minto/belajar/elysyaPro/elyapp/manelysia# bun --version
0.4.0

**Comment by izznatsir** [comment]
You should install @elysiajs/static package instead of @elysia/static.

**Comment by SaltyAom** [comment]
Closed as resolved, use `@elysiajs/static` instead of `@elysia/static`.
