### ISSUE TITLE
[bug] WebSocket validation error does not work correctly

### ISSUE THREAD

**Issue by TheRealSyler** [elysiajs/elysia#61]
When sending an invalid web socket message i got this error

```sh
error: send requires a non-empty message
      at message (/home/syler/github/socket-test/server/node_modules/elysia/dist/ws/index.js:1:1395)
CLOSE
OPEN
65 |       let s = e.data.transformMessage[r](t);
66 |       s !== void 0 && (t = s);
67 |     }
68 |     if (e.data.message?.Check(t) === !1)
69 | 
70 |       return void e.send(new r("message", e.data.message, t).cause);
```

The error is because `.cause` is `undefined` [here](https://github.com/elysiajs/elysia/blob/b5aa9ca0698a58652e6222897c3c866e755fb5a4/src/ws/index.ts#L186C9-L186C9), `ValidationError` does not have a cause because at some point you changed the code from [this](https://github.com/elysiajs/elysia/blob/d02fcf99657f12deb5ce88f80d9bd5784efed317/src/utils.ts#L112) to [this](https://github.com/elysiajs/elysia/blob/b5aa9ca0698a58652e6222897c3c866e755fb5a4/src/error.ts#L41), the fix is to change `.cause` to `.message` [here](https://github.com/elysiajs/elysia/blob/b5aa9ca0698a58652e6222897c3c866e755fb5a4/src/ws/index.ts#L186C9-L186C9)

**Comment by deadlinecode** [comment]
@SaltyAom 
+1 pls fix

**Comment by SaltyAom** [comment]
Should be fixed with the rewrite websocket introduced in 0.7.

Feels free to reopen if the issue still persists.
