### ISSUE TITLE
forgot to remove console.log in package

### ISSUE THREAD

**Issue by misonomikadev** [elysiajs/elysia#616]
### What version of Elysia.JS is running?

v1.0.13

### What platform is your computer?

Linux 6.2.0-39-generic x86_64 x86_64

### What steps can reproduce the bug?

"NODE_ENV=development bun run --watch src/index.ts" in command line

### What is the expected behavior?

Nothing in console (because i removed all console in my app)

### What do you see instead?

![image](https://github.com/elysiajs/elysia/assets/93425627/8176c858-fdfc-4c70-a89b-b49b2b7f8381)

### Additional information

I was checked that my code don't have any console.log that log the app.

**Comment by SaltyAom** [comment]
This seems like a bug in 1.0.12.
Are you sure you are using Elysia 1.0.13? Have you try removing `node_modules` and `bun.lockb` and reinstall again yet?

**Comment by misonomikadev** [comment]
Sorry for the late reply, before I created this issue, I checked to make sure I was on v1.0.13 but when I took the source code somewhere else it didn't have this problem, yes. Maybe I changed the version but forgot to update node_modules, thank you very much.
