### ISSUE TITLE
Feature request: RAW graphql-js plugin

### ISSUE THREAD

**Issue by capaj** [elysiajs/elysia#62]
I typically use code first approach to building my graphql APIs. That would be things like https://github.com/hayes/pothos or https://nexusjs.org/

and for those I would prefer to plug them into elysia using just [graphql-js](https://github.com/graphql/graphql-js). apollo-server and yoga have extra performance overhead I'd like to avoid.

**Comment by Cauen** [comment]
Hi @capaj 
It seems the plugin dont support setting schema. But the code of the plugin is baiscally only 2 lines:

Try this:

```ts
const graphqlPath = "/graphql"

new Elysia()
  .get('/', (() => `Hello`))
  .get('/id/:id', (({ params: { id } }) => id))
  .get(graphqlPath, async ({ request }) => yoga.fetch(request))
  .post(graphqlPath, async ({ request }) => yoga.fetch(request), { type: 'none' })
```

[Working example with Pothos](https://github.com/Cauen/bun-graphql-pothos/blob/master/src/index.ts#L7)

Hope that helps :)

**Comment by nephix** [comment]
Is there a way to make `pothos` work with the official yoga plugin from https://elysiajs.com/plugins/graphql-yoga?

**Comment by SaltyAom** [comment]
Closing as not planned in the roadmap.
We feels like we have no profession in GraphQL domain enough and don't have enough effort to maintain other GraphQL plugin.

I'd happy to see a third-party plugin as well.

**Comment by kamalkech** [comment]
@Cauen Property 'fetch' does not exist on type '<TypeDefs extends TypeSource, Context extends MaybePromise<Record<string, unknown>> | ((initialContext: YogaInitialContext) => unknown) | undefined, Prefix extends string = "/graphql">({ path, typeDefs, resolvers, resolverValidationOptions, inheritResolversFromInterfaces, updateResolversInPlace, schemaExtensions, sc...
