### ISSUE TITLE
`app.once()`

### ISSUE THREAD

**Issue by touhidurrr** [elysiajs/elysia#620]
### What is the problem this feature would solve?

I noticed that `app.on()` is available but `app.once()` is not.

### What is the feature you are proposing to solve the problem?

`app.once()` should also be available.

### What alternatives have you considered?

None.

**Comment by SaltyAom** [comment]
I can't see the use case why this would be beneficial for server-side and Elysia.

I think it made sense for client-side but not on sever-side, closing as not going to implemented.

If you would like to propose this feature, please create a proposal on why we would like to add this, thanks.
