### ISSUE TITLE
`app.onStart()` types and documentation does not match and does not work

### ISSUE THREAD

**Issue by touhidurrr** [elysiajs/elysia#621]
### What version of Elysia.JS is running?

1.0.13

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

When I hover over `app.onStart()`, I see:
![image](https://github.com/elysiajs/elysia/assets/46617994/2de7984f-19b4-4b60-9146-471df171f6de)
However, copy pasting the code gives you:
![image](https://github.com/elysiajs/elysia/assets/46617994/c1e19dc3-f21c-45ca-80c8-76b328b56886)
As you can see from this image, even when I copy paste the documented code, I do not get the types.

### What is the expected behavior?

Types should be available.

### What do you see instead?

Types cannot be found.

### Additional information

Also, string formatting is not done properly in example. The example has:
```ts
new Elysia()
  .onStart(({ url, port }) => {
    console.log('Running at ${url}:${port}');
  })
```
However, it should be:
```ts
new Elysia()
  .onStart(({ url, port }) => {
    console.log(`Running at ${url}:${port}`);
  })
```

**Comment by touhidurrr** [comment]
Also, after running the code:
![image](https://github.com/elysiajs/elysia/assets/46617994/0e1cce68-9575-4913-a1b5-605c5a2e2554)

**Comment by SaltyAom** [comment]
Close with [db4e428](https://github.com/elysiajs/elysia/commit/db4e428cfa72fcbab6c1ca943e3ededbea5a0649)
