### ISSUE TITLE
onError: For 'VALIDATION' type errors, status code change does not work (200 is always returned)

### ISSUE THREAD

**Issue by nadeemramsing** [elysiajs/elysia#639]
### What version of Elysia.JS is running?

"version": "1.0.17"

### What platform is your computer?

Linux 5.15.0-88-generic x86_64 x86_64

### What steps can reproduce the bug?

- Create a route /files POST
- Use type: {body: t.Object({file: t.File()})}
- In onError function, when code === 'Validation', set status to 400.
- Run app
- From Postman, do a request on the route with a form-data body without "file"

### What is the expected behavior?

Return error and 400 status code.

### What do you see instead?

Error is returned but status code remains 200.

### Additional information

In fact, logger (HoltLogger) says "unknown status":
![image](https://github.com/elysiajs/elysia/assets/20681851/47261c88-5763-474a-9ae6-22d08d3c8130)

In my case, setting status code and even return a value (e.g. "TEST") does not work; 200 and Validation Error by type lib is returned. Execution gets there (console.log inserted and called just before the setting of status and return).

**Comment by bogeychan** [comment]
You can overrite `error.status` or return a raw `Response` object as a workaround:

```ts
.onError(({ code, error }) => {
  if (code === "VALIDATION") {
    // @ts-ignore
    // error.status = 400;
    return new Response(error.message, {
      status: 400,
      headers: { "Content-Type": "application/json" },
    });
  }
})
```

**Comment by nadeemramsing** [comment]
Thank you; I'll try that.

**Comment by nadeemramsing** [comment]
Working perfectly; thank you.

**Comment by bogeychan** [comment]
Please leave the issue open as it's a bug and needs to be fixed somehow.

`set.status = 400` must either work or not be made accessible.

I gave you a workaround to make it work for you right away.
