### ISSUE TITLE
Unable to access root level macros in plugins

### ISSUE THREAD

**Issue by jrnxf** [elysiajs/elysia#640]
### What version of Elysia.JS is running?

1.0.20

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

The steps for this bug our outlined in [this thread](https://discord.com/channels/1044804142461362206/1239531018130559047). @SaltyAom already patched a fix for usage in groups, but the same patch for plugins feels like the next step given the documentations recommendation to use plugins as a means of cleaning up routes.

### What is the expected behavior?

Macros applied at the global level are inherited by plugins

### What do you see instead?

Plugins don't have access to the macros

**Comment by SaltyAom** [comment]
Should be resolved in [3d0adcf](https://github.com/elysiajs/elysia/commit/3d0adcf7e25d9044dce3ea541daa6d0272d91582), published on 1.0.27

Feels free to tag me to reopen the issue if the problem still persists.
