### ISSUE TITLE
`redirect` doesn't work with `aot: false`

### ISSUE THREAD

**Issue by bogeychan** [elysiajs/elysia#644]
### What version of Elysia.JS is running?

1.0.20

### What platform is your computer?

WSL Ubuntu

### What steps can reproduce the bug?

```ts
const app = new Elysia({ aot: false }).get('/', ({ redirect }) => redirect('/yay')).listen(8080)
```

### What is the expected behavior?

redirect works

### What do you see instead?

`redirect is not a function`

### Additional information

reported on [discord](https://discord.com/channels/1044804142461362206/1242194444783059037)

**Comment by SaltyAom** [comment]
Should be fixed on 321a7c5, published under 1.0.21
