### ISSUE TITLE
rate limit feature or plugin !?

### ISSUE THREAD

**Issue by MilesWuCode** [elysiajs/elysia#659]
### What is the problem this feature would solve?

limit ip times

### What is the feature you are proposing to solve the problem?

rate limit 

### What alternatives have you considered?

express-rate-limit
or 
nginx
limit_req zone=one burst=10 nodelay;

**Comment by touhidurrr** [comment]
@MilesWuCode, have your tried this https://www.npmjs.com/package/elysia-rate-limit
