### ISSUE TITLE
Validation with Elysia Typebuilder

### ISSUE THREAD

**Issue by itsyoboieltr** [elysiajs/elysia#66]
Is there a way to do validation with the Elysia Typebuilder? similar to zod.parse, where it would return true or false, or throw an error message. I would like to use the schemas I declared in Elysia also outside of body parsing, inside my application code.

**Comment by itsyoboieltr** [comment]
@SaltyAom how something like this would be implemented? According to the TypeBox docs, the TypeCompiler.Compile function needs to be executed to get Type.Check method. However, the Elyisa Typebuilder type does not conform to the input argument of the TypeCompiler.Compile function, throwing an error.

`
Argument of type 'TObject<{}>' is not assignable to parameter of type 'TSchema'.
  Property '[Kind]' is missing in type 'TObject<{}>' but required in type 'TSchema'.ts(2345)
`

**Comment by SaltyAom** [comment]
Hi sorry for the late response.

**Elysia.t** is built on TypeBox but it does some type override which might cause `Symbol` to be misunderstood by TypeScript itself, basically you should be able to use it despite the warning.

However, I'd recommended using `TypeCompiler` instead of `Value` for AoT compilation, you should be able to do either:

1. Using TypeBox Compiler 
```ts
import { t } from 'elysia'
import { TypeCompiler } from '@sinclair/typebox/compiler'

const valueToCheck = {}

const a = TypeCompiler.Compile(
	t.Object({
		username: t.String()
	})
)

if(a?.Check(valueToCheck))
  console.log(a?.Errors(valueToCheck))
```

2. If TypeBox Compiler cause and error, you could use `getSchemaValidator` from Elysia, this should fix the type error.
```ts
import { t, getSchemaValidator } from 'elysia'

const a = getSchemaValidator(
	t.Object({
		username: t.String()
	}),
        // This is a reference model to resolve, aka. Elysia.model
        // Use to resolve named schema
	{}
)

const valueToCheck = {}

if(a?.Check(valueToCheck))
  console.log(a?.Errors(valueToCheck))
```

Let me know if this help!

**Comment by itsyoboieltr** [comment]
Yes! Thank you, I got it working. Indeed, the TypeBox Compiler does not work, I assume we would need to patch the types for it somehow to make it work. However, getSchemaValidator works perfectly! I made a parsing function and extended it with a nice zod looking api to my liking, coming from trpc. I post it down below, just in case someone runs into the same issue as I did.


```typescript
import { t, UnwrapSchema, getSchemaValidator } from 'elysia';

// these types are sadly not exported, so we have to acquire them through the exported functions
type TSchema = Parameters<typeof t.Readonly>[0];
type TArray<T extends TSchema> = ReturnType<typeof t.Array<T>>;

export const makeSchema = <T extends TSchema>(schema: T) => {
  const validator = getSchemaValidator(schema, {});
  if (!validator) throw new Error('Invalid schema!');
  const parse = (data: UnwrapSchema<T>): UnwrapSchema<T> => {
    const isValid = validator.Check(data);
    if (isValid) return data;
    throw new Error(
      JSON.stringify(
        [...validator.Errors(data)].map(({ path, message }) => ({
          path,
          message,
        }))
      )
    );
  };
  const array = () => {
    const validator = getSchemaValidator(t.Array(schema), {});
    if (!validator) throw new Error('Invalid schema!');
    const parse = (data: UnwrapSchema<TArray<T>>): UnwrapSchema<TArray<T>> => {
      const isValid = validator.Check(data);
      if (isValid) return data;
      throw new Error(
        JSON.stringify(
          [...validator.Errors(data)].map(({ path, message }) => ({
            path,
            message,
          }))
        )
      );
    };
    return { ...t.Array(schema), parse };
  };
  return { ...schema, parse, array };
};

// usage in application code

export const schema = makeSchema(t.Object({ test: t.String() }));

const sample: any = { test: 'test' };

const test = schema.parse(sample);

/* 
const test: {
  test: string;
};
*/
```
