### ISSUE TITLE
"default" option is not being applied on validation

### ISSUE THREAD

**Issue by warcayac** [elysiajs/elysia#664]
### What version of Elysia.JS is running?

1.0.22

### What platform is your computer?

Linux 6.9.2-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

```typescript
export const apiUsersRoutes = new Elysia({prefix:'/users'})
  .post(
    '/',
    async ({body}) => {
      const result = await users.addOne(body);
      return result;
    },
    {
      body: t.Object({
        username: t.String(),
        password: t.String(),
        email: t.Optional(t.String({format: 'email'})),
        isSuperuser: t.Boolean({default: false}),
      })
    }
  )
```

then try to send a POST request with this body:

{
  "username": "admin",
  "password": "123456789",
  "email": "admin@chesu.org"
}

### What is the expected behavior?

body is accepted with default value applied to "isSuperuser" property

### What do you see instead?

![image](https://github.com/elysiajs/elysia/assets/7342885/db1ef7ce-74b7-42a1-beb0-c29981acec89)

If I send this body:
{
  "username": "admin",
  "password": "123456789",
  "email": "admin@chesu.org",
  "isSuperuser": false
}

then it is accepted and processed.

**Comment by david-plugge** [comment]
Workaround: Wrap it into optional and pass false as a second parameter

**Comment by warcayac** [comment]
@david-plugge it doesn't work, isSuperuser is ignored and never is assigned the default value.

**Comment by SaltyAom** [comment]
7d0e29b published on 1.0.23 including test case. Let me know if it works on your end.

**Comment by warcayac** [comment]
it is working as expected, thanks.

**Comment by M-Gonzalo** [comment]
Oh I think I'm relying on this bug for my app to work as intended. I'm not experienced with Typebox so when I saw that `default` values would get translated to examples in Swagger, I started using them everywhere. But if they can actually permeate to the DB, I should go and update everything at once lol
