### ISSUE TITLE
OnResponse

### ISSUE THREAD

**Issue by itsyoboieltr** [elysiajs/elysia#67]
Is there a way to fire an event like with "onRequest", but with both the request and response objects? Basically, something like "onResponse". 
I would like to log each response from the server. It would be nice for simple logging, something like: `GET / 200 2ms`

**Comment by SaltyAom** [comment]
Yes, [onAfterHandle](https://elysiajs.com/concept/middleware.html#life-cycle) as refers to this figure.

![image](https://github.com/elysiajs/elysia/assets/35027979/54a74bda-4fe2-4325-bc10-4d724b7ccf5c)

**Comment by itsyoboieltr** [comment]
@SaltyAom Thank you! However, the onAfterHandle function only fires on successful responses. For instance, if the route is not found, or the body is invalid, or an error is thrown, it is not fired. How can I listen to both successful and non-successful requests? This is why I suggested onResponse.

**Comment by SaltyAom** [comment]
Ok, this makes sense, I will add **onResponse** to Elysia 0.6.

**Comment by SaltyAom** [comment]
This is now introduced in Elysia 0.6, [see onResponse](https://elysiajs.com/blog/elysia-06.html#onresponse)
