### ISSUE TITLE
Decorates are replacing each other

### ISSUE THREAD

**Issue by vitorpldev** [elysiajs/elysia#673]
### What version of Elysia.JS is running?

1.0.23

### What platform is your computer?

Linux 6.5.0-35-generic x86_64 x86_64

### What steps can reproduce the bug?

![Captura de tela de 2024-06-09 23-59-08](https://github.com/elysiajs/elysia/assets/143728275/73c3976b-51b3-4139-8bdd-84481077594c)

I ended up putting the controllers for each route into groups, the user and url controllers both have the /create route.
For some reason, when I call /user/create, Elysia is running the service from the /url/create route

**Comment by bogeychan** [comment]
@vitorpldev, can you please post code snippets in text form? checkout [Creating and highlighting code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)

**Comment by vitorpldev** [comment]
Okay, the code I gave as an example is this:

```typescript
import Elysia, { t } from "elysia";

const user_decorator = (application: Elysia) => {
  return application.decorate({
    services: {
      find: (name: string) => `The name of user is ${name}`,
    },
  });
};

const url_decorator = (application: Elysia) => {
  return application.decorate({
    services: {
      find: (url: string) => `The url is ${url}`,
    },
  });
};

const user_controller = (application: Elysia) => {
  return application.use(user_decorator).get(
    "/",
    ({ query, services }) => {
      return new Response(services.find(query.value), { status: 200 });
    },
    {
      query: t.Object({ value: t.String() }),
    }
  );
};

const url_controller = (application: Elysia) => {
  return application.use(url_decorator).get(
    "/",
    ({ query, services }) => {
      return new Response(services.find(query.value), { status: 200 });
    },
    {
      query: t.Object({ value: t.String() }),
    }
  );
};

const controller = (application: Elysia) => {
  return application
    .group("/user", (user) => {
      return user.use(user_controller);
    })
    .group("/url", (url) => {
      return url.use(url_controller);
    });
};

const app = new Elysia().use(controller);

app.listen({ hostname: "localhost", port: 3030 }, (server) => {
  console.log(`Server is running at ${server.url}`);
});
```

If in this code I make a request for GET
for http://localhost:3030/user/ passing the value "Elysia" in the query, the expected would be "The name of user is Elysia", but the result is "The url is Elysia".
This is because the way in controllers I am grouping the url_controller after the user_controller, the decorate of the url_controller is replacing the decorate of the user_controller

**Comment by nxht** [comment]
@vitorpldev 
Both `user_decorator` and `url_decorator` is decorating same `services`, I think it's expected to get overridden.

You can either
- Use different name to decorate instead of `services` like `user_services` and `url_services`
- If you want to keep it as it is, you might consider using `derive` instead as you can define the [scopes](https://elysiajs.com/essential/scope.html)

**Comment by vitorpldev** [comment]
> @vitorpldev Both `user_decorator` and `url_decorator` is decorating same `services`, I think it's expected to get overridden.
> 
> You can either
> 
> * Use different name to decorate instead of `services` like `user_services` and `url_services`
> * If you want to keep it as it is, you might consider using `derive` instead as you can define the [scopes](https://elysiajs.com/essential/scope.html)

So, if you try to do this using services with different names, you will notice that the same problem occurs.
Unfortunately the problem is not the declaration of the services name in different decorates.

**Comment by vitorpldev** [comment]
Perfect, thank you my friend.
