### ISSUE TITLE
Optional query params

### ISSUE THREAD

**Issue by vrn-dev** [elysiajs/elysia#68]
For the following route:

```
app
	.get('/qtest', ({query}) => {
		return {
			query
		}
	}, {
		query: t.Object({
			pageNum: t.Optional(t.Numeric({ default: 1 })),
			pageSize: t.Optional(t.Numeric({ default: 10 })),
		}),
	})
```

`curl localhost:5000/qtest` gives me `Invalid query: 'pageNum'. Expected number`

How do I supply query params which are optional

**Comment by SaltyAom** [comment]
Fixes with 9192fa9, update to Elysia 0.5.23 to fix this error.

**Comment by mckamyk** [comment]
0.5.23 seems to have broken non-optional validation for me.
```ts
       .post('/todos/toggle/:id', ({params}) => {
		const todo = db.find(todo => todo.id === params.id)
		if (todo) {
			todo.completed = !todo.completed
			return <TodoItem {...todo} />
		}
	}, {
		params: t.Object({
			id: t.Numeric()
		})
	})
```
Works fine with 0.5.22, but when using 0.5.23 I get the `Invalid params: 'id'. Expected number`

**Comment by vrn-dev** [comment]
I can confirm that optional query object are working as intended but has indeed broken `t.Numeric()` coercion in params object.

```ts
.get('/test/:id/:id2/:id3', ({query}) => {
		return {
			query
		}
	}, {
		query: t.Object({
			pageNum: t.Optional(t.Numeric({ default: 1 })),  // <----- Works
			pageSize: t.Optional(t.Numeric({ default: 10 })), // <----- Works
		}),
		params: t.Object({
			id: t.Numeric(),             // <------ Invalid params: 'id'. Expected number
                        id2: t.Optional(t.Numeric),  // <------ Invalid params: 'id'. Expected number
                        id3: t.String()              // <------ Works
		})
	})
```

**Comment by SaltyAom** [comment]
Right, numeric path parameters should be fixed by 0.5.24.

I accidentally used query check on params which caused this error that was used to fix 0.5.23, you can see the commit here  4d8c6ca

**Comment by pacmanmati** [comment]
`t.Numeric()` coercion works for me after upgrading to `0.5.25` (latest)

**Comment by SaltyAom** [comment]
Closing this issue as the use of `t.Numeric` and no update.

Feels free to reopen the issue if the problem still insists.

**Comment by Ernxst** [comment]
This seems to be broken again (using Bun `v0.7.3` but also noticed this issue with `pnpm 8.6.10`).

Making a post request to following route does not work on `0.6.9` when `aot` is disabled:

```javascript
import { Elysia, t } from "elysia";

new Elysia({ aot: false })
  .post("/sign-in", ({ query }) => {}, {
    query: t.Object({
      redirect_uri: t.Optional(t.String()),
    }),
  })
  .listen(8080);
```

Gives the following error:

```
Invalid query, 'http://localhost:8080/sign-in': Unexpected property

Expected: {}

Found: {
  "http://localhost:8080/sign-in": ""
}
```

Enabling `aot` seems to fix this.

**Comment by SaltyAom** [comment]
Should be fixed in 0.6.10

**Comment by LucasLundJensen** [comment]
Is this broken again?
I'm getting this error when attempting to have an optional field in the body.

Using 0.7.30

```JavaScript
app
    .post("/getUser", ({ body }) => getUser(body.email), {
    body: t.Object({ email: t.Optional(t.String()) })
})
```

**Comment by spanwair** [comment]
same issue .. Elysia please repair this bug

**Comment by spanwair** [comment]
I found a work around for using object type:
```
t.Optional(t.Partial(t.Object({ noError: t.String() })))
```

**Comment by QAdamek** [comment]
i have the same issue :(

**Comment by JairZijp** [comment]
Same here with ```t.Optional(t.String())```

**Comment by akainocode** [comment]
Confirming that this isn't working with ``t.Optional(t.Boolean())`` as well.

**Comment by justin13888** [comment]
Same issue here as of version 1.1.7

**Comment by 0-don** [comment]
having same issue aswell

**Comment by jasperdunn** [comment]
I have this issue as well

**Comment by adidoesnt** [comment]
Facing an issue with t.optional(t.Boolean) and t.optional(t.Date)

**Comment by Exoden** [comment]
Had the same issue with this: `
t.Object({
  value1: t.Optional(t.UnionEnum(enum1)),
  value2: t.Optional(t.UnionEnum(enum2)),
})`

Fixed with this:
`
t.Object({
  value1: t.Optional(t.UnionEnum(enum1, { default: undefined })),
  value2: t.Optional(t.UnionEnum(enum2, { default: undefined })),
})`

**Comment by RoboticWater** [comment]
Echoing that `t.Optional(t.Date())` doesn't seem to work correctly. If I don't supply a the date parameter, I'll get the following validation error:

```{
  "type": "validation",
  "on": "property",
  "summary": "Expected Date",
  "property": "root",
  "message": "Expected Date",
  "expected": "2024-12-12T16:20:10.638Z",
  "found": null,
  "errors": [
    {
      "summary": "Expected Date",
      "type": 20,
      "schema": {
        "type": "Date"
      },
      "path": "",
      "value": null,
      "message": "Expected Date"
    }
  ]
}
```

The route is set up as follows:
```
messages.get(
  "/",
  ({ query }) => {
    const { id, authorId, before, after } = query;
    return db.message.findMany({
      where: { id, authorId, createdAt: { lte: before, gte: after } },
    });
  },
  {
    query: t.Object({
      id: t.Optional(t.Numeric()),
      authorId: t.Optional(t.Numeric()),
      before: t.Optional(t.Date()),
      after: t.Optional(t.Date()),
    }),
  }
);
```

**Comment by alimehasin** [comment]
I’m experiencing the same issue. When using `t.Optional(t.String())` or `t.Optional(t.Date())` and others, setting the value to `null` triggers the problem. However, if I remove the entry entirely from the JSON, the issue does not occur. This seems to be a bug.

**Comment by XavierGeerinck** [comment]
same here, when marking as `t.Optional` I get that query is still required in '@elysiajs/eden';

Just passing `{ query: {} }` seems to do the trick for now.

**Comment by u007** [comment]
i find this issue with params, ive to duplicate my method
