### ISSUE TITLE
`mapResponse` is completely ignored

### ISSUE THREAD

**Issue by recanman** [elysiajs/elysia#685]
### What version of Elysia.JS is running?

1.0.24

### What platform is your computer?

Linux 6.9.2-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

1. Use `mapResponse`.

The function is never called.

```typescript
new Elysia().mapResponse(({response}) => {
	console.log('test');
})
```

The above never logs.

### What is the expected behavior?

`mapResponse` is called.

### What do you see instead?

`mapResponse` is completely ignored, attempting to log anything in there doesn't work, as nothing happens.

### Additional information

This was working previously, but at some Elysia version, it stopped working.

**Comment by SaltyAom** [comment]
Hi, thanks for the report.

Unfortunately I'm unable to reproduce the issue on my end, can you give me a more precise minimal reproducible example that may cause this problem?

We have several [test case for mapResponse here](https://github.com/elysiajs/elysia/blob/edbf6fa816c36c273f673e29ecc0103084f5848e/test/lifecycle/map-response.test.ts) which runs before publishing the package, and if the test fail it won't be published.

Thank you.

**Comment by recanman** [comment]
When I first experimented with ElysiaJS, I mistakenly concluded that middlewares (`.use`) did not have an order. I attempted to reorder the middlewares and it worked.
Apologies for the oversight.
