### ISSUE TITLE
is there a way to render 1 html file or Template engine like EJS , HBS, ETA, etc..

### ISSUE THREAD

**Issue by bobwatcherx** [elysiajs/elysia#7]
I want to render 1 html file, is that possible?

Structur folder  like this:
```
-src
     -views
         - index.html
```

logic code:

const app = new Elysia()
   .get("/myhtml",()=>{
      **WHATS THE LOGIC HERE..... AND IF USE Ejs , Handlebars, and other.....**
})

**Comment by hisamafahri** [comment]
hi, you can use [`@elysia/html` plugin](https://elysiajs.com/plugins/html.html) for that

```ts
import { Elysia } from "elysia";
import { html } from "@elysiajs/html";
import { fileURLToPath } from "bun";
import path from "path";
import fs from "fs";

const __filename = fileURLToPath(new URL(import.meta.url));
const __dirname = path.dirname(__filename);

const app = new Elysia()
  .use(html())
  .get("/", ({ html }) =>
    // You can adjust it base on your html file location. In this example:
    // src
    //  ├── index.ts
    //  └── test.html
    html(fs.readFileSync(path.join(__dirname, "test.html"), "utf8"))
  )
  .listen(3000);
```

**Comment by SaltyAom** [comment]
Hi, sorry for the slow response.

As mentioned by @hisamafahri, you can use Elysia [HTLM plugin](https://elysiajs.com/plugins/html) to return HTML content, additionally, you can just returns HTML content without using `html` function if your content starts with `<!DOCTYPE html>` as stated in the plugin.

> This plugin detects if the string is started with <!DOCTYPE HTML>, it will add Content-Type: text/html; charset=utf8 to the response header

Feels free to re-open the issue if the answer is not clear.

**Comment by djdeo** [comment]
@SaltyAom,  hi can i add dynamic content to the file, like:

```js
app.get('/about', (ctx) => {
  const username = 'John Doe';
  ctx.body = ejs.render('about.ejs', { username });
});
```
the in the about.ejs file, or about.html, i use it like this:


```html
<h1>Hi, <%= username %></h1>
```
don't know if i can set view engine like this:

```js
const { Elysia } = require('elysia');
const ejs = require('ejs');

const app = new Elysia();

app.set('view engine', 'ejs');
```
