### ISSUE TITLE
Elysia fails to bundle without explicitly installing `@elysiajs/fn`

### ISSUE THREAD

**Issue by jkbz64** [elysiajs/elysia#70]
When trying to bundle elysia using `bun build --target bun` it fails to bundle because it cannot resolve `@elysiajs/fn`, the error is `error: Could not resolve: "@elysiajs/fn". Maybe you need to "bun install"?`.
After explicitly installing the package it bundles properly, the only thing that is needed to reproduce the error is to import elysia and try to bundle.

```js
import { Elysia } from "elysia";
```

**Comment by 0xAzazel** [comment]
same issue when run bun build ./src/index.ts

**Comment by 0xAzazel** [comment]
my solution is use this command 
bun add @elysiajs/fn

**Comment by igorrake** [comment]
+1
Can confirm the issue on version 0.5.25

**Comment by SaltyAom** [comment]
This is fixed in >= 0.6.0, you can try it out now by installing elysia@0.6.0-alpha.4.

Please keep this opened until Elysia 0.6.0 stable is released

**Comment by SaltyAom** [comment]
This should be fixed with Elysia 0.6
