### ISSUE TITLE
Semver not followed correctly

### ISSUE THREAD

**Issue by cybercoder-naj** [elysiajs/elysia#720]
### What version of Elysia.JS is running?

1.1.0

### What platform is your computer?

Linux 6.6.32-1-lts x86_64 unknown

### What steps can reproduce the bug?

Upgrade an existing project from `v1.0.x` to `v1.1.0`.

### What is the expected behavior?

Do not have any breaking changes.

### What do you see instead?

Breaking changes with the `onResponse` function.

### Additional information

According to [SemVer](https://semver.org/), *MINOR version when you add functionality in a backward compatible manner*. I don't think it was necessary to rename the function and publish the breaking change as a minor version upgrade.

**Comment by kravetsone** [comment]
as an option, leave it deprecated)
