### ISSUE TITLE
Elysia 1.1 breaks oauth2 plugin on WSL with an Illegal Instruction

### ISSUE THREAD

**Issue by alexkahndev** [elysiajs/elysia#725]
### What version of Elysia.JS is running?

1.1.1

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Try using the OAuth2 plugin in the new Elysia 1.1 and you will get an infinite Seg Fault. You can test the repo at https://github.com/alexkahndev/elysia-oauth2-example.git

### What is the expected behavior?

The code should run and authenticate with OAuth. It was working in 1.0.27

### What do you see instead?
```
alexkahn@LAPTOP-QC1EDE5K:~/webdev/elysia-oauth$ bun run src/server.ts
============================================================
Bun v1.1.20 (ae194892) Linux x64
WSL Kernel v5.15.133 | glibc v2.35
CPU: sse42 popcnt avx avx2
Args: "bun" "run" "src/server.ts"
Features: jsc dotenv transpiler_cache(4) tsconfig(2)
Builtins: "bun:main" "node:fs/promises" "node:path"
Elapsed: 167ms | User: 149ms | Sys: 70ms
RSS: 1.04GB | Peak: 133.40MB | Commit: 1.04GB | Faults: 1

panic(main thread): Segmentation fault at address 0x1A
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.20/lr1ae19489AioggwC2v7nnE+xyQ_+7o/8Dyg+45Eyt3xiF4x40mF8syqnDwqyonDs76q/CA2A0B

Illegal instruction
```
### Additional information

I've removed the env variables from the test repo but if you add your own you can see full functionality, although this is enough to reproduce the issue

**Comment by kravetsone** [comment]
Can you try it with [elysia-oauth2@v1.3.0](https://github.com/kravetsone/elysia-oauth2/releases/tag/v1.3.0)?

**Comment by kravetsone** [comment]
Can you close it?
