### ISSUE TITLE
Invalid body: 'files'. Expected kind Files

### ISSUE THREAD

**Issue by onionhammer** [elysiajs/elysia#74]
I have a pretty simple app, and for some reason it always returns a validation error when POSTing to this endpoint. Additionally, the 'files' is an array of `Blob`, how would you access the filename (which is provided in the request)

```ts
    .post("/bind-faq-document", async ({ body, set, store }) => {
        console.log("bind-faq-document", body.files);

        return "ok";
    }, {
        body: t.Object({
            files: t.Files({
                minItems: 1,
                maxItems: 25,
                // minSize: 1,
                // maxSize: 1024 * 1024 * 10,
            })
        })
    })
    .listen(process.env.PORT || 3000);
```

![image](https://github.com/elysiajs/elysia/assets/969938/63a29746-7215-4150-b7e2-7833bda98143)

Raw log:

![image](https://github.com/elysiajs/elysia/assets/969938/d3f37cff-8c48-4ab4-9645-c9924c480044)

The upload works if I remove the validation hook.

**Comment by onionhammer** [comment]
Copy/pasting the Elysia example ( https://elysiajs.com/patterns/file-upload.html#file-validation ) into an empty file also gives the same error

```ts
import {Elysia, t} from "elysia";

const app = new Elysia()
	.post(
		'/multiple',
		({ body: { files } }) => files[0],
		{
			body: t.Object({
				files: t.Files({
					type: ['image', 'video']
				})
			})
		}
	)
    

    .listen(process.env.PORT || 3000);
```

**Comment by abhi12299** [comment]
I tried this validation hook and it works with the latest release of `elysia`:
```js
{
        body: t.Object({
            files: t.Files({
                minItems: 1,
                maxItems: 25,
                // minSize: 1,
                // maxSize: 1024 * 1024 * 10,
            })
        })
}
```

However, when adding the `type` property to allow certain file types, it fails. Upon inspection, 

```js
.post(
    "/files",
    ({ body: { files } }) => {
      console.dir(files[0].type);
      return "ok";
    },
    {
      body: t.Object({
        files: t.Files({
          minItems: 1,
          type: ["application/pdf"],
        }),
      }),
    }
  )
```

The `files[0].type` gives an empty string and it could be that the mime type could not be validated properly.

**Comment by onionhammer** [comment]
@SaltyAom is the fix related to another issue or PR?

**Comment by wineTGH** [comment]
The bug is still present in the latest version

**Comment by namdien177** [comment]
also facing this in the latest version...
![image](https://github.com/user-attachments/assets/f6bef7f2-7995-482e-8e04-7fbd6d7c52f5)
![image](https://github.com/user-attachments/assets/67d9e3ef-6c2c-4f59-bece-89d24eb5e92e)

Confirmed that if we remove the type/mime validation, then the file is uploaded successfully.
