### ISSUE TITLE
cannot destructure in derive

### ISSUE THREAD

**Issue by staciax** [elysiajs/elysia#744]
### What version of Elysia.JS is running?

`elysia@1.1.3`
`@elysiajs/bearer@1.1.1`

### What platform is your computer?

Darwin 23.5.0 arm64 arm (MacOS 14.5)

### What steps can reproduce the bug?

```ts
import { bearer } from '@elysiajs/bearer';
import { Elysia } from 'elysia';

const app = new Elysia()
	.use(bearer())
	.get('/', ({ bearer }) => bearer)
	.listen(8080);

console.log(
	`🦊 Elysia is running at ${app.server?.hostname}:${app.server?.port}`,
);
```

### What do you see instead?

```json
{"name":"TypeError","message":"Right side of assignment cannot be destructured"}
```

**Comment by QEDK** [comment]
Facing the same issue, sadly.

**Comment by nephix** [comment]
I have the same issue in `1.0.23`

**Comment by SaltyAom** [comment]
Does this problem still persists in the latest version (1.1.5)?

**Comment by staciax** [comment]
> Does this problem still persists in the latest version (1.1.5)?

Sorry, I forgot to turn it off. It's working normally now. <3
