### ISSUE TITLE
TypeBox support with working types

### ISSUE THREAD

**Issue by itsyoboieltr** [elysiajs/elysia#75]
It would be nice if we could use TypeBox functionalities with Elysia t in a type safe manner. The issue is was already mentioned in #66: `Property '[Kind]' is missing in type 'TObject<{}>' but required in type 'TSchema'.ts(2345)` 
Elysia types do work with TypeBox, but the types need to be casted to avoid typescript errors. I wonder if this could be fixed someway, to have proper typing.
Reproduction + my current (kind of boring and annoying) workaround:

```typescript
import { t, UnwrapSchema } from 'elysia';
import { Value } from '@sinclair/typebox/value';

const test = t.String({ default: 'test' });

const testValue = Value.Create(test);

// Argument of type 'TString' is not assignable to parameter of type 'TSchema'. Property '[Kind]' is missing in type 'TString' but required in type 'TSchema'. ts(2345)

// but this is only a type error, the function still works.

const testValueFixed: UnwrapSchema<typeof test> = Value.Create(test as any);

// type error workaround
```

**Comment by itsyoboieltr** [comment]
This works:
```typescript
const a = getSchemaValidator(
  t.Object({
  	username: t.String()
  }),
       // This is a reference model to resolve, aka. Elysia.model
       // Use to resolve named schema
  {}
)
``` 
This does not work:
```typescript
const a = TypeCompiler.Compile(
  t.Object({
  	username: t.String()
  })
)
``` 
And the feature request is, is there any way to fix the type error when using the native TypeBox functions, by adding the Property '[Kind]', which is required in TSchema? to avoid the error mentioned before.

**Comment by AlandSleman** [comment]
Not sure if this helps, but you can extract the Static type from a schema via `<schema>.static`:
```
const testSchema = t.String({ default: "test" });
// TestSchema is of type string
type TestSchema = typeof testSchema.static;
```

**Comment by MeowningMaster** [comment]
Typebox didn't hit v1 yet and have many breaking changes in each release. The fix is to synchronize typebox version with elysia's. Actually i don't put `@synclair/typebox` to my package.json at all, I can do it because bun (and pnpm) hoists dependencies in node_modules

schema.ts
![image](https://github.com/elysiajs/elysia/assets/46621668/28d5c085-1b2a-49be-93d3-0c59e8f503fe)
controller.ts
![image](https://github.com/elysiajs/elysia/assets/46621668/baa41589-6204-47f4-9a16-76f2d59a6a4a)

**Comment by SaltyAom** [comment]
Elysia installed with a specific version of Typebox. If you install TypeBox separately a version is going to mismatch.

To fix this, we can add a `override` fields in package.json to synchronize both version of TypeBox.

```json
{
    "override": {
        "@sinclair/typebox": "0.32.4"
    }
}
```

Feels free to reopen the issue if this doesn't help.
