### ISSUE TITLE
Cookie: Right side of assignment cannot be destructured `aot: true`

### ISSUE THREAD

**Issue by bogeychan** [elysiajs/elysia#750]
### What version of Elysia.JS is running?

1.1.3

### What platform is your computer?

WSL Ubuntu

### What steps can reproduce the bug?

```ts
import { Elysia } from "elysia";

new Elysia()
  .get("/", ({ set, cookie: { auth } }) => {
    console.log(auth.value);
    return "";
  })
  .listen(8080);
```

Open http://localhost:8080/ in browser

### What is the expected behavior?

no error

### What do you see instead?

```json
{"name":"TypeError","message":"Right side of assignment cannot be destructured"}
```

### Additional information

This works as expected:

```ts
import { Elysia } from "elysia";

// order of destructured objects matter `cookie, set` !== `set, cookie`
new Elysia()
  .get("/", ({ cookie: { auth }, set }) => { 
    console.log(auth.value);
    return "";
  })
  .listen(8080);
```

Works with `aot: false` too: `new Elysia({ aot: false })`

reported on [discord](https://discord.com/channels/1044804142461362206/1264905917544136826/1264905917544136826)

**Comment by PrashantSakre** [comment]
yes getting the same issue in version 1.1.3

**Comment by SaltyAom** [comment]
Should have been fixed with a59edcc, published under 1.1.4

**Comment by nephix** [comment]
Can confirm it works 🚀 thank you @SaltyAom 🙏

**Comment by bogeychan** [comment]
ty, works for me too
