### ISSUE TITLE
SyntaxError: export 'Html' not found in '@kitajs/html'

### ISSUE THREAD

**Issue by entrptaher** [elysiajs/elysia#759]
### What version of Elysia.JS is running?

"elysia": "^1.1.4"

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Simply install `@elysiajs/html` as per the doc.

```tsx
import { Elysia } from "elysia";
import { html } from "@elysiajs/html";

new Elysia()
  .use(html())
  .get(
    "/html",
    () => `
            <html lang='en'>
                <head>
                    <title>Hello World</title>
                </head>
                <body>
                    <h1>Hello World</h1>
                </body>
            </html>`
  )
  .get("/jsx", () => (
    <html lang="en">
      <head>
        <title>Hello World</title>
      </head>
      <body>
        <h1>Hello World</h1>
      </body>
    </html>
  ))
  .listen(30001);
```

### What is the expected behavior?

No errors.

### What do you see instead?

```
1 | (function (entry, fetcher)
    ^
SyntaxError: export 'Html' not found in '@kitajs/html'
```

### Additional information

Seems a version specific problem from `@kitajs/html` in their latest version `4.2.0`, the following to the `package.json` fixes this issue for now.

```
  "overrides": {
    "@kitajs/html": "4.1.0"
  }
```

**Comment by x4132** [comment]
https://github.com/elysiajs/elysia-html/issues/91 Probably should put the issue in the plugin repo

**Comment by x4132** [comment]
Fix unnecessary as [kitajs 4.2.1](https://github.com/kitajs/html/releases/tag/%40kitajs%2Fhtml%404.2.1) fixes the issue.

**Comment by SaltyAom** [comment]
Closing as kita 4.2.1 released

**Comment by cholasimmons** [comment]
Same as [this issue](https://github.com/elysiajs/elysia-html/issues/91),
My Elysia app can also not find "Html" in @kitajs/html

elysia: 1.2.12
@elysiajs/html: 1.2.0
@kitajs/ts-html-plugin: 4.1.1

**Comment by x4132** [comment]
update your lock file to kita 4.2.1
