### ISSUE TITLE
state, decorate and derive does not infer types without chaining

### ISSUE THREAD

**Issue by implicit-invocation** [elysiajs/elysia#77]
I mean

```Typescript
app
  .use(
    jwt({
      secret: "secret",
    })
  )
  .get("/token", (req) => {
    req.jwt.sign({ sub: "1" });
    ...
  });
```
This is valid.

This will throw a type error.
```Typescript
app.use(
  jwt({
    secret: "secret",
  })
);
app.get("/token", (req) => {
  req.jwt.sign({ sub: "1" });
});
```
But `(req as any).jwt` can be used.

I know this might be intended, but to be able to infer type with chaining should be very nice.
In Hono, they have 2 Generics: Bindings for `c.env` and Variables for `c.get`.

**Comment by LoganArnett** [comment]
I believe this is an expected outcome based on the docs:
https://elysiajs.com/patterns/method-chaining.html#method-chaining
