### ISSUE TITLE
Make Elysia easier to maintain and debug by setting aot: false by default

### ISSUE THREAD

**Issue by remorses** [elysiajs/elysia#770]
### What is the problem this feature would solve?

Aot mode is very difficult to debug and maintain because it relies on creating a code string, transforming it with Sucrose and evaluating it at runtime

Aot mode should not be the default, it makes it super hard to debug issues because stack traces don’t point to any file, you instead have to debug the code generation code itself

For example currently there is a bug where throwing in the first line of an async generator handler crashes the server, I could not fix this issue in #742 because I would have to change at least 20 signature calls in the aot code generation without type safety and clear understanding of what branches get executed.

in my opinion speeding up Elysia by a few milliseconds by complicating 10x the whole codebase is not worth it. The only benefit of this feature are synthetic benchmarks, it does not improve real applications performance 

### What is the feature you are proposing to solve the problem?

Make aot false by default and deprecate it over time. Fix all the tests that currently fail with aot disabled

**Comment by SaltyAom** [comment]
Performance is one of the key factor that I made Elysia, and willing to trade some DX for the said problem.

However, I agreed with closing aot:false issues.

So I'm not going implement this, closing as not planned.

**Comment by crishoj** [comment]
IMO, as long as `aot` is available to developers, the whole test suite should pass both with `aot: true` and `aot: false`.

**Comment by kravetsone** [comment]
> IMO, as long as `aot` is available to developers, the whole test suite should pass both with `aot: true` and `aot: false`.

totally agree
elysia should run test in two modes

but for now we can add WARNING for aot: false mode
