### ISSUE TITLE
MESSY ERROR `NOT FOUND`

### ISSUE THREAD

**Issue by on1force** [elysiajs/elysia#775]
### What version of Elysia is running?

1.1.5

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

I honestly confused how to reproduce this, because it's working fine on local, but when I deployed it on Render something is not found. the errors are as follows

```
*/var D1=jj,M1=Wj;var e2=Object.prototype.toString,s0=/^[\u0009\u0020-\u007e\u0080-\u00ff]+$/;var o1=Y1(r0(),1);class B0{j;W;$;constructor(j,W,$={}){this.name=j;this.jar=W;this.initial=$}get cookie(){if(!(this.name in this.jar))return this.initial;return this.jar[this.name]}set cookie(j){if(!(this.name in this.jar))this.jar[this.name]=this.initial;this.jar[this.name]=j}get value(){return this.cookie.value}set value(j){if(!(this.name in this.jar))this.jar[this.name]=this.initial;this.jar[this.name].value=j}get expires(){return this.cookie.expires}set expires(j){this.cookie.expires=j}get....

this is way longer than this.. got limited by (maximum is 65536 characters) on issue body.
```

the message is NOT_FOUND, but I don't know what.. all path seems to be correct. Maybe it's on Render end ?
p.s. I've built a semi-complex api endpoint with elysia and prisma

### What is the expected behavior?

no errors

### What do you see instead?

```
*/var D1=jj,M1=Wj;var e2=Object.prototype.toString,s0=/^[\u0009\u0020-\u007e\u0080-\u00ff]+$/;var o1=Y1(r0(),1);class B0{j;W;$;constructor(j,W,$={}){this.name=j;this.jar=W;this.initial=$}get cookie(){if(!(this.name in this.jar))return this.initial;return this.jar[this.name]}set cookie(j){if(!(this.name in this.jar))this.jar[this.name]=this.initial;this.jar[this.name]=j}get value(){return this.cookie.value}set value(j){if(!(this.name in this.jar))this.jar[this.name]=this.initial;this.jar[this.name].value=j}get expires(){return this.cookie.expires}set expires(j){this.cookie.expires=j}get....

MESSAGE: NOT_FOUND
```

### Have you try removing the `node_modules` and `bun.lockb` and try again yet?

yup

**Comment by hi-zp** [comment]
same issue on centos. My project will release on this week, but this problem has left me with nothing to do...

**Comment by Ripwords** [comment]
This looks like a minified version of some kind, previously on one of Elysia's plugin, we noticed that minifying the build with bun caused an error as well. You can refer to [this](https://github.com/cybercoder-naj/logestic/pull/35#issue-2420812116) for reference. 

I'm not 100% sure it's this error, but give it a go and see if that resolves your issue

**Comment by on1force** [comment]
Hmm.. interesting, but on Render my start setting is set to bun index.ts and build to bun install, so I think it's not running the compiled version of the script. But again not really sure cause the build event state that

```bash
==> Uploading build...
==> Build uploaded in 8s
==> Build successful 🎉
==> Deploying...
==> Using Node version 20.15.1 (default)
==> Docs on specifying a Node version: https://render.com/docs/node-version
==> Using Bun version 1.1.0 (default)
```

not sure what they did on still using Node.

anyhow, it's not causing any breaking errors for the moment. So i think I'm just gonna let it be for now until I can find the cause

**Comment by on1force** [comment]
found it, It was the default health check path made by renderer (healthz), make sure to include it in your path guys!
