### ISSUE TITLE
Body type will be unknown if strictNullChecks not enabled

### ISSUE THREAD

**Issue by clansty** [elysiajs/elysia#777]
### What version of Elysia is running?

1.1.5

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

Something like 
```ts
let app = new Elysia()
  .post('test', async ({ body }) => {
    console.log(body.uuid)
  }, {
    body: t.Object({
      uuid: t.String(),
    }),
  });
```
set `strict: false` or `strictNullChecks: false` in tsconfig.json

### What is the expected behavior?

the body type is `{ uuid: string }`

### What do you see instead?

typescript think body is unknown and shows: `TS2339: Property uuid does not exist on type unknown`

### Additional information

Add `strictNullChecks: true` will work, but I need to fix 296 typescript errors in my project

### Have you try removing the `node_modules` and `bun.lockb` and try again yet?

yes

**Comment by SaltyAom** [comment]
This is an expected TypeScript error as it's a behavior of the TypeScript Language Server.

Closing as out of scope that Elysia can change or handle.

**Comment by andrewchester1** [comment]
I have this same issue with a mono repo for a react-native mobile app. I have more details on this issue on Discord https://discord.com/channels/1044804142461362206/1277665925029429432 

Adding strictNullChecks: true and strict: true did not fix the issue for me sadly 
Not sure if I am missing something else, but I have been trying to resolve this issue for 2 weeks now
