### ISSUE TITLE
Add Default .gitignore to Prevent Committing .env Files

### ISSUE THREAD

**Issue by boomNDS** [elysiajs/elysia#778]
### What is the problem this feature would solve?

Currently, there's no default .gitignore setup that prevents .env files from being committed to the repository. This can lead to sensitive information being unintentionally exposed.

### What is the feature you are proposing to solve the problem?

Add .env to .gitignore:

Ensure that .env files are included in the .gitignore file by default to prevent them from being committed to the repository.
Implement Default .gitignore Setup for New Projects:

Automatically generate a .gitignore file with common patterns like .env, node_modules/, and dist/ when initializing new projects. This will help streamline the setup process and reduce the risk of accidental commits of sensitive information.

**Comment by kravetsone** [comment]
This is not elysia issue 
And also https://github.com/kravetsone/elysiajs do it

**Comment by boomNDS** [comment]
Thank you for your input. I want to clarify that this isn't an issue with Elysia itself. Instead, the setup issue arises from using the command bun create elysia rather than bun create elysia.js.

**Comment by kravetsone** [comment]
> Thank you for your input. I want to clarify that this isn't an issue with Elysia itself. Instead, the setup issue arises from using the command bun create elysia rather than bun create elysia.js.

You can open issue/PR here - https://github.com/bogeychan/create-elysia
