### ISSUE TITLE
Custom errors thrown in `onRequest` are not usable when caught in `onError` in `1.1.6`

### ISSUE THREAD

**Issue by nathankleyn** [elysiajs/elysia#779]
### What version of Elysia is running?

1.1.6

### What platform is your computer?

Darwin 23.6.0 arm64 arm

### What steps can reproduce the bug?

```ts
import { expect } from "bun:test";
import Elysia from "elysia";

class SomeCustomError extends Error {
  asJSON() {
    return JSON.stringify({
      somePretty: "json",
    });
  }
}
const app = new Elysia()
  .onError(({ error }) => {
    if (error instanceof SomeCustomError) {
      return error.asJSON();
    }
  })
  .onRequest(() => {
    throw new SomeCustomError();
  })
  .get("/", () => "");

const res = await app.handle(new Request("https://localhost/"));
const body = await res.json();

expect(body).toStrictEqual({
  somePretty: "json",
});
```

### What is the expected behavior?

The `error` parameter to the `onError` hook should be the error that was thrown.

### What do you see instead?

The `error` parameter is a function named `S1` and isn't the error that was thrown:

```ts
[Function: S1]
```

### Additional information

This works in 1.1.5, not in 1.1.6.

It works when `aot: false`.

### Have you try removing the `node_modules` and `bun.lockb` and try again yet?

Yes

**Comment by SaltyAom** [comment]
Should be fixed with [2085673](https://github.com/elysiajs/elysia/commit/2085673c3cb22d131536bbc8ac470061b997379f) with test case included, published under 1.1.8

Feels free to reopen or create a new issue if the problem still persists, thanks.
