### ISSUE TITLE
Error from sending empty body multipart/form-data

### ISSUE THREAD

**Issue by misonomikadev** [elysiajs/elysia#780]
### What version of Elysia is running?

1.1.6

### What platform is your computer?

Linux 6.5.0-45-generic x86_64 x86_64

### What steps can reproduce the bug?

Send only file is normal 
Send only "name" field is normal
Send both "file" and "name" is normal
but when nothing in body it throw "Failed to parse body"

```js
import { Elysia, t } from 'elysia'

const app = new Elysia()

app.post('/', ({ body }) => {
    console.log(body)

    return { ok: true } 
}, {
    type: 'multipart/form-data',
    body: t.Object({
        file: t.Optional(t.File()),
        name: t.Optional(t.String())
    })
})

app.listen(5000, (server) => {
    console.log(`> App is listening at: ${server.url.origin}`)
})
```

### What is the expected behavior?

body is {}

### What do you see instead?

"Failed to parse body" in response

### Have you try removing the `node_modules` and `bun.lockb` and try again yet?

Yes

**Comment by SaltyAom** [comment]
@misonomikadev I think you need to make sure that body is optional as well.

Something like this
```ts
app.post('/', ({ body }) => {
    console.log(body)

    return { ok: true } 
}, {
    type: 'multipart/form-data',
    body: t.Optional(t.Object({
        file: t.Optional(t.File()),
        name: t.Optional(t.String())
    }))
})
```

**Comment by misonomikadev** [comment]
Hmmmmm okay seem work to me, thanks
