### ISSUE TITLE
Global websocket publish() not possible

### ISSUE THREAD

**Issue by JohnRoseDev** [elysiajs/elysia#781]
### What version of Elysia is running?

1.1.6

### What steps can reproduce the bug?

Bun allows you to publish a message to all subscribers of a topic by calling publish() on the bun server instance (https://bun.sh/docs/api/websockets#pub-sub):

```
const server = Bun.serve({
  websocket: {
    // ...
  },
});

server.publish("the-group-chat", "Hello world");
```

If I'm not wrong, Elysia for now does not allow us to call publish() on the underlying bun server instance. We can only call publish on the exposed ws objects.

```
open(ws) {
  ws.subscribe('some-updates');
  ws.publish('some-updates', 'update'); // this will publish the message to every subscriber of the topic except the publisher
  myElysiaApp.publish('some-updates', 'update'); // this is not possible
},
```

### What is the expected behavior?

It would be great if either the elysia instance would expose the global publish method or if the ws.data object contained a reference to the underlying bun server.

**Comment by bibauporto** [comment]
const app = new Elysia() 
.ws('/ws', {
                beforeHandle(ws) {
                        try {
                                const token = ws.query.token || ''
                                const decoded = jwt.verify(
                                        token,
                                        String(process.env.TOKEN_SECRET),
                                ) as TDecoded

                                if (!decoded) {
                                        return ws.error(401, 'Unauthorized')
                                }
                        } catch (error: any) {
                                return ws.error(400, error.message || 'Bad Request')
                        }
                },
                open(ws) {
                        try {
                                ws.subscribe('broadcast')
                                console.log(`WebSocket connection opened: ${ws.id}`)
                                //log number of clients connected
                                console.log(`Clients connected: ${app.server?.pendingWebSockets}`)
                        } catch (error) {
                                console.error('WebSocket connection error:', error)
                        }
                },
                close(ws) {
                        ws.unsubscribe('broadcast') // Unsubscribe from the channel
                        console.log(`WebSocket connection closed: ${ws.id}`)
                },
        })

export const io = (event: string, data?: any) => {
        try {
                const payload = JSON.stringify({ event, data })
                app.server?.publish('broadcast', payload)

                
        } catch (error) {
                console.error('Error sending message:', error)
                throw error
        }


This is working

**Comment by ChampClarinet** [comment]
> ```
>   const app = new Elysia().ws('/ws', {
>             beforeHandle(ws) {
>                     try {
>                             const token = ws.query.token || ''
>                             const decoded = jwt.verify(
>                                     token,
>                                     String(process.env.TOKEN_SECRET),
>                             ) as TDecoded
> 
>                             if (!decoded) {
>                                     return ws.error(401, 'Unauthorized')
>                             }
>                     } catch (error: any) {
>                             return ws.error(400, error.message || 'Bad Request')
>                     }
>             },
>             open(ws) {
>                     try {
>                             ws.subscribe('broadcast')
>                             console.log(`WebSocket connection opened: ${ws.id}`)
>                             //log number of clients connected
>                             console.log(`Clients connected: ${app.server?.pendingWebSockets}`)
>                     } catch (error) {
>                             console.error('WebSocket connection error:', error)
>                     }
>             },
>             close(ws) {
>                     ws.unsubscribe('broadcast') // Unsubscribe from the channel
>                     console.log(`WebSocket connection closed: ${ws.id}`)
>             },
>     })
> ```
> 
> ```
> export const io = (event: string, data?: any) => {
>         try {
>                 const payload = JSON.stringify({ event, data })
>                 app.server?.publish('broadcast', payload)
>  } catch (error) {
>                 console.error('Error sending message:', error)
>                 throw error
>       } 
> ```
> 
> This is working

Mine is not working. It results as app.server is null at app.server?.publish line

**Comment by bibauporto** [comment]
What version of elysia and Bun are you using?

**Comment by cameronwiebe** [comment]
I am having a similar issue as @ChampClarinet where `app.server` is resulting in `null`. My setup is a bit different than the example however. Here are some details:

Elysia `v1.1.21`
Bun `v1.1.30`

routes/chats/index.ts:
```TypeScript
import Elysia, { t } from "elysia";
import {
  insertMessage,
} from "../../../services/chats";
import { websocket } from "./websocket";

export const chatRoutes = new Elysia({ prefix: "/chats" })
  .post(
    "/:id/messages",
    async (ctx) => {
      const message = await insertMessage(ctx.params.id, "user", ctx.body.text);
      console.log(websocket.server) // Results in null
      return message;
    },
    {
      body: t.Object({
        text: t.String(),
      }),
    }
  )
  .use(websocket);
  ```
  
  routes/chats/websocket.ts:
  ```TypeScript
 import Elysia, { t } from "elysia";

export const websocket = new Elysia().ws("/", {
    body: t.Object({
        message: t.String()
    }),
    query: t.Object({
        id: t.String()
    }),
    open(ws) {
      try {
        ws.subscribe("broadcast");
        console.log(`WebSocket connection opened: ${ws.id}`);
      } catch (error) {
        console.error("WebSocket connection error:", error);
      }
    },
    message(ws, { message }) {
        const { id } = ws.data.query;
        ws.send({
            id,
            message,
            time: Date.now()
        })
    },
    close(ws) {
      ws.unsubscribe("broadcast"); // Unsubscribe from the channel
      console.log(`WebSocket connection closed: ${ws.id}`);
    }
  });
  ```
  
I am able to connect to the ws route and send messages just fine, however broadcasting messages from the post route is not possible due to `websocket.server` being null. 

Am I doing something wrong?

**Comment by ChampClarinet** [comment]
In my case, I solved with this way.
My intention is I want the websocket to handle subscription when data changes. So I implemented a broadcast function as follows
`export const broadcast = (server: Server) => {
  const data = get();

  server.publish("orders", JSON.stringify(data));
};`
ref: https://github.com/ChampClarinet/socket-example/blob/master/backend/src/ws/index.ts

And then I used it in afterHandle function in my CRUD module as follows
`export const CRUDHandler = new Elysia()
  .onAfterHandle(({ request, server }) => {
    if (request.method != "GET" && !!server) broadcast(server);
  })`
ref: https://github.com/ChampClarinet/socket-example/blob/master/backend/src/crud/index.ts

and it works! Feel free to look at my repository to guide yours, hope it helps!

My repository: https://github.com/ChampClarinet/socket-example (try looking in backend folder)

**Comment by bibauporto** [comment]
```
export const io = (event: string, data?: any) => {
	try {
		const payload = JSON.stringify({ event, data })
		app.server?.publish('broadcast', payload)

		// Resolve all pending long-polling requests
		while (pendingRequests.length > 0) {
			const pendingRequest = pendingRequests.shift()
			if (pendingRequest) {
				const { resolve, timeout } = pendingRequest
				clearTimeout(timeout) // Clear the timeout for the request
				resolve(payload) // Send the payload to the client
			}
		}
	} catch (error) {
		console.error('Error sending message:', error)
		throw error
	}
}```


Maybe make the server null safe, and wrap on a try catch.

**Comment by cameronwiebe** [comment]
Thanks y'all! @ChampClarinet your solution works for me! I can also reference `ctx.server` from my route in order to publish a message:

```TypeScript
import Elysia, { t } from "elysia";
import {
  insertMessage,
} from "../../../services/chats";
import { websocket } from "./websocket";

export const chatRoutes = new Elysia({ prefix: "/chats" })
  .post(
    "/:id/messages",
    async (ctx) => {
      const message = await insertMessage(ctx.params.id, "user", ctx.body.text);
      console.log(ctx.server) // This works!
      return message;
    },
    {
      body: t.Object({
        text: t.String(),
      }),
    }
  )
  .use(websocket);
  ```
  
  This solves my issue. I appreciate all the support!
