### ISSUE TITLE
Missing onResponse ?

### ISSUE THREAD

**Issue by tanishqmanuja** [elysiajs/elysia#799]
### What version of Elysia is running?

1.1.8

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

https://github.com/tanishqmanuja/todos-react-elysia/blob/main/server/src/lib/logger/index.ts

### What is the expected behavior?

Is was working in version Elysia v1.0.27, suddenly stopped version after updating deps :(

### What do you see instead?

![image](https://github.com/user-attachments/assets/78789f44-8500-4f04-bc76-b047a08592e8)

### Have you try removing the `node_modules` and `bun.lockb` and try again yet?

yes

**Comment by randompixel** [comment]
@tanishqmanuja 1.1 has breaking changes. See the https://github.com/elysiajs/elysia/blob/main/CHANGELOG.md#110---16-jul-2024

**Comment by tanishqmanuja** [comment]
Thank you, I was searching the docs but forgot the changelog file.
