### ISSUE TITLE
using JWT get Error  : Import named 'getSchemaValidator' not found in module 

### ISSUE THREAD

**Issue by bobwatcherx** [elysiajs/elysia#8]
i follow you tutorial this https://elysiajs.com/plugins/jwt.html

mycode :
```
.use(jwt({
        name:"jwtBego",
        secret:"myfist"
    }))
    .get("/masuk",async({jwt,cookie,setCookie,params})=>{
        setCookie('auth', await jwt.sign(params), {
            httpOnly: true,
            maxAge: 7 * 86400,
        })

        return `Sign in as ${cookie.auth}`
    })
```

but get error like this 
SyntaxError: Import named 'getSchemaValidator' not found in module '/home/minto/belajar/elysyaPro/elyapp/manelysia/node_modules/elysia/build/es/index.js'.
[nodemon] app crashed - waiting for file changes before starting...

whats solution

**Comment by SaltyAom** [comment]
What version of Elysia are you using?
This error likely happens if you're using `elysia =< 0.1.0`
