### ISSUE TITLE
Connection reset on large file upload

### ISSUE THREAD

**Issue by RaphaelNJ** [elysiajs/elysia#801]
### What version of Elysia is running?

latest

### What platform is your computer?

tested on a Linux 6.10.1 x86_64 unknown (nixos) and a virtual ubuntu 24.04 LTS (Linux 6.8.0-39-generic x86_64 x86_64)

### What steps can reproduce the bug?

on the following setup, the route is reached correctly when the file that was sent is quite small, but the route is not reached (no error messages or someting) if the file is too large (around a few hundred megabytes)

try with the small files :
```
$ curl -X POST -F "title=Your Title Here" -F "file=@small_file.zip" http://localhost:3000/upload
Your Title Here
```
and on the server side : 
```
$ bun run index.ts 
Blob (6.34 KB) {
  type: "application/zip"
}
```

but, with the large file, nothing happen nor is logged out:
```
$ curl -X POST -F "title=Your Title Here" -F "file=@large_file.zip" http://localhost:3000/upload
$
```
and on the server side :
```
$ bun run index.ts 
```

the code :

```
import { Elysia, t } from "elysia";

const app = new Elysia()
  .post(
    "/upload",
    ({ body }) => {
      console.log(body.file);
      return body.title;
    },
    {
      body: t.Object({
        title: t.String(),
        file: t.File(),
      }),
    },
  )
  .listen(3000);
  ```

### What is the expected behavior?

the large files are handled too

### What do you see instead?

noting happens without any error

### Have you try removing the `node_modules` and `bun.lockb` and try again yet?

yes

**Comment by SaltyAom** [comment]
This is probably because file size limit is 128MB by default.

To increase file size, please specify `maxRequestBodySize` as follows:
```ts
new Elysia({
	serve: {
		maxRequestBodySize: 600 * 1024 * 1024 // 600MB
	}
})
```

**Comment by IcyFoxe** [comment]
Hello, is this by any chance broken? I set larger file size, but the request just hangs and the API endpoint isn't even called.

**Comment by IcyFoxe** [comment]
@SaltyAom Sorry to ping you like this, but not sure if you've seen my comment since the issue is closed.

**Comment by kravetsone** [comment]
> @SaltyAom Sorry to ping you like this, but not sure if you've seen my comment since the issue is closed.

Can u add reproduction? If it would be file+ curl command it would be amazing 

But possibly more Bun issue (if it really issue)
