### ISSUE TITLE
Optional params don't work (NOT QUERY)

### ISSUE THREAD

**Issue by SupertigerDev** [elysiajs/elysia#805]
Same as #435 but invalidly closed.

This doesn't work: `/users/:id?`

The one @SaltyAom mentioned are these `/users?id=123` which work fine.

**Comment by bogeychan** [comment]
Hi, make sure to use the latest version of elysia (`1.1.11`) and clean re-install it with removing node_modules and bun.lockb.

I can't reproduce it on my end:

```ts
import { Elysia } from "elysia";

new Elysia().get("/users/:id?", ({ params: { id } }) => ({ id })).listen(8080);
```

http://localhost:8080/users/323
```json
{"id":"323"}
```
http://localhost:8080/users

```json
{}
```

**Comment by bogeychan** [comment]
If not, please share some code snipped to reproduce it properly

**Comment by SupertigerDev** [comment]
ohh my bad, seems like its working now. sorry.
