### ISSUE TITLE
Wrong inference of response in `afterResponse`, includes status code

### ISSUE THREAD

**Issue by BleedingDev** [elysiajs/elysia#810]
### What version of Elysia is running?

1.1.11

### What platform is your computer?

Microsoft Windows NT 10.0.26120.0 x64

### What steps can reproduce the bug?

1. Define response with status code
2. Try to use response in `afterResponse`
3. Observe the bug

### What is the expected behavior?

Response omits 200/401/... and keeps only body of the response, not status code. 

### What do you see instead?

It works in code (e.g. `duration` is defined on `response`), but is broken on type-level (e.g. suggests to use `response[200]?.duration` which results in `undefined`).

### Additional information

![image](https://github.com/user-attachments/assets/acf0b12f-c640-44b5-b659-ffd64781fb6e)

### Have you try removing the `node_modules` and `bun.lockb` and try again yet?

yes, but I use npm as package manager due to issues with Prisma in Nx Monorepo

**Comment by SaltyAom** [comment]
Fixed and published under [1.1.13](https://github.com/elysiajs/elysia/releases/tag/1.1.13) with test case included
see https://github.com/elysiajs/elysia/compare/1.1.12...1.1.13

If this doesn't fix the issue, feel free to tag me or reopen the issue.
