### ISSUE TITLE
server.requestIP returns null with specific Content-Type headers

### ISSUE THREAD

**Issue by memetrollsXD** [elysiajs/elysia#814]
### What version of Elysia is running?

^1.1.7

### What platform is your computer?

Linux 5.4.0-174-generic x86_64 x86_64

### What steps can reproduce the bug?

I have been going insane for a week straight.

Assume following context:
```typescript
import { Elysia } from 'elysia';
import mongoose from 'mongoose';
import cors from '@elysiajs/cors';
import oauth from './routes/oauth';
import uploadApi from './routes/upload';

mongoose.connect(...);

new Elysia()
    .derive(x => { return { ip: x.server?.requestIP(x.request) } })
    .onBeforeHandle(ctx => {
        if (!ctx.ip) console.log('No IP found');
    })
    .all('/test', x => `${x.ip?.address} ${(<any>x.body)?.name}`)
    .use(cors())
    .use(oauth)
    .use(uploadApi)
    .listen(8009);
```

### What is the expected behavior?

/test route should return IP regardless of body or method

### What do you see instead?

On GET: ::ffff:127.0.0.1 undefined

On POST (no body): ::ffff:127.0.0.1 undefined 

On POST (application/json): undefined aqua.gif

On POST (text/plain): undefined undefined

On POST (text/html): ::ffff:127.0.0.1 undefined 
On POST (content type empty):  ::ffff:127.0.0.1 undefined

And so on..

### Have you try removing the `node_modules` and `bun.lockb` and try again yet?

Yes

**Comment by kravetsone** [comment]
it is bun bug

**Comment by memetrollsXD** [comment]
> it is bun bug

Is it a known bug? I thought it would be an Elysia bug since it's related to the handling of the request rather than the implementation itself. It doesn't happen with just a simple GET request.

**Comment by kravetsone** [comment]
> > it is bun bug
> 
> Is it a known bug? I thought it would be an Elysia bug since it's related to the handling of the request rather than the implementation itself. It doesn't happen with just a simple GET request.

use Bun.sleep in bun serve for example

**Comment by memetrollsXD** [comment]
Tested with Bun.sleep(), indeed returns undefined

**Comment by kravetsone** [comment]
> Tested with Bun.sleep(), indeed returns undefined

A lot of things with requestIp broken(
You can search issues in elysia (marked as blocked) and bun
