### ISSUE TITLE
HTML plugin returns JSX as content-type = text/plain;charset=utf-8

### ISSUE THREAD

**Issue by hari-narasimhan** [elysiajs/elysia#815]
### What version of Elysia is running?

elysia@1.1.12

### What platform is your computer?

Darwin 23.6.0 arm64 arm

### What steps can reproduce the bug?

bun create elysia
bun add @elysiajs/html  

make the necessary changes to tsconfig.json

rename index.ts to index.tsx
Copy the example from html plugin

`import { Elysia } from "elysia";
import { html, Html } from '@elysiajs/html'

const app = new Elysia()
.get("/", () => (
  <html lang='en'>
      <head>
          <title>Hello World</title>
      </head>
      <body>
          <h1>Hello World</h1>
      </body>
  </html>
)).listen(3000);

console.log(
  `🦊 Elysia is running at ${app.server?.hostname}:${app.server?.port}`
);
`

### What is the expected behavior?

To render the HTML

### What do you see instead?

`
<html lang="en"><head><title>Hello World</title></head><body><h1>Hello World</h1></body></html>
` 

### Have you try removing the `node_modules` and `bun.lockb` and try again yet?

yes

**Comment by HigherOrderLogic** [comment]
Did you `.use(html())`? Cause I dont see that in your code.

**Comment by hari-narasimhan** [comment]
Oops... sincere apologies, use(html()) indeed was missing, thanks. It is working now! thanks a lot.
