### ISSUE TITLE
comparison with golang? (fiber or net/http)

### ISSUE THREAD

**Issue by terlan4** [elysiajs/elysia#82]
So according to ratio of fiber and elysia with express, does it mean elysia and fiber-go framework is almost at the same speed?
I would be happy to see benchmarking of bun frameworks against go frameworks(fiber, gin, net/http). Thank you

![image](https://github.com/elysiajs/elysia/assets/138553763/98d34253-cfd0-4d91-9008-a8464803a04c)
![image](https://github.com/elysiajs/elysia/assets/138553763/4e6e1ce9-d3e0-451e-a5d6-67a9631d89e6)
>fiber benchmark source: https://docs.gofiber.io/extra/benchmarks

**Comment by Tirke** [comment]
You can find such comparison here: https://web-frameworks-benchmark.netlify.app/result?l=go,javascript

**Comment by Fecony** [comment]
> @Tirke could you please tell me how this benchmark site compares? Because I dont think that python libraries slower than javaascript, even slower than express.

Python web frameworks are slow. And you can literally go to the benchmark page and see how they are running

**Comment by Tirke** [comment]
Yes elysia is quite performant, on the level of the best Rust / Go framework, you should not be surprised by this fact.

**Comment by Tirke** [comment]
Choosing a framework or language involves many factors. Some questions to consider:

Are you working in a team?
Is the team more proficient in JS or Go?
What is the nature of your project? Are you building a backend with extensive computations?
The differences between languages or frameworks might not be very noticeable unless you're working on highly computational tasks.

From my personal experience, I find Go to be way more mature compared to Bun at the moment. For serious production use, especially if you're looking to build a product or start a company, I'd be cautious about using Bun with Elysia. However, for personal projects or exploration, go ahead! I've experimented quite a bit with Bun and Elysia and have found it amazing.

**Comment by waghanza** [comment]
Hi,

Maintainer of the above project here (not elysia but the benchmarking project).

I am also curious to see how elysia has 18x more rps than express.

Feel free to ask me any questions, but maybe on https://github.com/the-benchmarker, in order no to make some noise here

Regards,

**Comment by moeidsaleem** [comment]
So is Elysia faster then Go Gin? They claim on the website but is it really faster then GO Gin?
