### ISSUE TITLE
`params` in hooks inside prefixed groups are incorrectly typed `never`

### ISSUE THREAD

**Issue by joulev** [elysiajs/elysia#820]
### What version of Elysia is running?

1.1.11

### What platform is your computer?

Darwin 23.6.0 arm64 arm

### What steps can reproduce the bug?

Type-check the following code:

```tsx
import Elysia, { t } from "elysia";

const idRoutes = new Elysia({ prefix: "/:id" })
  // .guard({ params: t.Object({ id: t.String() }) }) // Without this it doesn't work
  .onBeforeHandle(({ params }) => console.log(params.id))
  .get("/", ({ params }) => console.log(params.id));
```

### What is the expected behavior?

The type should pass, i.e. `params.id` in `.onBeforeHandle` should be a `string`, like in the `.get` call, because the prefix already contains a dynamic param.

### What do you see instead?

TypeScript error, as `params` in the `.onBeforeHandle` call is of type `never`.

### Additional information

If you uncomment the `.guard` line, it works. But of course that's a workaround, and it should work without the workaround above.

Though, the Elysia type system is so good that even a typing workaround still looks really really neat.

### Have you try removing the `node_modules` and `bun.lockb` and try again yet?

Yes

**Comment by SaltyAom** [comment]
Fixed and published under [1.1.13](https://github.com/elysiajs/elysia/releases/tag/1.1.13) with test case included
see https://github.com/elysiajs/elysia/compare/1.1.12...1.1.13

If this doesn't fix the issue, feel free to tag me or reopen the issue.
