### ISSUE TITLE
`.resolve` doesn't work with `aot: false`

### ISSUE THREAD

**Issue by bogeychan** [elysiajs/elysia#834]
### What version of Elysia is running?

1.1.13

### What platform is your computer?

WSL Ubuntu

### What steps can reproduce the bug?

```ts
import { Elysia } from "elysia";

new Elysia({ aot: false })
  .resolve(async () => {
    return {
      user: "FOO",
    };
  })
  .get("/", ({ user }) => {
    console.log("GET", user);
    return "Hello Elysia";
  })
  .listen(8080);
```

`GET http://localhost:8080/`

### What is the expected behavior?

`Hello Elysia`

### What do you see instead?

`{"user":"FOO"}`

### Additional information

`.get` handler doesn't get executed.

---

reported on [discord](https://discord.com/channels/1044804142461362206/1285979675629453346)

### Have you try removing the `node_modules` and `bun.lockb` and try again yet?

yes

**Comment by jasperdunn** [comment]
Bump

**Comment by bogeychan** [comment]
Closing this, as it seems to work with the latest Elysia version: `1.2.6`
