### ISSUE TITLE
Invalid `onAfterResponse` typing

### ISSUE THREAD

**Issue by nxht** [elysiajs/elysia#838]
### What version of Elysia is running?

1.1.13

### What platform is your computer?

Linux 5.15.153.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

```ts
import Elysia from 'elysia';

const app = new Elysia()
  .onAfterResponse((ctx) => {
    ctx.request;
  })
```

### What is the expected behavior?

`ctx` is typed correctly and `ctx.request` exists

### What do you see instead?

`ctx` is inferred as `never` in typescript

### Additional information

Same issue doesn't happen on 1.1.12. Might be related with #810

### Have you try removing the `node_modules` and `bun.lockb` and try again yet?

Yes

**Comment by bompus** [comment]
I commented on a commit actually, but I don't think the author saw it. It appears the unit test for this was commented out, so the regression wasn't caught. https://github.com/elysiajs/elysia/blob/61096846ecf37b481231de3c5ff754355313c903/test/types/index.ts#L1969

**Comment by 7f8ddd** [comment]
It's also only in the plugin itself, any plugins that use it will have types.

**Comment by nathankleyn** [comment]
We also have this exact same issue from `1.1.13` onwards. In our case, it's a logging plugin where all of the params to `.onAfterResponse` now type as `never`:

```ts
return new Elysia({
  name: "logger",
})
  .derive(() => {
    return {
      startTime: performance.now(),
    };
  })
  .onAfterResponse({ as: "global" }, ({ request, set, startTime }) => {
    // request, set and startTime are all `never`
  });
```

**Comment by crishoj** [comment]
Wrong types with 1.1.16 too:

<img width="748" alt="image" src="https://github.com/user-attachments/assets/37de001b-76ae-4952-b443-60d639e7c811">

**Comment by zoto-ff** [comment]
same here
![image](https://github.com/user-attachments/assets/97512299-b8d7-4aae-bf65-8c095f634ae8)

**Comment by 7f8ddd** [comment]
@SaltyAom We gonna have beef real soon if you don't stop watching anime girls and fix this, on folk n em
