### ISSUE TITLE
Async derive

### ISSUE THREAD

**Issue by Zig1375** [elysiajs/elysia#84]
Add possibility to return Promise in derive.
I'd like to get user info from db in derive and set it to a context variable.
Getting user is an async method.

```ts
app.derive(async function(context) {
  const user = await loadUser();
  return { user };
});
```

Right now, the "user" variable is not added to the context

**Comment by SaltyAom** [comment]
You should be able to use async derive automatically.

Can you provide me what Elysia version are you using?

**Comment by SaltyAom** [comment]
Since there's no active discussion, I'm closing this issue.

Feels free to reopen if you have anything regarding to this.
