### ISSUE TITLE
return error no longer works in derive() on 1.1.18 

### ISSUE THREAD

**Issue by sunnylqm** [elysiajs/elysia#865]
### What version of Elysia is running?

1.1.18

### What platform is your computer?

Darwin 24.0.0 arm64 arm

### What steps can reproduce the bug?

```
export const checkLogined = new Elysia().derive(
  { as: 'scoped' },
  ({ headers, error }) => {
    const token = headers['x-accesstoken'];
    const session = token && checkTokenWithInfo(token, 'user');
    if (!session) {
      return error(401, {
        message: 'Unauthorized',
      });
    }
    return {
      userId: session.uid,
    };
  },
);
```

### What is the expected behavior?

it worked fine before 1.1.18

### What do you see instead?

![QQ_1728179750160](https://github.com/user-attachments/assets/b8726a98-5f84-48ea-b255-4eeee7da8ba4)

### Have you try removing the `node_modules` and `bun.lockb` and try again yet?

yes

**Comment by SaltyAom** [comment]
fix with 93d457b
