### ISSUE TITLE
console logged cookie value

### ISSUE THREAD

**Issue by m1212e** [elysiajs/elysia#869]
### What steps can reproduce the bug?

Running 

```
		cookie[tokensCookieName].expires = undefined;
```
with any value, be it undefined or something else completely causes the cookie to be logged to the console. Thats probably not what should happen!

**Comment by crishoj** [comment]
@SaltyAom this has been fixed, suggest closing

**Comment by crishoj** [comment]
(fixed in 22b79ced2f0e710ebd2b9f68146f926c00f8b2f3)
