### ISSUE TITLE
Websocket not typesafe anymore (between 0.5.25 & 0.6.0-alpha.0)

### ISSUE THREAD

**Issue by titouv** [elysiajs/elysia#87]
In 0.5.25, i can only `ws.send`and `ws.publish` messages which correspond to the response type defined in the ws handler.

In 0.6.0-alpha.0, i can write anything and typescript doesn't error. Maybe the validation still works at runtime but in the IDE, this doesn't work.

Maybe this is linked to this commit but not so sure: 
https://github.com/elysiajs/elysia/commit/481a8f859a5fe9e31d76dbd14c59921b4e6b3cad#diff-c54113cf61ec99691748a3890bfbeb00e10efb3f0a76f03a0fd9ec49072e410a

**Comment by SaltyAom** [comment]
Should be fixed in 0.7 #103, as we essentially rewritten Web Socket again.

https://elysiajs.com/blog/elysia-07.html#rewritten-web-socket
