### ISSUE TITLE
Providing a default function in param type causes crash

### ISSUE THREAD

**Issue by klydra** [elysiajs/elysia#874]
### What version of Elysia is running?

1.1.20

### What platform is your computer?

Not platform specific

### What steps can reproduce the bug?

Provide a Type with a default value that is determined by a function.

```ts
import { Elysia, t } from "elysia";

const elysia = new Elysia().get("/:id", ({ params: { id } }) => id, {
  params: t.Object({
    id: t.String({
      default: () => "",
    }),
  }),
});
```

### What is the expected behavior?

The request to return the ID String.

### What do you see instead?

A response of `ValueClone: Unable to clone value` with code `500`.

**Comment by K4leri** [comment]
i wll add `t.Optional(t.Date())` examples cause they are still arround validation

```ts
const schema = t.Object({
  startDate: t.Optional(t.Date()),
  endDate: t.Optional(t.Date()),
})

new Elysia().get(
        "/aid/filter",
        async () => 'hi',
        {
          query: schema,
        }
      )
```
fails on request with validation error
```
{
    "error": {
        "schema": {
            "anyOf": [
                {
                    "type": "Date"
                },
                {
                    "format": "date",
                    "default": "2024-10-04T18:25:10.250Z",
                    "type": "string"
                },
                {
                    "format": "date-time",
                    "default": "2024-10-04T18:25:10.250Z",
                    "type": "string"
                }
            ]
        },
        "path": "/startDate",
        "error": {
            "code": "VALIDATION",
            "status": 422,
            "type": "property",
            "validator": {
                "type": "Date"
            },
            "value": null
        },
        "originalLine": 3,
        "originalColumn": 10
    }
}
```

**Comment by klydra** [comment]
Hey @K4leri,
I appreaciate the comment, but I don't think that is really the same error, right?
Wouldn't it hence make more sense in a separate issue? :D

**Comment by klydra** [comment]
As I was just developing, I noticed that my expected functionalty isn't even supposed to work. I was previously using the latest version of typebox where it is in fact possible to provide a function as a default value. But in the version of typebox elysia depends on, it was in fact not supported yet.

The fix would therefore be upgrading the version of typebox under the hood, but which I'm sure would in turn probably cause other problems and probably wouldn't be easy.

**Comment by K4leri** [comment]
@klydra just use 
```ts
// package.json
  "overrides": {
    "@sinclair/typebox": "0.32.34"
  }
  ```
