### ISSUE TITLE
Proper way to access response code in `onResponse` hook?

### ISSUE THREAD

**Issue by jayden-chan** [elysiajs/elysia#88]
I want to use the `onResponse` hook to print a log message every time a response is generated. Right now I am reading the value of `set.status` to determine the HTTP status code of the response. However in cases where Elysia responds early due to an error, the value of `set.status` is incorrect. For example if body validation fails, the server responds to the client with code 400 but the value of `set.status` is 500.

Is this the wrong way of determining info about the response? I did not see any other way in the docs or function signature. From what I can tell, the response itself isn't actually accessible in the `onResponse` hook.

**Comment by SaltyAom** [comment]
This should be fixed with Elysia 0.6.11

> Bug fix:
> - [#86](https://github.com/elysiajs/elysia/issues/86) Group prefix repeating on inline function callback
> - [#88](https://github.com/elysiajs/elysia/issues/88), onResponse hooks validation return non 400

Feels free to reopen the issue if the problem still persists.

**Comment by jayden-chan** [comment]
@SaltyAom The problem persists. Failed hooks validation is not the only case where `set.status` differs from the actual returned response.

Here is a minimal reproduction example:
```typescript
import { Elysia } from "elysia";

new Elysia()
  .onResponse(({ set }) => {
    console.log(`Response code: ${set.status}`);
  })
  .get("/", () => {
    return new Response("Not Found", {
      status: 404,
    });
  })
  .listen(3000);
```

Performing a `curl` request returns 404 as expected:
```
$ curl http://localhost:3000/ --verbose
* processing: http://localhost:3000/
*   Trying [::1]:3000...
* Connected to localhost (::1) port 3000
> GET / HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/8.2.1
> Accept: */*
>
< HTTP/1.1 404 Not Found
< content-type: text/plain;charset=utf-8
< Date: Sat, 09 Sep 2023 02:30:28 GMT
< Content-Length: 9
<
* Connection #0 to host localhost left intact
Not Found%
```

but the code prints:
```
Response code: 200
```

The issue is that `set` isn't always used to actually set the response code. I think for the `onResponse` API to make sense, the callback needs to have access to the actual `Response` object that was sent to the client. I'm not sure if this is possible but I think it makes the most sense.

**Comment by otherguy** [comment]
@SaltyAom can confirm on 0.6.24.
