### ISSUE TITLE
Cannot return error on resolve when set ElysiaConfig aot to false

### ISSUE THREAD

**Issue by thanatpp** [elysiajs/elysia#888]
### What version of Elysia is running?

"elysia": "1.1.22"

### What platform is your computer?

Darwin 24.0.0 arm64 arm

### What steps can reproduce the bug?

```
import Elysia, { error } from "elysia";

const app = new Elysia({ aot: false })
  .resolve(() => {
    return error(401);
  })
  .get("/hello", () => "Hello")
  .listen(3000);
```

### What is the expected behavior?

When we call endpoint `/hello` should be response an error status code `401`.

### Have you try removing the `node_modules` and `bun.lockb` and try again yet?

yes

**Comment by sgmustafi** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
