### ISSUE TITLE
Conditional Route?

### ISSUE THREAD

**Issue by QuentinDutot** [elysiajs/elysia#89]
The 0.4 release blog post mentions conditional route: https://elysiajs.com/blog/elysia-04.html#conditional-route

But nothing about that in the documentation and when using it: "Property 'if' does not exist on type 'Elysia"

Was the feature remove?

---------------------------

`.use((app) => (isProduction() ? app.use(prodPlugin()) : app))`
vs
`.if(isProduction(), (app) => app.use(prodPlugin()))`

**Comment by SaltyAom** [comment]
Yes, this feature is removed due to confusion naming convention.

You can use:
```ts
app
    .use((app) => (isProduction() ? app.use(prodPlugin()) : app))
```

as it's exactly the same thing under the hood.
