### ISSUE TITLE
`normalize: true` mutates objects used in responses

### ISSUE THREAD

**Issue by crishoj** [elysiajs/elysia#897]
### What version of Elysia is running?

1.1.23

### What platform is your computer?

macOS

### What steps can reproduce the bug?

With [normalize](https://elysiajs.com/patterns/configuration.html#normalize) `true` (the default), Elysia will _mutate_ objects used in responses.

Consider this example with a long-lived object `people`:

```ts
import {Elysia, t} from 'elysia'

const people = new Map<number, object>([
    [1, {name: 'Jane Doe', age: 80}],
])

const app = new Elysia()
    .get('/names/:id', ({params: {id}}) => {
        return people.get(id)
    }, {
        params: t.Object({id: t.Number()}),
        response: t.Object({name: t.String()})
    })

console.log('people before request:', people)
await app.handle(new Request('http://localhost/names/1'))
console.log('people after request:', people)
```

### What is the expected behavior?

```
people after request: Map(1) {
  1: {
    name: "Jane Doe",
    age: 80,
  },
}
```

From a developer perspective, I expect Elysia to not directly mutate objects used in a response body.

If response normalization is active, I expect cleaning to happen on a (deep) clone of the object passed as response body.

### What do you see instead?

```
people after request: Map(1) {
  1: {
    name: "Jane Doe",
    // ⚠️ Notice that the `age` property is now missing from the long-lived object
  },
}
```

Objects used in responses are directly mutated — additional properties are deleted by the Typebox cleaner:

```ts
if (IsSchema(additionalProperties) && Check(additionalProperties, references, value[key])) {
    value[key] = Visit(additionalProperties, references, value[key]);
    continue;
}
delete value[key];
```

### Additional information

This caught me off guard and led to subsequent errors in my app where properties in a long-lived object were suddenly undefined.

For improved DX, please consider doing a `structuredClone()` of objects before normalization.

### Have you try removing the `node_modules` and `bun.lockb` and try again yet?

Yes

**Comment by crishoj** [comment]
@SaltyAom — what do you think about the proposed change https://github.com/crishoj/elysia/commit/d759a6f59bf01ca3e7486375a2533cbdf327af3c?

Also removed redundant logic — all three cases do exactly the same thing.

**Comment by sgmustafi** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by kravetsone** [comment]
I think we shouldn't do it by default.
It as typebox do
And structuredClone is perfomance killer

**Comment by crishoj** [comment]
I would be happy with an option as well.

Perhaps:
- `clean` → mutates
- `normalize` → clone then clean (doesn't mutate)
- `none` → no normalization, extra attributes in responses causes validation error

**Comment by crishoj** [comment]
I would argue that DX should also be an important goal. Frankly speaking, seeing long-lived objects referenced in responses being _mutated_ by Elysia/Typebox was a terrifying gotcha for me.

Perhaps a reasonable default could be to _error_ in case response doesn't match the type sanctioned by the schema.

Then, let the developer make an explicit choice:
- Use mutating cleaning to minimize response time.
- Use clone+clean to maintain type safety.

**Comment by kravetsone** [comment]
> I would argue that DX should also be an important goal. Frankly speaking, seeing long-lived objects referenced in responses being _mutated_ by Elysia/Typebox was a terrifying gotcha for me.
> 
> Perhaps a reasonable default could be to _error_ in case responses don't match the type sanctioned by the schema.
> 
> Then, let the developer make an explicit choice:
> - Use mutating cleaning to minimize response time.
> - Use clone+clean to maintain type safety.

Long-lived objects is not so often case
If u need to prevent mutation just clone it
But i agree that it should be more warned in the docs

**Comment by yazd** [comment]
I think this should be revisited. The implemented solution penalizes, what I would assume, the majority of normal uses, for the benefit of a specialized use-case, where a simple solution exists (which is applying `structuredClone` in the code itself).

If there is agreement, I can make the code changes necessary to revert this and to add a note in the docs.

**Comment by kravetsone** [comment]
> I think this should be revisited. The implemented solution penalizes, what I would assume, the majority of normal uses, for the benefit of a specialized use-case, where a simple solution exists (which is applying `structuredClone` in the code itself).
> 
> If there is agreement, I can make the code changes necessary to revert this and to add a note in the docs.

sadly that @SaltyAom merge https://github.com/elysiajs/elysia/pull/905

idk why we should decrease perfomance

**Comment by crishoj** [comment]
I could live with using `normalize: false` and making sure myself that no additional properties are present.

Or, ideally, a way to explicitly configure normalization to mutate or not.

**Comment by kravetsone** [comment]
> Я мог бы смириться с использованием `normalize: false`и убедиться самостоятельно в отсутствии дополнительных свойств.
> 
> Или, в идеале, способ явно настроить нормализацию на мутацию или нет.

u can use structuredClone on your side if it matter

**Comment by crishoj** [comment]
The core issue here is weighing DX against performance.

Having my long-lived service objects mangled with `delete` was a huge gotcha for me, and I can imagine such an experience could discourage developers from relying on Elysia. I think that would be a shame.

**Comment by kravetsone** [comment]
> The core issue here is weighing DX against performance.
> 
> Having my long-lived service objects mangled with `delete` was a huge gotcha for me, and I can imagine such an experience could discourage developers from relying on Elysia. I think that would be a shame.

it is really edge case

long-lived object with additional for response params

but it should be documented and warned more
