### ISSUE TITLE
dynamic mode, Can't modify immutable headers

### ISSUE THREAD

**Issue by implicit-invocation** [elysiajs/elysia#91]
using elysia with CF worker's durable object
```
app.get("/stream", (req) => {
  const id = req.env.STREAM.idFromName("global");
  const streamServer = req.env.STREAM.get(id);

  return streamServer.fetch(req.request);
});
```

but the error `Can't modify immutable headers` is thrown every time.

Found that mapResponse (https://github.com/elysiajs/elysia/blob/820b1e7e8c86ddc572e83d6d95b00443fc65ff68/src/handler.ts#L203) does that and mapCompactResponse doesn't. 
Maybe it's the dynamic-handle (https://github.com/elysiajs/elysia/blob/820b1e7e8c86ddc572e83d6d95b00443fc65ff68/src/dynamic-handle.ts#L274)
the logic of using mapCompactResponse is not there
unlike this (https://github.com/elysiajs/elysia/blob/820b1e7e8c86ddc572e83d6d95b00443fc65ff68/src/compose.ts#L641)

**Comment by implicit-invocation** [comment]
maybe it's this condition (https://github.com/elysiajs/elysia/blob/820b1e7e8c86ddc572e83d6d95b00443fc65ff68/src/handler.ts#L169)

I am trying to return a 101 protocol switching with a websocket connection

**Comment by SaltyAom** [comment]
Closing as websocket is now implemented in the core of Elysia.

Please use `new Elysia().ws` instead of manually handling websocket, thanks.
