### ISSUE TITLE
app.server.port is not same app.listen(port)

### ISSUE THREAD

**Issue by baramofme** [elysiajs/elysia#917]
### What version of Elysia is running?

1.1.24

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

set port with app.listen method. 
and then, the print app.server.port variable

### What is the expected behavior?

The app.server.port value should match the port number specified in the app.listen method

```
const app = new Elysia()
.listen(3002);
```

### What do you see instead?

always same 3000

```
$ bun run --watch src/index.ts
🦊 Elysia is running at localhost:3002
Started server http://localhost:3000
```

### Additional information

because of this bug, I cannot run another server using port 3000.

I am unable to start another server using port 3000 at the same time as elysiajs. It seems that elysia is turning on faster and blocking port 3000.

If you think about it, if you position the elysiajs startup order behind another server that uses 3000 ports, it will work.

### Have you try removing the `node_modules` and `bun.lockb` and try again yet?

yes, I did it.

**Comment by crishoj** [comment]
Tried to reproduce:

```ts
import Elysia from 'elysia'

const app = new Elysia()
    .listen(3002);

console.log('app.server.port =', app.server.port)
```

Output:

```
app.server.port = 3002
```

If you could post a minimal code example to reproduce the issue, it would be helpful for diagnosing the issue.

**Comment by SaltyAom** [comment]
Hi, I want to tackle this problem again.

I'm unable to reproduce this issue and the issue is on stale.
If the problems still occurs, feels free to reopen this issue again.

**Comment by Tohjuler** [comment]
Hi, i found the issue, it happens when you have ``export default app;``
```ts
import Elysia from 'elysia'

const app = new Elysia()
    .listen(3002);

export default app;

console.log('app.server.port =', app.server?.port)
```
Here is the code that has the issue, and it outputs.
```
app.server.port = 3002
Started development server: http://localhost:3000
```

It seem like it is bun that does something when you export a bun serve. 
You can change the port with ``--port`` or ``-p``, but as elysia exposes a api and bun does it can't use the same port.
I use this dev command ``bun run --port $(((RANDOM % $((11000 - 10000))) + 10000)) --watch src/index.ts`` it just find a random port between 10000 and 11000, there is not a lot of app running in that range so it should be fine.

**Comment by crishoj** [comment]
You are right, `export default` causes this.

I was not aware, but it appears to be the [documented](https://bun.sh/docs/api/http#export-default-syntax) behavior of Bun:

> when Bun sees a file with a default export containing a fetch handler, it passes it into Bun.serve under the hood

**Comment by baramofme** [comment]
@SaltyAom @crishoj Hello. 

Regarding the current issue, is the following correct?

As stated in this document, this is related to [Bun's export default behavior](https://bun.sh/docs/api/http#export-default-syntax)  so please comment out or avoid using the following code:

```
// export default app;
```

**Comment by crishoj** [comment]
Indeed, you should avoid using `export default app` in your main file.

May I know what the motivation for exporting was? In case you need API types for an Eden Treaty client, you can use `export type ...`.

**Comment by Tohjuler** [comment]
You use the export for test, so you can make calls to the api in the test.

**Comment by crishoj** [comment]
Makes sense.

Then, instead of `export default app` you could `export { app }`.

**Comment by baramofme** [comment]
@crishoj OK, understood. I will use `export {app}' instead of `export default app'.
