### ISSUE TITLE
typings break with exactOptionalPropertyTypes

### ISSUE THREAD

**Issue by hesxenon** [elysiajs/elysia#93]
Sadly the types break when specifying `exactOptionalPropertyTypes` in the tsconfig :/

E.g. the guard function only accepts `never` and the schema parameter has the fixed type `undefined`

**Comment by sinclairzx81** [comment]
@hesxenon Hi,

Not sure if this is related, but if you use the `exactOptionalPropertyTypes` setting in `tsconfig.json`, it should be possible to have `Elysia.t` adopt the same runtime assertions by setting the `ExactOptionalPropertyTypes` switch in TypeBox.

```typescript
import { TypeSystemPolicy } from '@sinclair/typebox/system'

// Only enable if 'exactOptionalPropertyTypes' is true in tsconfig.json
TypeSystemPolicy.ExactOptionalPropertyTypes = true
```
What this does is enforces runtime checking inline the TS setting.

```typescript
const T = Type.Object({ x: Type.Optional(Type.String()) })

Value.Check(T, { x: 'hello' })   // ok
Value.Check(T, { })              // ok
Value.Check(T, { x: undefined }) // fail - undefined not assignable to optional `string'
```
The inferred types should line up as expected (as exactOptionalPropertyTypes inference is governed by the TS compiler and language service). Also, you would typically set this variable somewhere near the applications entry module, but have a chat to @SaltyAom how best to enable in Elysia (it might be possible for Elysia to provide an API to this setting)

Hope this helps!
S

**Comment by habiiev** [comment]
Encountered the same problem, but when trying to provide body schema for the request.

This code will be ok without exactOptionalPropertyTypes:

```typescript
import { Elysia, t } from "elysia";

const app = new Elysia()
    .get("/", () => "Hello Elysia")
    .post("/post", ({ body }) => ({ body }), { body: t.Object({}) })
    .listen(3000);

console.log(`🦊 Elysia is running at ${app.server?.hostname}:${app.server?.port}`);
```

But if I set exactOptionalPropertyTypes to true, tsc will throw an error:

```shell
src/index.ts:5:46 - error TS2345: Argument of type '{ body: TObject<{}>; }' is not assignable to parameter of type 'undefined'.

5     .post("/post", ({ body }) => ({ body }), { body: t.Object({}) })
                                               ~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in src/index.ts:5
```
