### ISSUE TITLE
Plugin html type error

### ISSUE THREAD

**Issue by Tetreur** [elysiajs/elysia#94]
Hello, I would like to report that I'm experiencing an html plugin type error

```ts
// index.ts

import { Elysia } from 'elysia'
import { html } from '@elysiajs/html'

const page = `<!DOCTYPE HTML>
<html lang="en">
    <head>
        <title>Hello World</title>
    </head>
    <body>
        <h1>Hello World</h1>
    </body>
</html>`

new Elysia()
    .use(html())
    .get('/', () => page)
    .get('/html', ({ html }) => html(page))
//                   ⇑ Type Error
    .listen(8080)
```
The Error ->

```ts
 Property 'html' does not exist on type:
 Context<
  {
    body: unknown; 
    params: Record<never, string>;
    query: undefined; 
    headers: undefined;
    response: unknown; 
  },
  {}
  > & {}
```
So it's seems like that passing the `html` plugin in the `use` function doesn't make it available later in the get callback function :/

elysia: 0.6.11
@elysiajs/js: 0.6.0
typescript: 5.0.0

**Comment by Burtonium** [comment]
If you want a workaround for now you can do this:

```
// index.ts

import { Elysia } from 'elysia'
import sanitize from 'sanitize-html';
import { html } from '@elysiajs/html'

const page = `<!DOCTYPE HTML>
<html lang="en">
    <head>
        <title>Hello World</title>
    </head>
    <body>
        <h1>Hello World</h1>
    </body>
</html>`

new new Elysia<"", { store: {}; request: { html(v: string): Response, sanitize: typeof sanitize }; schema: {}; error: {}; meta: { schema: {}; defs: {}; exposed: {}; }; }>()
    .use(html())
    .get('/', () => page)
    .get('/html', ({ html }) => html(page))
//                   ⇑ Type Error
    .listen(8080)
```

**Comment by Burtonium** [comment]
So this seems fixed with the current version of elysia. Had some persistent type issues while fixing it which required me to start a reproduction project adding dependencies one by one until I came to the exact project I had before but without the type issues.

Here's the commit that fixed my typing issues here: https://github.com/ethanniser/the-beth-stack/commit/84f814b50a3be008be32b32ce3cd4e005092f38c

Good luck, @Tetreur

**Comment by BastienGenin** [comment]
Tyvm for letting me know @Burtonium
