### ISSUE TITLE
`t.Integer()` doesn't work with query params

### ISSUE THREAD

**Issue by bogeychan** [elysiajs/elysia#949]
### What version of Elysia is running?

1.1.26

### What platform is your computer?

WSL Ubuntu

### What steps can reproduce the bug?

```ts
// test.test.ts
import { test, expect } from "bun:test";
import { Elysia, t } from "elysia";

test("Integer query param", async () => {
  const app = new Elysia().get("/", ({ query: { limit } }) => limit, {
    query: t.Object({
      limit: t.Integer(),
    }),
  });

  await app.modules;

  const response = await app.handle(new Request(`http://localhost/?limit=1`));

  expect(response.status).toBe(200);
});
```

`bun test`

### What is the expected behavior?

test pass

### What do you see instead?

test fails:

```
Expected: 200
Received: 422
```

### Additional information

Should work out of the box, like `t.Number()`. We can't use `t.Number()` here because it allows floating point numbers.

---

reported on [discord](https://discord.com/channels/1044804142461362206/1044804143455420539/1319322309173182485)

### Have you try removing the `node_modules` and `bun.lockb` and try again yet?

yes

**Comment by scarf005** [comment]
I'm interested in opening a PR.
