### ISSUE TITLE
Default validation values doesn't work with `aot: false`

### ISSUE THREAD

**Issue by bogeychan** [elysiajs/elysia#950]
### What version of Elysia is running?

1.1.26

### What platform is your computer?

WSL Ubuntu

### What steps can reproduce the bug?

```ts
// test.test.ts
import { test, expect } from "bun:test";
import { Elysia, t } from "elysia";

test("Default values with aot: false", async () => {
  const app = new Elysia({ aot: false }).get(
    "/",
    ({ query: { limit } }) => limit,
    {
      headers: t.Object({
        yay: t.String({
          default: "yay",
        }),
      }),
      query: t.Object({
        limit: t.String({
          default: "yay",
        }),
      }),
    }
  );

  await app.modules;

  const response = await app.handle(new Request(`http://localhost`));

  expect(response.status).toBe(200);
});
```

### What is the expected behavior?

test pass

### What do you see instead?

test fail

```
Expected: 200
Received: 422
```

### Additional information

It doesn't work for both `headers` and `query`, maybe others too. You can just comment out parts of the above code sample.

---

reported on [discord](https://discord.com/channels/1044804142461362206/1044804143455420539/1319352533403177011)

### Have you try removing the `node_modules` and `bun.lockb` and try again yet?

yes

**Comment by azezsan** [comment]
aot being off causes weird and unexpectable behaviors in many places that shouldn't be affected by it #946 #948, the implementation needs reconsideration
