### ISSUE TITLE
Swagger Plugin Respects OS Dark-Mode

### ISSUE THREAD

**Issue by gdibble** [elysiajs/elysia#96]
Could we do something slick with the `/swagger` UI to auto-respect the user's dark-mode :: pg theme? Thanks 🙏

**Comment by SaltyAom** [comment]
Added in `@elysiajs/swagger` 0.7.3: https://github.com/elysiajs/elysia-swagger/blob/main/CHANGELOG.md#073---26-sep-2023

**Comment by gdibble** [comment]
Integrated and confirmed ✅ Looks grrrr8 🐯 

🙏 _ty everyone_
